### PR TITLE
Fix multiple gRPC interceptors

### PR DESCRIPTION
**Pull request by youngbupark**
# Description

Fix multiple gRPC interceptors

## Issue reference

#1177 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by youngbupark** [comment]
@jjcollinge Please review this pr. Adding middleware for metrics broke tracing middleware. this PR fixed the bug.

**Comment by jjcollinge** [comment]
Ah -  I did look at using `WithUnaryServerChain` earlier on but wasn't sure it was needed - good catch. Do we think it's feasible to add e2e test coverage for tracing?

**Comment by youngbupark** [comment]
> Ah - I did look at using `WithUnaryServerChain` earlier on but wasn't sure it was needed - good catch. Do we think it's feasible to add e2e test coverage for tracing?

Yes, we will have work item to create e2e test for tracing.

**Pull request merged**
