### PR TITLE
add snssqs pubsub provider

### PR DESCRIPTION
**Pull request by khous**
# Description

Add AWS SNS/SQS pubsub provider to the loader

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing 
* [x] Extended the documentation 
* [x] Specification has been updated 
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by pruthvidhodda** [comment]
Can you please [update components-contrib](https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md#submit-your-component) mod using `go get -u github.com/dapr/components-contrib`

**Comment by khous** [comment]
> Can you please [update components-contrib](https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md#submit-your-component) mod using `go get -u github.com/dapr/components-contrib`

Good catch. Done and building

**Comment by yaron2** [comment]
hey @khous, please resolve the conflict.

Also, can we call this `aws.sqs`? why is this sqssns? :)

**Comment by khous** [comment]
> hey @khous, please resolve the conflict.
> 
> Also, can we call this `aws.sqs`? why is this sqssns? :)

the module is called "snssqs". I chose this name to be as specific as possible. This binding uses the SNS service to send messages to SQS queues. In the case that AWS adds first class support for messaging via some other service, that binding can also be added underneath aws.

**Comment by pruthvidhodda** [comment]
> > Can you please [update components-contrib](https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md#submit-your-component) mod using `go get -u github.com/dapr/components-contrib`
> 
> Good catch. Done and building

Hey @khous just checking if this is done as I don't see any changes in go.mod/go.sum

**Comment by khous** [comment]
> > > Can you please [update components-contrib](https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md#submit-your-component) mod using `go get -u github.com/dapr/components-contrib`
> > 
> > 
> > Good catch. Done and building
> 
> Hey @khous just checking if this is done as I don't see any changes in go.mod/go.sum

This is what I see when I diff my fork with origin. It shows the expected changes to go.mod.

`$> git diff origin/master fork/master`

https://gist.github.com/khous/d1470f9e8c062bf2c9790d99e9245753#file-snssqs-patch-L41

**Comment by pruthvidhodda** [comment]
@yaron2 I'll merge this unless the naming needs to be changed.

**Pull request merged**
