### PR TITLE
Add volume mount support for sidecar

### PR DESCRIPTION
**Pull request by shubham1172**
# Description

This PR adds a way to mound Pod volumes to the container using two new Dapr annotations:
1. **dapr.io/volume-mounts**: for read-only volume mounts
1. **dapr.io/volume-mounts-rw**: for read-write volume mounts

The format of both the annotations are comma separated pairs of "pod-volume-name:/path/to/mount/in/container".
If a volume mount is annotated but not present in the pod, we ignore it and log a warning.

There are unit and e2e tests added. The e2e test follows a scenario similar to [custom-secrets-storage-using-local-file-secret-store](https://github.com/dapr/docs/blob/840486d9f8c6836b8125b755abe231c40c8250fb/daprdocs/content/en/operations/hosting/kubernetes/kubernetes-volume-mounts.md#custom-secrets-storage-using-local-file-secret-store), wherein an init container is used to populate data to the pod volume, which is then used as local file-based secret.

## Issue reference

Please reference the issue this PR will close: #4662

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Unit tests passing
* [X] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/issues/2454
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
Nice! I like this feature.

**Comment by shubham1172** [comment]
The e2e test has been verified manually and via the GH pipeline.
image

image

**Comment by shubham1172** [comment]
Apparently this is causing all other e2e tests to fail. Will investigate further.

**Review by halspang — COMMENTED** [review]
Change looks good overall, looks like you have a linter error though. Address that and we can see how the actions go.

**Review by halspang — DISMISSED** [review]

**Comment by shubham1172** [comment]
Failure seems unrelated: `tests/e2e/pubsub_grpc TestPubSubGRPC/publish_with_subscriber_error_test_redelivery_of_messages_grpc`

**Comment by shubham1172** [comment]
I see why e2e tests for Windows are failing. `Message:Back-off pulling image "docker.io/busybox"` - since there is no Windows version of it. One option is to write an custom init app with OS agnostic implementation.

**Review by artursouza — APPROVED** [review]

**Comment by shubham1172** [comment]
> > I see why e2e tests for Windows are failing. `Message:Back-off pulling image "docker.io/busybox"` - since there is no Windows version of it. One option is to write an custom init container binary with OS agnostic implementation.
> 
> Which test is requiring this image? This is new.

I was trying to introduce one, as the initcontainer image for injectorapp. Its job is to create a new file in the volume mount. I have not created an injectorapp-init golang binary that does that (and handles both Linux and Windows).

**Comment by shubham1172** [comment]
Both Linux and Windows error seem to be transient. Linux error fails for injectorapp test and Windows error fails for allowlists test with the same error type: `cannot find dapr sidecar in pod <app-name>-5cd8ccc77-g7pkl`. Shall we retrigger this once again?

**Review by artursouza — APPROVED** [review]

**Pull request merged**
