### PR TITLE
Make e2e run in HA mode

### LINKED ISSUE #2188: E2E tests should run with a highly available setup
Today, end to end tests run the non-production recommended setup with one instance per pod.

As between the two modes (non-HA and HA) the highly available setup is both the recommended one and also the more complex one in terms of different coordination between resources on an otherwise no resource dependency coordinated hosting platform (Kubernetes), it's recommended we run the e2e tests with `ha.enabled=true`.

/cc @youngbupark @msfussell

### PR DESCRIPTION
**Pull request by yaron2**
Do not merge before https://github.com/dapr/dapr/pull/2185.

Closes #2188

### CODE REVIEW

**Comment by yaron2** [comment]
I think the 30s timeout for helm install needs to increase, I've seen the KiND tests timeout when installing.

**Comment by youngbupark** [comment]
@yaron2 Once this e2e test are green, then I will cut 0.11.1 release

cc/ @mchmarny @msfussell @orizohar @yolember

**Comment by yaron2** [comment]
> I think the 30s timeout for helm install needs to increase, I've seen the KiND tests timeout when installing.
> 
> /cc @youngbupark

Also, I think as @tcnghia mentioned, we need to increase the mode size. Pods might be pending.

**Comment by youngbupark** [comment]
> > I think the 30s timeout for helm install needs to increase, I've seen the KiND tests timeout when installing.
> > /cc @youngbupark
> 
> Also, I think as @tcnghia mentioned, we need to increase the node size / add nodes.. Pods might be pending.

```
helm install \
	dapr --namespace=dapr-tests --wait --timeout 5m0s\
	--set global.ha.enabled=true --set-string global.tag=dev-linux-amd64 --set-string global.registry=localhost:5000/dapr --set global.logAsJson=true --set global.daprControlPlaneOs=linux ./charts/dapr
```

5 minutes timeout. So it may be because of node size.

**Comment by yaron2** [comment]
> > > I think the 30s timeout for helm install needs to increase, I've seen the KiND tests timeout when installing.
> > > /cc @youngbupark
> > 
> > 
> > Also, I think as @tcnghia mentioned, we need to increase the node size / add nodes.. Pods might be pending.
> 
> ```
> helm install \
> 	dapr --namespace=dapr-tests --wait --timeout 5m0s\
> 	--set global.ha.enabled=true --set-string global.tag=dev-linux-amd64 --set-string global.registry=localhost:5000/dapr --set global.logAsJson=true --set global.daprControlPlaneOs=linux ./charts/dapr
> ```
> 
> 5 minutes timeout. So it may be because of node size.

Yeah. The pods are probably pending, as helm install times out on KinD.

**Comment by youngbupark** [comment]
windows e2e test is failed. restarting test.

**Comment by yaron2** [comment]
> End-to-end tests failed on windows. Please check the [build logs](https://github.com/dapr/dapr/actions/runs/286890593)

Also, do we know why Windows tests are interminantly failing on the scheduled runs?

https://github.com/dapr/dapr/actions?query=workflow%3Adapr-test

**Comment by youngbupark** [comment]
pubsub test failed in windows e2e test. I hope this was  just an intermittent failure. 
```
Failed Platform.addApps(), deployment "pubsub-publisher" is not in desired state, received: &Deployment{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:DeploymentSpec{Replicas:nil,Selector:nil,Template:{{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []} {[] [] [] []  <nil> <nil>  map[]   <nil>  false false false <nil> nil []   nil  [] []  <nil> nil [] <nil> <nil> <nil> map[] []}},Strategy:DeploymentStrategy{Type:,RollingUpdate:nil,},MinReadySeconds:0,RevisionHistoryLimit:nil,Paused:false,ProgressDeadlineSeconds:nil,},Status:DeploymentStatus{ObservedGeneration:0,Replicas:0,UpdatedReplicas:0,AvailableReplicas:0,UnavailableReplicas:0,Conditions:[]DeploymentCondition{},ReadyReplicas:0,CollisionCount:nil,},}: etcdserver: request timed out2020/10/03 18:47:08 Running teardown...
FAIL	github.com/dapr/dapr/tests/e2e/pubsub	28.030s
Enter TestMain
```

**Comment by youngbupark** [comment]
> > > > I think the 30s timeout for helm install needs to increase, I've seen the KiND tests timeout when installing.
> > > > /cc @youngbupark
> > > 
> > > 
> > > Also, I think as @tcnghia mentioned, we need to increase the node size / add nodes.. Pods might be pending.
> > 
> > 
> > ```
> > helm install \
> > 	dapr --namespace=dapr-tests --wait --timeout 5m0s\
> > 	--set global.ha.enabled=true --set-string global.tag=dev-linux-amd64 --set-string global.registry=localhost:5000/dapr --set global.logAsJson=true --set global.daprControlPlaneOs=linux ./charts/dapr
> > ```
> > 
> > 
> > 5 minutes timeout. So it may be because of node size.
> 
> Yeah. The pods are probably pending, as helm install times out on KinD.

Turned off HA for KinD test for now. we can revisit it later. let's see how aks cluster tests go.

**Comment by tcnghia** [comment]
If it is difficult for the KinD workflows to support HA testing I think we could turn on the HA testing for AKS workflows first. That allows this PR to be checked in early leading to more testing/baking time (through scheduled workflows) before we cut the patch release.

Independently in that time window, we could try turning on the HA testing for KinD workflows.

**Review by youngbupark — APPROVED** [review]

**Pull request merged**
