### PR TITLE
Add perf test for state and pubsub

### PR DESCRIPTION
**Pull request by skyao**
# Description

Add in memory state
Add perf test for state 
Add perf test for pubsub

## Issue reference

https://github.com/dapr/dapr/issues/4506

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by skyao** [comment]
Status Update:

- fortio repo has been forked in dapr. see  https://github.com/dapr/fortio
- the dapr extend code of fortio is pushed in to v1.24.0-dapr branch of dapr fork repo. see     https://github.com/dapr/fortio/tree/v1.24.0-dapr
- the dapr tester app is udpated to use dapr fork repo and v1.24.0-dapr branch

Now there is only one blocking for this PR:

- the in-memory state: https://github.com/dapr/components-contrib/pull/1326

**Comment by skyao** [comment]
Good news that the in-memory state PR is merged: https://github.com/dapr/components-contrib/pull/1326

I will remove the replace to my repo and use the latest component-contrib repo.

**Comment by skyao** [comment]
@yaron2 @artursouza  This PR is ready to merge. 

BTW: as a bug (or limitation), the new perf test case won't run until it's merged into master branch.

**Review by daixiang0 — APPROVED** [review]

**Comment by daixiang0** [comment]
No new dependence was introduced, fossa-scan may be a "history issue".

**Comment by yaron2** [comment]
@mukundansundar is this not closed via https://github.com/dapr/dapr/pull/4543?

**Pull request merged**
