### PR TITLE
fix log-as-json arg

### PR DESCRIPTION
**Pull request by youngbupark**
# Description

fix log-as-json arg

## Issue reference

#1054 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by yaron2** [comment]
Do we need to run e2e for this?

**Comment by youngbupark** [comment]
> Do we need to run e2e for this?

Let's try it out.

**Comment by youngbupark** [comment]
> End-to-end tests failed.

It fails because of multi-arch change. let me fix! Sorry!!!

**Comment by youngbupark** [comment]
looks like it is intermittent failure

--- FAIL: TestHelloDapr (198.26s)
    --- FAIL: TestHelloDapr/green_dapr (197.64s)
        hellodapr_test.go:101: 
            	Error Trace:	hellodapr_test.go:101
            	Error:      	Received unexpected error:
            	            	Post http://52.143.91.75:3000/tests/green: dial tcp 52.143.91.75:3000: connect: connection timed out
            	Test:       	TestHelloDapr/green_dapr
    --- PASS: TestHelloDapr/blue_dapr (0.62s)
=== RUN   TestScaleReplicas

I will rerun e2e test

**Comment by yaron2** [comment]
> looks like it is intermittent failure
> 
> --- FAIL: TestHelloDapr (198.26s)
> --- FAIL: TestHelloDapr/green_dapr (197.64s)
> hellodapr_test.go:101:
> Error Trace: hellodapr_test.go:101
> Error: Received unexpected error:
> Post http://52.143.91.75:3000/tests/green: dial tcp 52.143.91.75:3000: connect: connection timed out
> Test: TestHelloDapr/green_dapr
> --- PASS: TestHelloDapr/blue_dapr (0.62s)
> === RUN TestScaleReplicas
> 
> I will rerun e2e test

I agree.

But since the other tests have passed, I think we can merge this.

**Pull request merged**
