### PR TITLE
Allows anybody to /assign via Dapr Bot

### PR DESCRIPTION
**Pull request by artursouza**
# Description

It allows anyone to `/assign` to an issue that is currently unassigned.

## Issue reference

Please reference the issue this PR will close: #3245

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by artursouza** [comment]
Validation: https://github.com/artursouza/test-github/issues/1
GitHub Action: https://github.com/artursouza/test-github/actions/runs/1096217470

**Review by yaron2 — APPROVED** [review]

**Review by dmitsh — DISMISSED** [review]

**Review by tanvigour — COMMENTED** [review]
This basically allows anyone to assign, didn't we want it to be a dapr community member?

**Comment by artursouza** [comment]
@tanvigour Thanks for the heads up. Yaron asked this to be open to everyone. Actually by looking into the code, this would only allow for people in the inclusion list in this file. I will change it to actually allow it for everyone.

**Comment by yaron2** [comment]
Thanks @tanvigour, we can start out this way (allow everyone) and then lock down to members if needed.

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
