### PR TITLE
Feat/pluggable components injector

### PR DESCRIPTION
**Pull request by mcandeia**
# Description

This PR is the complete implementation of [pluggable components injector](https://github.com/dapr/proposals/blob/main/0005-R-pluggable-components-injector.md) proposal with a single change mentioned here: https://github.com/dapr/dapr/issues/5668#issuecomment-1424666211

## Issue reference

Please reference the issue this PR will close: #5492 
See also: https://github.com/dapr/dapr/issues/5668#issuecomment-1424666211

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by ItalyPaleAle — COMMENTED** [review]
LGTM with just some small tweaks

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by philliphoff** [comment]
@ItalyPaleAle Did some testing of this with my own application/components and the components container is injected as expected.

That said, I've been struggling with a separate (but related) issue where the injected components container is not (always) creating the sockets files before `daprd` expected to find them.  I think there's still a race condition between those sidecar components to sort out.

**Comment by ItalyPaleAle** [comment]
Thanks for confirming!

**Comment by ItalyPaleAle** [comment]
@dapr/maintainers-dapr This is probably ready to be merged now, seems good!

**Review by ItalyPaleAle — APPROVED** [review]

**Review by artursouza — APPROVED** [review]

**Pull request merged**
