### PR TITLE
Merge Release 1.0

### PR DESCRIPTION
**Pull request by artursouza**
# Description

Merge release 1.0

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: endgame

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by yaron2 — APPROVED** [review]
LGTM

**Review by mukundansundar — CHANGES_REQUESTED** [review]
create a branch from release-1.0 and then merge it ....

**Comment by artursouza** [comment]
> create a branch from release-1.0 and then merge it ....

Why?

**Comment by mukundansundar** [comment]
> > create a branch from release-1.0 and then merge it ....
> 
> Why?

release-1.0 should not be updated with master right?

**Comment by artursouza** [comment]
> > > create a branch from release-1.0 and then merge it ....
> > 
> > 
> > Why?
> 
> release-1.0 should not be updated with master right?

release-1.0 will not be updated with master.

**Comment by artursouza** [comment]
> > > > create a branch from release-1.0 and then merge it ....
> > > 
> > > 
> > > Why?
> > 
> > 
> > release-1.0 should not be updated with master right?
> 
> release-1.0 will not be updated with master.

Github does not allow this merge. So, yes, creating a new PR with a new branch.

**Pull request closed without merging**
