### PR TITLE
Renaming conversation types to exclude "Alpha1"

### PR DESCRIPTION
**Pull request by WhitWaldo**
# Description

Minor refactoring to rename conversation types:

ConversationAlpha1Request -> ConversationRequest
ConversationAlpha1Response -> ConversationResponse
ConversationAlpha1Result -> ConversationResult

## Issue reference

Please reference the issue this PR will close: #8241 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] Code compiles correctly
- [ ] Created/updated tests
- [ ] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Specification has been updated / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Provided sample for the feature / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by WhitWaldo** [comment]
@daixiang0 I think it's 90% of the way there, but I don't know how to regenerate the protos in Go so the static check fails. Could you help me get this over the finish line?

**Comment by cicoyle** [comment]
I believe this is the command you are looking for: `make gen-proto`

**Review by elena-kolevska — DISMISSED** [review]
This change is in line with what we're doing for workflows.

**Review by daixiang0 — APPROVED** [review]
LGTM

**Comment by daixiang0** [comment]
> I believe this is the command you are looking for: `make gen-proto`

@WhitWaldo please use above command to update, after CI happy, we can make it land.

**Comment by WhitWaldo** [comment]
I've been poking at this off and on all night trying to get it to build and I'm having no such luck (despite the instructions [here](https://github.com/dapr/dapr/blob/master/dapr/README.md#proto-client-generation)).

image
image
image

Could someone else please generate the protos and merge in? The rest of it should be ready to go.

**Comment by elena-kolevska** [comment]
> Could someone else please generate the protos and merge in? The rest of it should be ready to go.

We should be good now, the proto check is passing.

**Comment by mikeee** [comment]
Triggered another rerun, hopefully it is more of a green run 🤞

**Comment by WhitWaldo** [comment]
> Triggered another rerun, hopefully it is more of a green run 🤞

Nearly got it this time - failed due to a connection issue in a different integration test. For what it's worth, these have been a problem in the .NET repo as well.

**Review by mikeee — APPROVED** [review]
Lgtm

**Comment by WhitWaldo** [comment]
> Lgtm

If it's not one integration test failing, it's another.

**Comment by WhitWaldo** [comment]
Another good try @mikeee - round four?

**Comment by mikeee** [comment]
I don't think these flaky tests should be blocking us 🤷‍♂️ we'll be here all day rerunning

**Pull request merged**
