### PR TITLE
Removing go vendoring in dapr repo

### LINKED ISSUE #799: Remove vendor dir?
## Describe the proposal

Because we are using go module and could set `GOPROXY`, I think we should remove vendor dir.

### PR DESCRIPTION
**Pull request by shalabhms**
# Description

Removing Go vendoring from dapr

## Issue reference

Closes #799

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by youngbupark** [comment]
@shalabhms when will we merge this change? 

cc/ @yaron2 @amanbha

**Comment by shalabhms** [comment]
> @shalabhms when will we merge this change?
> 
> cc/ @yaron2 @amanbha

@youngbupark ,
I have to measure the time with/without go vendoring. I will get the number by tomorrow /early next week and based on that will merge the PR.

**Comment by youngbupark** [comment]
> > @shalabhms when will we merge this change?
> > cc/ @yaron2 @amanbha
> 
> @youngbupark ,
> I have to measure the time with/without go vendoring. I will get the number by tomorrow /early next week and based on that will merge the PR.

You can easily measure it in Actions :) let's fix the merge-conflict and then CI will build pr build.

then you can measure the time.

**Comment by shalabhms** [comment]
cc @yaron2 , @youngbupark , @amanbha ,

Here is the build time with and without go vendoring:

With Go vendoring : 1 m 35 secs
Without Go vendoring : 1 m 54 secs.

So there is not much difference , based on the time, I think we can merge this change.

**Comment by shalabhms** [comment]
> > > @shalabhms when will we merge this change?
> > > cc/ @yaron2 @amanbha
> > 
> > 
> > @youngbupark ,
> > I have to measure the time with/without go vendoring. I will get the number by tomorrow /early next week and based on that will merge the PR.
> 
> You can easily measure it in Actions :) let's fix the merge-conflict and then CI will build pr build.
> 
> then you can measure the time.

Here is the build time with and without go vendoring:

With Go vendoring : 1 m 35 secs
Without Go vendoring : 1 m 54 secs.

So there is not much difference , based on the time, I think we can merge this change.

**Comment by yaron2** [comment]
I suggest we merge this after we cut the 0.4 release.

**Comment by shalabhms** [comment]
> I suggest we merge this after we cut the 0.4 release.

Sounds good. thanks @yaron2 .

**Pull request merged**
