### PR TITLE
feature: supported opentelemetry trace&metric and remove opencensus

### PR DESCRIPTION
**Pull request by 1046102779**
Signed-off-by: 1046102779 <seachen@tencent.com>

# Description

Step 1:  Modify package diagnostics & go  build cmd/daprd/main.go -o daprd; (**Done**)
Step 2: go build cmd/injector/main.go -o injector (**Done**)
Step 3: go build cmd/operator/main.go -o operator (**Done**)
Step 4: go build cmd/placement/main.go -o placement (**Done**)
Step 5: go build cmd/sentry/main.go -o sentry (**Done**)
Step 6: Modify unit tests.
Step 7: Modify grafana json. 
Step 8: Modify docs.

## Issue reference

https://github.com/dapr/dapr/issues/5225
https://github.com/dapr/dapr/issues/5336

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by 1046102779** [comment]
cc @yaron2 @ItalyPaleAle @daixiang0 

I submitted a version that was completely based on Opentelemetry, drastically transformed the observability of Dapr, completely removed Opencensus, and transformed the semantics of the entire initialization and reporting metrics. 

Tracing and metrics can be exported any monitoring systems.

**Comment by daixiang0** [comment]
Thanks for your contribution! 

Since it is a big feature, I think you can complete UT and make this PR ready for review and update grafana in other PR.

**Comment by yaron2** [comment]
@1046102779 can we close this PR? We already have full OTel support in Dapr 1.9

**Comment by 1046102779** [comment]
> @1046102779 can we close this PR? We already have full OTel support in Dapr 1.9

OK.

**Pull request closed without merging**
