### PR TITLE
Fix e2e test by updating global.tag when deploying dapr via Makefile 

### PR DESCRIPTION
**Pull request by shubham1172**
# Description

This PR updates the Makefile to use the correct tag while deploying dapr on k8s. Due to the linked PR, the `<dapr-tag>-windows-amd64` is now a manifest that points to 1809 and ltsc2022 Windows images. In e2e pipeline, the manifests are not created, so the pipeline tries to look for `<test-prefix>-windows-amd64` and fails. This PR updates the deploy step to look for the actual image `<test-prefix>-windows-lts2022-amd64` instead of manifest.

Example broken run: https://github.com/dapr/dapr/actions/runs/4372310169/jobs/7649326519

## Issue reference

Related to https://github.com/dapr/dapr/pull/5999

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by ASHIQUEMD — DISMISSED** [review]

**Comment by shubham1172** [comment]
Since the /ok-to-test action uses the workflow YAML from master, the changes from this PR won't be considered and it will fail!

**Review by ItalyPaleAle — APPROVED** [review]

**Pull request merged**
