### PR TITLE
Delayed start of the actor runtime because it depends on app configur…

### LINKED ISSUE #1493: Make secrets api available before the app is ready.
Make secrets api available before the app is ready.
Currently apis in dapr are available only after app has responded on app-port. For some of the apis like secrets, app might need it to do some initialziation, so atlease secret api should be available before the app starts. eg. when using secrets as Aspnet core configuration. 
Please see this discussion https://github.com/dapr/dotnet-sdk/pull/262#discussion_r414363850

cc @cmendible

### PR DESCRIPTION
**Pull request by jigargandhi**
…ation

App configuration is dependent on the app itself which might
need for the Dapr to start because it needs some secrets
fixes #1493

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by jigargandhi** [comment]
TODO: To add tests

**Comment by jigargandhi** [comment]
@amanbha @youngbupark  I have delayed the start of actor because actor depends on app to start (because actor needs app configuration) 
Please review and let me know if the commit makes sense. 
Then I will add unit test

**Comment by youngbupark** [comment]
> @amanbha @youngbupark I have delayed the start of actor because actor depends on app to start (because actor needs app configuration)
> Please review and let me know if the commit makes sense.
> Then I will add unit test

Thanks for the contribution. This change will allow users to access all Dapr APIs.

@yaron2 @msfussell @mchmarny @orizohar  @yolember / in the conversation, we would want to make secret APIs available in our discussion. can you please confirm this ?

**Comment by yaron2** [comment]
The only issue I see here is Dapr starting to pull messages from Input Bindings and/or Pub/Sub and trying to deliver it to the app before the app channel is ready.

**Comment by youngbupark** [comment]
> The only issue I see here is Dapr starting to pull messages from Input Bindings and/or Pub/Sub and trying to deliver it to the app before the app channel is ready.

ok so, then if we can hold two listeners for input binding and subscription, you agree on exposing all building block apis. I am ok with this as well. 

@orizohar @mchmarny @msfussell  any comments ?

**Comment by yaron2** [comment]
> > The only issue I see here is Dapr starting to pull messages from Input Bindings and/or Pub/Sub and trying to deliver it to the app before the app channel is ready.
> 
> ok so, then if we can hold two listeners for input binding and subscription before app channel is ready, exposing all building block apis is ok. it makes sense to me.
> 
> @orizohar @mchmarny @msfussell any comments ?

Sounds good to me. @jigargandhi can you make the required changes?

**Comment by jigargandhi** [comment]
Sure I will take a look at `hold two listeners for input binding and subscription before app channel is ready`

**Comment by jigargandhi** [comment]
I added a commit that delays init of pubsub and bindings.. If there is a consensus on this approach, I can add tests, else make more changes

cc @yaron2 , @orizohar @msfussell @mchmarny

**Comment by yaron2** [comment]
Hey @jigargandhi, see the build error:

`pkg/runtime/runtime.go:1635:20: a.figureOutComponentCategory undefined (type *DaprRuntime has no field or method figureOutComponentCategory)
`

**Comment by yaron2** [comment]
@jigargandhi I think you committed unrelated changes.. maybe it's best to fetch latest and start a new PR?

**Comment by jigargandhi** [comment]
@yaron2 I think so it would be appropriate to create a new PR. with only my changes, 
I think I messed up trying to resolve conflicts and did git. Do you usually do it with just ```git merge master``` ?

**Comment by jigargandhi** [comment]
Created a new PR #2215

**Pull request closed without merging**
