### PR TITLE
time.Now() usage updated to time.Now().UTC()

### PR DESCRIPTION
**Pull request by gophersumit**
# Description

Inconsistent usage of `time.Now()` is updated to `time.Now().UTC()`

## Issue reference

The issue this PR will close: #1039 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Created/updated tests
* [X] Unit tests passing
* [X] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks for this. As this PR changes times of certificates, I'll want to run some manual tests to validate no regressions are happening.

**Comment by yaron2** [comment]
@youngbupark e2e are failing on master branch..

**Comment by yaron2** [comment]
LGTM.

**Comment by youngbupark** [comment]
> @youngbupark e2e are failing on master branch..

This is interesting error message from service invocation tests.

```
--- FAIL: TestServiceInvocation (97.89s)
    --- FAIL: TestServiceInvocation/Test_singlehop_for_callee-0 (1.14s)
        service_invocation_test.go:115: 
            	Error Trace:	service_invocation_test.go:115
            	Error:      	Not equal: 
            	            	expected: "singlehop is called"
            	            	actual  : "invalid character 'B' after top-level value"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1 +1 @@
            	            	-singlehop is called
            	            	+invalid character 'B' after top-level value
            	Test:       	TestServiceInvocation/Test_singlehop_for_callee-0
```

**Pull request merged**
