### PR TITLE
state: adding consul as a statestore

### PR DESCRIPTION
**Pull request by anubhavmishra**
# Description

This PR adds HashiCorp [Consul](https://consul.io) as a state store after components-contrib/state/consul is merged.

https://github.com/dapr/components-contrib/pull/52

Fixes: #687

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by anubhavmishra** [comment]
@yaron2 I guess we can review and merge this now? Should be good to go right?

**Comment by yaron2** [comment]
@anubhavmishra can you update with the latest version of `contrib`?

**Comment by yaron2** [comment]
@youngbupark can you please check why the build is failing here?
https://github.com/dapr/dapr/runs/278452051

**Comment by youngbupark** [comment]
@anubhavmishra can you please run `make lint` and fix the linter error?

**Comment by anubhavmishra** [comment]
@youngbupark I am not sure why the lint error would be caused due to this branch. The error is:

```
Run make lint
# Due to https://github.com/golangci/golangci-lint/issues/580, we need to add --fix for windows
golangci-lint run --fix
level=error msg="Running error: context loading failed: failed to load program with go/packages: could not determine GOARCH and Go compiler"
make: *** [lint] Error 3
```

**Comment by anubhavmishra** [comment]
@youngbupark `make lint` works perfectly fine for me locally.

```
[anubhavmishra]-> (dapr)
->make lint
# Due to https://github.com/golangci/golangci-lint/issues/580, we need to add --fix for windows
golangci-lint run --fix
[anubhavmishra]-> (dapr)
```

I am running the latest version of `golangci-lint`: `1.21.0 built from 645e794 on 2019-10-15T18:15:04`

**Comment by anubhavmishra** [comment]
Looks like the tests are passing again! 🎉

**Comment by anubhavmishra** [comment]
@yaron2 I think I pulled the latest version of `contrib`.

**Comment by anubhavmishra** [comment]
Can someone merge it for me? :)

**Pull request merged**
