### PR TITLE
Add permission of “watch subscription"

### PR DESCRIPTION
**Pull request by Li-Yanzhi**
# Description

ClusterRole of "dapr-operator-admin" need the permission of “watch subscription" , otherwise pod  dapr-operator will continuously output the error of "Failed to watch *v1alpha1.Subscription: unknown (get subscriptions.dapr.io)"

## Issue reference

closes https://github.com/dapr/dapr/issues/2208

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [X] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks, this is a good addition.

While there's no functionality today for watching subscriptions, I think this change can be accepted to reduce the kubebuilder error logs and also to provide the basis for a future hot-reload functionality which will need this.

**Review by yaron2 — APPROVED** [review]
lgtm

**Comment by yaron2** [comment]
Can you please open a corresponding issue and replace it with the gitter reference?

**Comment by Li-Yanzhi** [comment]
> Can you please open a corresponding issue and replace it with the gitter reference?

Done.

**Review by youngbupark — APPROVED** [review]

**Comment by yaron2** [comment]
Thanks for this @Li-Yanzhi and welcome to Dapr.

**Pull request merged**
