### PR TITLE
Prevent github workflow from failing if windows integration tests fail

### PR DESCRIPTION
**Pull request by JoshVanL**
/cc @artursouza

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]
LGTM but can we also try to make the Windows tests work?

**Review by artursouza — APPROVED** [review]

**Comment by JoshVanL** [comment]
> LGTM to unblock builds, but can we also try to make the Windows tests work?

I agree. I would like to know why daprd seems to completely break down in serving on CPU constrained environments- assuming that is the issue. It doesn't seem windows OS specific to me.

**Comment by ItalyPaleAle** [comment]
> > LGTM to unblock builds, but can we also try to make the Windows tests work?
> 
> I agree. I would like to know why daprd seems to completely break down in serving on CPU constrained environments- assuming that is the issue. It doesn't seem windows OS specific to me.

We know from prior experience that the Windows agents are slower. Not sure exactly why, but it may be related to the OS being heavier and the fact that it runs more complex anti-malware. Even I/O is [significantly slower](https://github.com/actions/runner-images/issues/3577).

I also mentioned on Discord that I think we should change the ITs to run without the `-race` flag, since it makes tests much slower (and using more CPU), and it doesn't really help much in the case of ITs: since all binaries are pre-compiled, the flag can't help detecting race conditions there, and it can only detect race conditions in the test suite (which is of very little use IMHO).

**Comment by JoshVanL** [comment]
> I also mentioned on Discord that I think we should change the ITs to run without the -race flag, since it makes tests much slower (and using more CPU), and it doesn't really help much in the case of ITs: since all binaries are pre-compiled, the flag can't help detecting race conditions there, and it can only detect race conditions in the test suite (which is of very little use IMHO).

I'll open a PR to remove the `-race` flag and we can see what the result is.

**Pull request merged**
