### PR TITLE
Add Subscription metadata to SubscriptionRequest

### PR DESCRIPTION
**Pull request by jjcollinge**
# Description

Flow the metadata defined in the subscription through to the `SubscriptionRequest` so that it is available to the pubsub component to use.

Requires: https://github.com/dapr/components-contrib/pull/530

## Issue reference

Please reference the issue this PR will close: #2379 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@yittg can you kindly review this PR?

**Comment by jjcollinge** [comment]
Not super keen on route.route as a property name but not sure on a good alternative... maybe route.value and route.metadata or something 🤷‍♂️

**Comment by yaron2** [comment]
> Not super keen on route.route as a property name but not sure on a good alternative... maybe route.value and route.metadata or something 🤷‍♂️

Maybe `route.path`? btw there's a linter error on the e2e build: `pkg/runtime/runtime.go:418:4: unknown field 'Metadata' in struct literal of type "github.com/dapr/components-contrib/pubsub".SubscribeRequest
`

**Comment by jjcollinge** [comment]
@yaron2 yeah `route.path` is better - I'll update. Isn't the build error caused by the fact the [required PR](https://github.com/dapr/components-contrib/pull/530) isn't yet merged to introduce that field?

**Comment by yittg** [comment]
looks generally good, is there any other pending commits for these PR?

**Comment by jjcollinge** [comment]
@yittg 👍 - think it's good to go once the [depenednt PR](https://github.com/dapr/components-contrib/pull/530) is merged.

**Comment by cvictory** [comment]
Maybe you just use this pr: https://github.com/dapr/dapr/pull/2496

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
