### PR TITLE
Upgrade docker buildx version

### PR DESCRIPTION
**Pull request by shivamkm07**
Signed-off-by: Shivam Kumar <shivamkm07@gmail.com>

# Description

`docker/setup-buildx-action` has been failing due to an issue in upstream: https://github.com/docker/setup-buildx-action/issues/190. Upgrading to v2 fixes the issue.

Failed run: https://github.com/shivamkm07/dapr/actions/runs/4030388679
Successful run: https://github.com/shivamkm07/dapr/actions/runs/4030420000

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by shivamkm07** [comment]
cc @artursouza

**Comment by mukundansundar** [comment]
@shivamkm07 try using the latest version greater than 0.9.1 or remove that version pin

**Comment by shivamkm07** [comment]
> 

Latest version has been failing our workflow due to another issue in containerd. That's why 0.9.1 version was pinned. For details, see https://github.com/dapr/dapr/issues/5805

**Comment by crazy-max** [comment]
> @mukundansundar Latest version has been failing our workflow due to another issue in containerd. That's why 0.9.1 version was pinned. For details, see #5805

@shivamkm07 This issue with containerd was in BuildKit, not Buildx. Also it hasa been fixed in BuildKit 0.11.2 so should be fine with defaults now.

**Comment by shivamkm07** [comment]
> @shivamkm07 This issue with containerd was in BuildKit, not Buildx. Also it has been fixed in BuildKit 0.11.2 so should be fine with defaults now.

Yes but was waiting for buildx to release new version with Buildkit 0.11.2. Just saw buildx 0.10.1 has been released. Will update with defaults then.

**Review by berndverst — APPROVED** [review]

**Review by ItalyPaleAle — APPROVED** [review]

**Pull request merged**
