### PR TITLE
ci: add test skip case

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

# Description

Now CI would do tests in any cases, if there are only docs/config changes, no need to test all.

After this pr, those file changes would skip CI tests:
- all docs
- all `yml` under `.github`
- `.codecov.yaml`

Github action detail see https://github.com/marketplace/actions/skip-duplicate-actions.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by daixiang0** [comment]
@artursouza please review, it would speed up and up test :)

**Review by berndverst — APPROVED** [review]
LGTM

**Comment by berndverst** [comment]
@artursouza this looks good to me. Please also take a look :)

Thanks @daixiang0!

**Review by artursouza — DISMISSED** [review]

**Comment by daixiang0** [comment]
@artursouza slow merge process from bot?

**Comment by artursouza** [comment]
> @artursouza slow merge process from bot?

You force pushed, which dismisses my review. Bot only merges if my approval remains valid.

**Review by artursouza — APPROVED** [review]

**Comment by daixiang0** [comment]
Oh, I see.

**Pull request merged**
