### PR TITLE
bugfix: lazy load workload engine

### PR DESCRIPTION
**Pull request by famarting**
# Description

Fixes https://github.com/dapr/dapr/issues/7449

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@famarting please fix the linter issues

**Comment by famarting** [comment]
I was wondering if we should close this PR as after this comment https://github.com/dapr/dapr/issues/7449#issuecomment-1910786156 it became clear that the strategy implemented here won't be helpful for the majority of the usecases

**Review by artursouza — CHANGES_REQUESTED** [review]
Can there be an integration test to reproduce the issue?

**Review by cgillum — APPROVED** [review]
I think it's worth taking this fix. Appreciate your contribution!

**Comment by shivamkm07** [comment]
@famarting Did this PR fix the issue for you? i.e. if `GetWorkItems` is not called explicitly then is Engine autostarting when calling the Dapr Workflow APIs? 

Looking into the code, seems this solution won't work. When Dapr APIs are called, currently we already wait for engine to be started here: https://github.com/dapr/dapr/blob/c53fc16211e265cf486701bba9c2e94f50ee000f/pkg/api/universal/workflow.go#L37
and so the component implementation won't be called itself. 

If we want to start the Engine at every Dapr Workflow API call, it needs to be done at API level itself.

But IMO we shouldn't do this. The reason being if `GetWorkItems` is not called i.e. there is no stream listening for workItems, then the workflow won't be executed itself. The DTF Grpc executor will be anyway be blocked waiting for an application to connect (and send the work item). So isn't it better and more cleaner to wait for that at API itself, which is what we are doing rn. We can actually add a log line saying `Waiting for engine to be ready`.. something like that. Thoughts @cgillum ?

**Comment by yaron2** [comment]
> We can actually add a log line saying Waiting for engine to be ready

That log message won't mean anything to users and will hardly be discoverable.

**Comment by cgillum** [comment]
> But IMO we shouldn't do this. The reason being if GetWorkItems is not called i.e. there is no stream listening for workItems, then the workflow won't be executed itself. The DTF Grpc executor will be anyway be blocked waiting for an application to connect (and send the work item). So isn't it better and more cleaner to wait for that at API itself, which is what we are doing rn. We can actually add a log line saying Waiting for engine to be ready.. something like that. Thoughts cgillum ?

I think it's a valid point worth considering. The choice is to either block the API caller until a worker is ready or to accept the message and block its _processing_ until the worker is ready. Either way, these APIs are designed to be asynchronous, which is why I didn't see any harm in accepting the message even without a ready worker. It's one less error condition for the developer to worry about. But at the same time, if we know that the worker is supposed to be running, I can see that it might make it easier to diagnose problems if the client call times out because a worker didn't come online within a reasonable amount of time. Without a timeout, the developer is left wondering why nothing is happening after they try to start a workflow.

I could go either way on this.

**Comment by famarting** [comment]
I'm closing this PR, as it has been mentioned this change does not address the problem I described. 

For me my root problem was that the streamed connection to GetWorkItems was failing on my end for other reasons. So the changes in this PR do not bring any improvements

**Pull request closed without merging**
