### PR TITLE
Allow component metadata value to use {appID}

### PR DESCRIPTION
**Pull request by VerstraeteBert**
# Description

Today, component metadata values can use template values like `{uuid}` or `{podName}`. In addition, components can have some attributes that can be bound to a particular application. So, this PR adds `{appID} `as another possible template value. Which is relevant for, for example, https://github.com/dapr/components-contrib/issues/2397

## Issue reference

#5690

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by artursouza — APPROVED** [review]

**Comment by berndverst** [comment]
Please don't use this approach for the linked Kafka issue.

I don't like additional API calls in components.

Instead, the runtime should inject special purpose keys in metadata properties (see "consumerID" for such a special purpose metadata being handled by the library) ideally prefixed with "_dapr_" or something.

Then each component would only need to access these values from metadata.properties (available in the Init function of the component)

Do not add new API calls in components thanks!

**Comment by artursouza** [comment]
> Please don't use this approach for the linked Kafka issue.
> 
> I don't like additional API calls in components.
> 
> Instead, the runtime should inject special purpose keys in metadata properties (see "consumerID" for such a special purpose metadata being handled by the library) ideally prefixed with `_dapr_` or something.
> 
> Then each component would only need to access these values from metadata.properties (available in the Init function of the component)
> 
> Do not add new API calls in components thanks!

This is beyond Kafka. Kafka is one of the scenarios and there is no extra API call since the info is already there.

**Comment by berndverst** [comment]
Ah sorry, I thought this PR was something else (was reading from my phone)

We should additionally inject the appID into metadata properties but that doesn't have to be here.

**Comment by artursouza** [comment]
@VerstraeteBert this PR will require documentation in dapr/docs, similar to the other properties.

**Comment by VerstraeteBert** [comment]
Hab

> @VerstraeteBert this PR will require documentation in dapr/docs, similar to the other properties.

Updated docs here https://github.com/dapr/docs/pull/3062

**Pull request merged**
