### PR TITLE
Fix workflow perf test failure

### PR DESCRIPTION
**Pull request by shivamkm07**
# Description

## Issue reference

Please reference the issue this PR will close: #7468 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
Waiting on the latest run to succeed.

**Comment by shivamkm07** [comment]
> Waiting on the latest run to succeed.

Perf test for workflow passed.

**Pull request merged**
