### PR TITLE
Make AppHealthChecks stable and change default path to /healthz

### LINKED ISSUE #6217: Make App Health Checks stable (and change the default HTTP healthcheck path)
[App Health Checks](https://docs.dapr.io/developing-applications/building-blocks/observability/app-health/) were introduced in Dapr 1.9 and are behind a feature flag.

In Dapr 1.11 we should consider removing the feature flag to make the feature stable. Note that this won't enable them for everyone, as they still need to be explicitly enabled by the user with the `enable-app-health-check` CLI flag or annotation.

As part of the stabilization effort, I also propose we make a **breaking change** and switch the default path for HTTP healthchecks from `/health` to `/healthz`. This is the same paths that actor health checks use, so it will make it easier to converge them (see #6216)

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
# Description

Removes the "AppHealthChecks" feature flag to make app health checks stable. The feature is still not enabled by default and requires the user to opt-in with the `enable-app-health-checks` CLI flag/annotation.

**Breaking change:** The default path for HTTP health checks is changed from `/health` to `/healthz` so it's aligned with the path used by actors health checks. See: #6216 

## Issue reference

Fixes #6217

### CODE REVIEW

**Comment by mukundansundar** [comment]
@ItalyPaleAle what is the impact of this breaking change?

**Comment by mukundansundar** [comment]
> @mukundansundar if users were not specifically passing a value for app-health-check-path, the default was /health - see: https://docs.dapr.io/developing-applications/building-blocks/observability/app-health/#configuring-app-health-checks
> 
> I would like to change the default to /healthz for the reasons explained in the linked issue, to harmonize with how actor health checks work today (with the eventual goal of merging the two)
> 
> This will impact users that were relying on the default value being /health so they may need to either change the healthcheck endpoint in their apps, or explicitly set app-health-check-path=/health

ok ... is there a change required in the Dapr SDKs?
And for the time being can we have it query both `/healthz` and if not available `/health`? With a deprecation set for `/health` endpoint?

**Comment by mukundansundar** [comment]
Are there breaking changes needed in SDKs?

**Review by mukundansundar — DISMISSED** [review]

**Comment by yaron2** [comment]
> Are there breaking changes needed in SDKs?

Seconding this question

**Comment by yaron2** [comment]
> And for the time being can we have it query both /healthz and if not available /health

That would be much preferable, even if not required

**Comment by ItalyPaleAle** [comment]
> > Are there breaking changes needed in SDKs?
> 
> Seconding this question

I am not sure. I don't know which SDKs implement AppHealth, and whether they use HTTP or gRPC (not impacted), and whether they rely on the built-in health path. How would we go about finding this out?

> > And for the time being can we have it query both /healthz and if not available /health
> 
> That would be much preferable, even if not required

Is this additional complexity warranted in this case? Since we're talking about code that runs on init, it will be challenging to detect if /healthz responds with an error becuase it's the wrong endpoint, or because the app is just not yet ready.

Since what we're talking about is an alpha feature (so per contract we can make breaking changes), and users who depend on the old behavior only need to set a CLI flag.

I'm also concerned is that if we add this second option, users will begin depending on that and then deprecating this will be much harder.

**Comment by mukundansundar** [comment]
cc @yaron2 @artursouza I think this can be merged .... I agree that with moving this feature out of preview, we can have a breaking change and it will be better to have consistency in health endpoints across Dapr
Wdyt?

**Review by artursouza — APPROVED** [review]
I am fine merging as-is but can postpone to next release if people want to discuss the default health end point further.

**Pull request merged**
