### PR TITLE
dapr support rocketmq

### PR DESCRIPTION
**Pull request by x-shadow-man**
We have combined dapr and rocketmq at work, so the rocketmq component is introduced in the dapr project, so that dapr can support rocketmq

### CODE REVIEW

**Comment by msftgits** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/dapr/dapr?pullRequest=4016) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/dapr/dapr?pullRequest=4016) before we can accept your contribution.<br/><br/>:x: x-shadow-man [sign now](https://cla.opensource.microsoft.com/dapr/dapr?pullRequest=4016)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/dapr/dapr?pullRequest=4016) it.</sub>

**Comment by yaron2** [comment]
@x-shadow-man please run `go mod tidy` and push the changes.

**Comment by yaron2** [comment]
This PR is dependent on https://github.com/dapr/components-contrib/pull/1169.

cc @beiwei30

**Comment by x-shadow-man** [comment]
> This PR is dependent on [dapr/components-contrib#1169](https://github.com/dapr/components-contrib/pull/1169).
> 
> cc @beiwei30

finish 'go mod tidy'. pls feel free to check it. thx. @yaron2 @beiwei30

**Comment by x-shadow-man** [comment]
> > This PR is dependent on [dapr/components-contrib#1169](https://github.com/dapr/components-contrib/pull/1169).
> > cc @beiwei30
> 
> finish 'go mod tidy'. pls feel free to check it. thx. @yaron2 @beiwei30

Sorry. I made some git operation from "DCO's Details". It appears error. I'm confused.

**Comment by x-shadow-man** [comment]
> This PR is dependent on [dapr/components-contrib#1169](https://github.com/dapr/components-contrib/pull/1169).
> 
> cc @beiwei30

I'll 

> > > This PR is dependent on [dapr/components-contrib#1169](https://github.com/dapr/components-contrib/pull/1169).
> > > cc @beiwei30
> > 
> > 
> > finish 'go mod tidy'. pls feel free to check it. thx. @yaron2 @beiwei30
> 
> Sorry. I made some git operation from "DCO's Details". It appears error. I'm confused.

I'll try again for commit. thx.

**Comment by yaron2** [comment]
> > This PR is dependent on [dapr/components-contrib#1169](https://github.com/dapr/components-contrib/pull/1169).
> > cc @beiwei30
> 
> I'll
> 
> > > > This PR is dependent on [dapr/components-contrib#1169](https://github.com/dapr/components-contrib/pull/1169).
> > > > cc @beiwei30
> > > 
> > > 
> > > finish 'go mod tidy'. pls feel free to check it. thx. @yaron2 @beiwei30
> > 
> > 
> > Sorry. I made some git operation from "DCO's Details". It appears error. I'm confused.
> 
> I'll try again for commit. thx.

@x-shadow-man see here: https://docs.dapr.io/contributing/contributing-overview/#i-didnt-sign-my-commit-now-what.

**Comment by yaron2** [comment]
@x-shadow-man please run `go mod tidy` and push the changes.

**Comment by x-shadow-man** [comment]
> @x-shadow-man please run `go mod tidy` and push the changes.

ok，i'll do it. thx a lot

**Comment by x-shadow-man** [comment]
@yaron2 

i start a new PR for this.  because wrong operation cause merge failed. 

New PR pls refer to https://github.com/dapr/dapr/pull/4081

**Pull request closed without merging**
