### PR TITLE
[WIP] Filter daprEnabled label to reduce operator's memory consumption

### PR DESCRIPTION
**Pull request by snoopy-dooog**
Signed-off-by: Alen Polakof <apolakof@Alens-MacBook-Pro.local>

# Description

Enable label based filtering for operator reconciler. An increase in the number of pods was producing high memory consumption since all the pods in the cluster with StatefulSets and Deployment were being watched for. This changes to only watch the pods that are part of the aforementioned set and also contain the dapr enabled label.   

NOTE: Currently, I'm watching for the daprEnabledAnnotationKey since it was already there and seems like it could do the job from reading the code? But I could also inject another label to it. 

## Issue reference 

Please reference the issue this PR will close: #5693

### CODE REVIEW

**Comment by daixiang0** [comment]
Good catch!

**Comment by ItalyPaleAle** [comment]
As far as I know, `daprEnabledAnnotationKey` is an annotation, not a label, and K8s APIs cannot filter by annotations. The fact that [tests on K8s are failing](https://github.com/dapr/dapr/actions/runs/4099881314/jobs/7070247798) right now is an indicator that the Service is not created because K8s cannot filter by annotation.

I guess this _could_ work if you _also_ modified the Dapr injector to add a label to the Deployment in addition to an annotation? I am not sure if that's possible, but worth exploring.

CC: @yaron2

**Comment by yaron2** [comment]
@snoopy-dooog the e2e tests are failing. Other than that, this is a good addition, thanks.

**Comment by filintod** [comment]
you could create an annotation predicate: 
```
p := predicate.NewPredicateFuncs(func(object client.Object) bool {
		if v, ok := object.GetAnnotations()[daprEnabledAnnotationKey]; ok {
			return v == "true"
		}
		return false
	})
```

**Comment by ItalyPaleAle** [comment]
@filintod although that would filter the invocations that hit the reconciler code, not sure if that would be effective at reducing memory usage, as to my understanding (and I could be wrong), the client still receives all messages and keeps the state in cache anyways.

However, worth an attempt.

**Comment by filintod** [comment]
I think you are right, you would need to create a custom cache to pass to the manager (as mentioned here https://github.com/kubernetes-sigs/controller-runtime/blob/master/designs/use-selectors-at-cache.md)

The predicate above was to solve the issue of the label selector predicate using an annotation.

**Comment by snoopy-dooog** [comment]
Thanks for the comments. I will take a look at this on Friday and update it accordingly!

**Comment by filintod** [comment]
@snoopy-dooog I think the main problem, more than the operator deployment/sts, is from this line https://github.com/dapr/dapr/blob/master/pkg/operator/watchdog.go#L152. if as @ItalyPaleAle said we change the injector to add a label to the pod when it is patching it, then we can add an option to this get list of pods to filter the list to only retrieve those with the label set.  We might not need to have the custom cache if we never receive all the pods in the cluster.

**Comment by ItalyPaleAle** [comment]
Correct! But what you change is not the operator, which doesn't patch pods, but the Dapr Injector: https://github.com/dapr/dapr/blob/master/pkg/injector/pod_patch.go

**Comment by filintod** [comment]
yeah, but you still need to change the list operation in the operator

**Comment by filintod** [comment]
actually was thinking on this and we could work on this before working on the injector label-addition patch change. We can use a non-cached clientset (non controller-runtime clientset) + list with pagination. We are not really watching those pods that would need a cache and this runs on a ticker period.  

Adding the injector change is still worthwhile as then this client can query just the pods that don't have the label added by the injector that will reduce the resource usage of the operation here.

**Comment by ItalyPaleAle** [comment]
Moving to draft until #5937 is merged.

**Comment by snoopy-dooog** [comment]
Just saw this: https://github.com/dapr/dapr/pull/5937. Will work on the filter part in the weekend! Sorry, had some busy weeks

**Comment by filintod** [comment]
@snoopy-dooog I have created a [draft](https://github.com/dapr/dapr/pull/5944) that you could use/refactor, I think it is mostly ready but it does not have any tests nor I have tested it in a local environment.

**Pull request closed without merging**
