### PR TITLE
Fix perfs pt2

### PR DESCRIPTION
**Pull request by mikeee**
# Description

Partial revert removing references to k6-operator v0.0.14
Remove deprecated CRDs that are incompatible with controller-gen v0.15.0
Lowers `actor_reminder` expected QPS - https://github.com/dapr/dapr/pull/7677 related matter

Resulting in... all perf tests passing?

image

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
May the force be with you

**Review by JoshVanL — APPROVED** [review]

**Pull request merged**
