### PR TITLE
Add support for deployment/statefulset annotations

### PR DESCRIPTION
**Pull request by FerencoVonMatterhorn**
# Description

The current dapr Helm chart doesn't support annotations. Annotations are needed in many cases, e.g. to secure the Kubernetes cluster (AppArmor annotations).
Therefore I added `deploymentAnnotations` and `statefulsetAnnotations` so it's possible to set these settings for each deployment/statefulset. 

## Issue reference

closes https://github.com/dapr/dapr/issues/6802

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by berndverst** [comment]
@FerencoVonMatterhorn please fix the DCO check. By using the git `signoff` feature (see details on the failing DCO check).

You can run:

```
git rebase HEAD~2 --signoff
git push --force-with-lease origin feature/add-annotations-for-helm
```

**Review by berndverst — CHANGES_REQUESTED** [review]
LGTM once DCO is fixed.

@dapr/maintainers-dapr to merge if agreed

**Comment by FerencoVonMatterhorn** [comment]
@yaron2 can you re-test the PR? I don't think my changes affected the e2e test..

**Comment by FerencoVonMatterhorn** [comment]
@yaron2 Is there a reason why the PR is not merged ?

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
Skew tests are failing due to a change in the expected error message for service invocation tests between 1.11 and master.

**Comment by yaron2** [comment]
Thanks for this PR @FerencoVonMatterhorn

**Pull request merged**
