### PR TITLE
Disallow app-id containing dots

### LINKED ISSUE #5552: Dapr service can not be called when the app-id contains dots
## In what area(s)?

 /area runtime

## What version of Dapr?

1.8.x

## Expected Behavior

The services are resolved by app-id or I receive an error that dapr does not support app-ids containing dots.

## Actual Behavior

Dapr tries to resolve the service id as an url

## Steps to Reproduce the Problem

Try to do a service call to an app with id "services.my.great.service."

## Release Note

Depends on the solution chosen.

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
The daprd binary now shows a fatal error if `--app-id` contains a dot, which is not allowed.

Fixes #5552

### CODE REVIEW

**Review by mukundansundar — COMMENTED** [review]
Should the `ValidateKubernetesAppID` method in pkg/validation/validation.go be modified and used here as well to be completely consistent with k8s mode `AppID` validation?

**Comment by ItalyPaleAle** [comment]
> Should the ValidateKubernetesAppID method in pkg/validation/validation.go be modified and used here as well to be completely consistent with k8s mode AppID validation?

Uhm seems that method is used in the operator and injector. I don't think that's necessary, this validation was added to the `daprd` binary, so putting a dot in the `--app-id` flag there would just cause it to fail to start.

**Comment by ItalyPaleAle** [comment]
@mukundansundar oh yeah, good idea. I changed it to use a method from the validation package.

**Comment by mukundansundar** [comment]
@ItalyPaleAle if docs are not there please add docs for this.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
