### PR TITLE
ftr: add apache/dubbo output binding

### PR DESCRIPTION
**Pull request by LaurenceLiZhixin**
Signed-off-by: LaurenceLiZhixin <382673304@qq.com>

# Description

Add apache/dubbo output binding

## Issue reference

Mentioned in pr https://github.com/dapr/components-contrib/pull/1768

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@LaurenceLiZhixin we're currently experiencing a broken build, this is why the checks aren't passing. I'll merge with master once the fix is in.

**Comment by LaurenceLiZhixin** [comment]
Got it, thanks. @yaron2

**Comment by yaron2** [comment]
@LaurenceLiZhixin please resolve the conflicts

**Comment by LaurenceLiZhixin** [comment]
fixed @yaron2

**Comment by yaron2** [comment]
@LaurenceLiZhixin we now need documentation specs for the new binding.

**Pull request merged**
