### PR TITLE
Add release notes for Dapr 1.10.3

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Add release notes for Dapr 1.10.3 hotfix.

We're using this PR also to run E2E and perf tests

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
Looks like "/ok-to-test" is broken on the release branch due to changes to the pipeline. I've manually triggered the Action here, so it uses the pipeline from the correct branch: https://github.com/dapr/dapr/actions/runs/4318073173

**Review by artursouza — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
The linter keeps failing without any error. I've no idea what's going on, but I've updated the version of the linter to match what's on master. Hopefully this fixes it...

**Pull request merged**
