### PR TITLE
Fix skew tests

### PR DESCRIPTION
**Pull request by yaron2**
This PR fixes the version skew tests for service invocation.

### CODE REVIEW

**Review by daixiang0 — DISMISSED** [review]
LGTM

**Review by mukundansundar — CHANGES_REQUESTED** [review]
the test is failing still

**Comment by yaron2** [comment]
> the test is failing still

The test that's failing is targeting the 1.12 branch, this PR should be merged into 1.12 as well.

**Comment by JoshVanL** [comment]
@yaron2 this is done by adding a patch which gets applied to the relesse-1.12 e2e test suite https://github.com/dapr/dapr/tree/master/.github/scripts/version-skew-test-patches/e2e/release-1.12/dapr-sidecar-master

**Comment by yaron2** [comment]
@artursouza this is still taking the old code

**Comment by artursouza** [comment]
@JoshVanL any ideas here?

**Comment by JoshVanL** [comment]
@artursouza it is looking for the directory `.github/scripts/version-skew-test-patches/e2e/release-1.12/dapr-sidecar-master`. We are missing the last segment.

**Pull request merged**
