### PR TITLE
fix content-type override

### PR DESCRIPTION
**Pull request by yaron2**
Closes https://github.com/dapr/dapr/issues/1072

This PR does the following:

1. Treats content-type as any other header. Until now, it was treated in a special way and not respected in the caller side, only in the app channel side. This resulted in a custom content type not arriving to the app.

2. Fixed direct messaging API to not apply `application/json` content type on response header if one is already present from the invoke response.

3. Removes unneeded commented out code

### CODE REVIEW

**Comment by youngbupark** [comment]
@yaron2 Can you please add unit-test or e2e test to validate the scenario that the problem address ?

**Comment by malotho** [comment]
Super exciting that you have resolved this. Will this impact the actors as well?

**Comment by yaron2** [comment]
@malotho I'm not sure we are allowed to have actors sending non JSON formatted data.

@amanbha what do you think?

**Comment by amanbha** [comment]
> @malotho I'm not sure we are allowed to have actors sending non JSON formatted data.
> 
> @amanbha what do you think?

Yes, it will be json formatted.

**Comment by yaron2** [comment]
> @yaron2 Can you please add unit-test or e2e test to validate the scenario that the problem address ?

Added

**Pull request merged**
