### PR TITLE
Update pinned components-contrib

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Updates pinned components-contrib to include:

- dapr/components-contrib#2984 which makes the GetComponentMetadata method optional.
- dapr/components-contrib#3015 which adds `MultiMaxSize` to transactional state stores. This is useful with components like Cosmos DB which have a limit in the max number of transactions. Needed by #6647

PS: Closes #6701, closes #6718, closes #6719 too

### CODE REVIEW

**Comment by mukundansundar** [comment]
> Updates pinned components-contrib to include [dapr/components-contrib#2984](https://github.com/dapr/components-contrib/pull/2984) which makes the GetComponentMetadata method optional.

Just a clarity, this method was originally added for metadata builder only and not for dapr runtime to use. Now a different option is there with the above PR merge and thus this is not needed to be implemented anymore. 
Is my understanding correct?

**Review by mukundansundar — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
JS tests are currently broken in master. See https://github.com/dapr/dapr/pull/6726

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
