### PR TITLE
Add resiliency to state APIs

### PR DESCRIPTION
**Pull request by halspang**
# Description

Add resiliency to state APIs.

Signed-off-by: Hal Spang <halspang@microsoft.com>

## Issue reference

Please reference the issue this PR will close: Resiliency

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by mukundansundar — COMMENTED** [review]
@halspang How do we make sure that the operations are idempotent for set, delete and receptive bulk operations?

**Review by pkedy — APPROVED** [review]

**Comment by halspang** [comment]
> @halspang How do we make sure that the operations are idempotent for set, delete and receptive bulk operations?

Idempotency tends to come from either the user app, or the underlying statestore. This is a common concern in resiliency and I think is honestly something solved with a big warning flag on the documentation.

We have the option of introducing that as a feature flag to the statestore components, but I don't think it's something we'd capture here. 

What do you think?

**Comment by halspang** [comment]
> There is a failing test, but I approve assuming that is resolved.

I think I just made the tolerance for the test too low for non-local runs. 5ms is pretty short in a github action. I'll increase the window for success.

**Comment by daixiang0** [comment]
> > There is a failing test, but I approve assuming that is resolved.
> 
> I think I just made the tolerance for the test too low for non-local runs. 5ms is pretty short in a github action. I'll increase the window for success.

Is it better to set different value for different env, like local uses 5ms, CI use 100ms?

**Pull request merged**
