### PR TITLE
[DO NOT MERGE] Investigating performance regressions on service-invocation-grpc

### PR DESCRIPTION
**Pull request by mcandeia**
# Description

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@mcandeia can you explain a little about what regressions you're investigating?

**Comment by mcandeia** [comment]
I've been noticing that the perf tests are 90% of times failing on service-invocation-grpc tests. There is a slightly increase in the p90 latency (~0.5 ms max), I'm trying to find out which PR it started. 

I don't have any guess aside from @ItalyPaleAle changes regarding gRPC streaming, however I tested without it and seems the regression still there. Perhaps something related to infrastructure or a dependency? 

Will try older commits.

**Pull request closed without merging**
