### PR TITLE
Add bulk get in state store - Plan B

### PR DESCRIPTION
**Pull request by skyao**
# Description

Add BulkGet method on state store.

This Pr is for Plan B:

- Adding BulkGet method on state store which will return (bool, response, error)

- Dapr will calls BulkGet method first

    * if store supports BulkGet, it will return true with resposne list
    * if store doesn't support BulkGet, it will return false with nil response; dapr need to fallback to call get method one by one

## Issue reference

https://github.com/dapr/dapr/issues/2368

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by skyao** [comment]
@yaron2  Please help to review and merge the PR in component-contrib first. Then I will update go.mod file to remove this replacement:

```go
github.com/dapr/components-contrib => github.com/skyao/components-contrib v1.0.0-rc1.0.20201123121316-9f0ad6b4b713
```

**Comment by yaron2** [comment]
> @yaron2 Please help to review and merge the PR in component-contrib first. Then I will update go.mod file to remove this replacement:
> 
> ```go
> github.com/dapr/components-contrib => github.com/skyao/components-contrib v1.0.0-rc1.0.20201123121316-9f0ad6b4b713
> ```

Thanks, will do soon.

**Comment by yaron2** [comment]
> > @yaron2 Please help to review and merge the PR in component-contrib first. Then I will update go.mod file to remove this replacement:
> > ```go
> > github.com/dapr/components-contrib => github.com/skyao/components-contrib v1.0.0-rc1.0.20201123121316-9f0ad6b4b713
> > ```
> 
> Thanks, will do soon.

Done now.

**Comment by skyao** [comment]
@yaron2 Update branch and moved the replace in go.mod.

But some check failed: 

FAIL	github.com/dapr/dapr/tests/e2e/stateapp	609.125s

What happened for this 609 secondes? Can we restart and try again?

**Comment by yaron2** [comment]
> @yaron2 Update branch and moved the replace in go.mod.
> 
> But some check failed:
> 
> FAIL github.com/dapr/dapr/tests/e2e/stateapp 609.125s
> 
> What happened for this 609 secondes? Can we restart and try again?

I re-ran the tests now, but looks like the stateapp error occured in 4 different instances of the test, which means there might be a regression. Lets see what the new test results look like.

**Comment by yaron2** [comment]
@skyao there seems to be a regression.

**Comment by skyao** [comment]
@yaron2  Fixed, now it seems everything is OK.

**Comment by yaron2** [comment]
> @yaron2 Fixed, now it seems everything is OK.

Great, will take a look soon.

**Review by yaron2 — APPROVED** [review]
lgtm

**Pull request merged**
