### PR TITLE
Pluggable components injector

### PR DESCRIPTION
**Pull request by mcandeia**
# Description

This PR adds support for automatically injecting pluggable components based upon the declared components and its annotations. To see it working:

1) Install dapr
```shell
helm upgrade --install dapr dapr/dapr \
--namespace dapr-system \
--create-namespace \
--set global.registry=ghcr.io/mcandeia \
--set global.tag=1.10.0-components-injection-linux-amd64 \
--wait
```

2) Apply the following yaml
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: jsonlogic
  annotations:
    dapr.io/component-container-image: "ghcr.io/mcandeia/dapr-components:latest"
    dapr.io/component-container-env: "NAME=VALUE"
    dapr.io/component-container-volume-mounts-rw: "mymount:/tmp"
spec:
  type: bindings.jsonlogic
  version: v1
  metadata: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        dapr.io/enabled: "true" # required
        dapr.io/app-id: "my-app"
        dapr.io/inject-pluggable-components: "true"
    spec:
      containers:
        - name: "httpbin"
          image: "kennethreitz/httpbin"

```

Notice that three containers were created within the same pod.
- httpbin
- jsonlogic
- daprd

Also, I changed the pubsub e2e-test to use the injectable pluggable components containers.

## Issue reference

Please reference the issue this PR will close: #5492 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by mcandeia** [comment]
@yaron2 @artursouza @tmacam @philliphoff

**Review by ItalyPaleAle — DISMISSED** [review]

**Comment by yaron2** [comment]
Do not merge until proposal is accepted https://github.com/dapr/proposals/pull/9.

**Comment by artursouza** [comment]
Please, fix lint.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
