### PR TITLE
Revert "Add -dapr-listen-address option to daprd (#3429)"

### PR DESCRIPTION
**Pull request by wcs1only**
This reverts commit 87d76e4dbc4d910644c04a13cc479379cea7c98a.

Cherry picking from release branch.

See: https://github.com/dapr/dapr/pull/3456

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by daixiang0** [comment]
Could share revert reason here?

**Comment by wcs1only** [comment]
> Could share revert reason here?

Reason is in https://github.com/dapr/dapr/pull/3456. This PR is just the cherry-pick back into master from the release branch.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
