### PR TITLE
Support tracestate can be propagated in PubSub

### PR DESCRIPTION
**Pull request by CrazyHZM**
# Description

## Issue reference

Fix https://github.com/dapr/dapr/issues/3470
Flollow  https://github.com/dapr/components-contrib/pull/1264

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by beiwei30** [comment]
@CrazyHZM pls. solve compilation errors in CI, thanks.

**Comment by CrazyHZM** [comment]
> @CrazyHZM pls. solve compilation errors in CI, thanks.

Need to wait for https://github.com/dapr/components-contrib/pull/1264 to be merged, I will become the components-contrib master version in go mod tidy, and then let this ci pass

**Review by beiwei30 — DISMISSED** [review]
LGTM.

**Comment by artursouza** [comment]
PR from contrib is merged.

**Comment by CrazyHZM** [comment]
@artursouza @beiwei30 
I have adjusted the components-contrib master version, ci has passed, please review.
When this PR is merged, the components-contrib test will be able to change the version of dapr to master to make the Certification Tests normal.

**Review by yaron2 — APPROVED** [review]
lgtm

**Pull request merged**
