### PR TITLE
remove etcd state store to prepare to update grpc to new version

### PR DESCRIPTION
**Pull request by skyao**
# Description

Remove etcd state store temporarily to prepare to update grpc to new version.

## Issue reference

https://github.com/dapr/dapr/issues/2101

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by skyao** [comment]
Please merge the PR first:

https://github.com/dapr/components-contrib/pull/499

Then I will update go.mod to match components-contrib version: 

```go
require (
       github.com/dapr/components-contrib v0.4.1-0.20201009172644-b08e920cdd71
)
```

**Comment by skyao** [comment]
@yaron2  PR completed. Please help to review.

**Review by yaron2 — APPROVED** [review]

**Comment by skyao** [comment]
@yaron2 e2e tests on KinD (v1.19.1, ha) failed for the first time after I submit the fix of close method. But it succeed in the next round when you approved this changed. It seems this  e2e test is not so stable? 

Anyway, help to merge it and let's go on.

**Comment by skyao** [comment]
@yaron2 Please help to merge this PR. Then I can continue to push PRs to upgrade grpc version today. Thank you.

**Comment by yaron2** [comment]
> @yaron2 Please help to merge this PR. Then I can continue to push PRs to upgrade grpc version today. Thank you.

Will merge as soon as they pass.

**Comment by kazablock** [comment]
Hi 👋 
Will etcd as a state store be added back again?

**Pull request merged**
