### PR TITLE
improv: List components that will be loaded before actually doing it

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: GitHub <noreply@github.com>

# Description

List components that will be loaded before actually doing it when using `debug` logs. This allows you get an understanding of all the components that it will attempt to load to diagnose issues in case it fails to spin up.

> ⚠ This is my first Go contribution so sorry if this is totally wrong.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature has been discussed prior to implementation.

Please reference the issue this PR will close: N/A
Please reference the issue this PR will relate to: https://github.com/dapr/dapr/issues/2680

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@yaron2 Happy to abandon since it's crappy code, but would be good to have this in debug logs maybe?

**Comment by yaron2** [comment]
So this is not a regular loop, it's looping over a channel and thus you can't make that same for loop twice :)

Basically, we already print the component's name before it's starting to load here: https://github.com/dapr/dapr/blob/9d9c9943b8d2539ebfd9aae54d123b3308c51d2a/pkg/runtime/runtime.go#L1358

If you think we should log all components together re-open the issue or create a new one, and I'll be happy to take this on.

**Comment by yaron2** [comment]
So we're abandoning this *for now* but thanks for opening the issue and greater thanks for this PR.

**Comment by tomkerkhove** [comment]
No problem at all, I didn't expect this to get merged as it was crappy code 😅

The intend is to list everything in case it has issues with one, so that we can understand what all other components are.

**Pull request closed without merging**
