### PR TITLE
fix method invocation automatically unescape

### PR DESCRIPTION
**Pull request by Taction**
# Description

Do not automatically unescape params in method invocation.

## Issue reference

Please reference the issue this PR will close: #4008 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@Taction can you check why e2e tests are failing?

**Comment by Taction** [comment]
> @Taction can you check why e2e tests are failing?

Sure, I'll look into it asap.

**Comment by Taction** [comment]
@yaron2 I have fixed the e2e. This code https://github.com/dapr/dapr/blob/master/pkg/channel/http/http_channel.go#L193 will format the URL to `http://localhost:3000//method` in some cases, if fasthttp don't parse it will cause an error.

The latest e2e is a connection error, I don't think it is related to this pr and will try to look into it later.

**Comment by yaron2** [comment]
Thanks @Taction.

@artursouza can you please look at this and share your opinion about the possibility of this being a breaking change in the encoding parsing format?

**Comment by mcrio** [comment]
Hi, do you think this can be merged for the next release : )

**Comment by artursouza** [comment]
Can we have E2E test for this?

**Comment by Taction** [comment]
@artursouza e2e test added.

**Comment by mcrio** [comment]
Hi, do you think this can be merged for the next release? Cheers.

**Comment by BrianMcBrayer** [comment]
Tossing in my request for a merge too.

**Review by yaron2 — APPROVED** [review]
LGTM

**Comment by yaron2** [comment]
@artursouza please approve too. E2E are added.

**Review by artursouza — APPROVED** [review]

**Comment by yaron2** [comment]
Thanks for the fix @Taction!

**Pull request merged**
