### PR TITLE
Unserializing reminder period accepts more null-y values

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Fixes dapr/components-contrib#2786 which seems to be due to how MongoDB serializes the null value

### CODE REVIEW

**Review by berndverst — APPROVED** [review]

**Comment by berndverst** [comment]
LGTM!

**Comment by artursouza** [comment]
Let's merge this into 1.10 first then merge back to master.

**Review by artursouza — CHANGES_REQUESTED** [review]
Merging into 1.10 first.

**Comment by artursouza** [comment]
Closing in favor of https://github.com/dapr/dapr/pull/6284/files

**Pull request closed without merging**
