### PR TITLE
fix: fix bug when close a closed channel repeatedly

### PR DESCRIPTION
**Pull request by CodingSinger**
Change-Id: I0f3d071d714ab9a73b05f0669c453487ce7ef1d7

# Description

Solve the panic caused by repeatedly closing the closed channel  when calling `unblockPlacements` concurrently in pkg/actors/internal/placement.go:322

## Issue reference

#3364 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by beiwei30 — APPROVED** [review]
this change LGTM.

**Review by pkedy — APPROVED** [review]
LGTM

**Comment by CodingSinger** [comment]
Can someone help me with approval running workflows?

**Comment by CodingSinger** [comment]
@daixiang0  can you help me approval running workflows?

**Review by pkedy — APPROVED** [review]

**Comment by pkedy** [comment]
@CodingSinger a maintainer needs to approve the running workflow.

/cc @yaron2 @artursouza

**Comment by yaron2** [comment]
> @CodingSinger a maintainer needs to approve the running workflow.
> 
> /cc @yaron2 @artursouza

Running now.

**Comment by CodingSinger** [comment]
> > @CodingSinger a maintainer needs to approve the running workflow.
> > /cc @yaron2 @artursouza
> 
> Running now.

@yaron2 pls approve to run workflows again.

**Review by pkedy — APPROVED** [review]

**Review by yaron2 — APPROVED** [review]
lgtm

**Pull request merged**
