### PR TITLE
feature: add context to lock&pubsub API

### PR DESCRIPTION
**Pull request by 1046102779**
https://github.com/dapr/components-contrib/pull/2369

Signed-off-by: seachen <seachen@tencent.com>

cc @yaron2 @daixiang0 @ItalyPaleAle

### CODE REVIEW

**Comment by 1046102779** [comment]
cc @berndverst @ItalyPaleAle @yaron2

**Comment by 1046102779** [comment]
cc @berndverst @yaron2 @ItalyPaleAle @daixiang0 .

**Comment by 1046102779** [comment]
cc @berndverst @yaron2 @ItalyPaleAle @daixiang0

**Comment by berndverst** [comment]
Sometimes we need a week or so to get to PRs, no need to ping so many times.

**Review by berndverst — DISMISSED** [review]

**Comment by 1046102779** [comment]
> Sometimes we need a week or so to get to PRs, no need to ping so many times.

OK. I will pay attention next time.

**Comment by 1046102779** [comment]
image

```golang
Modified：     tests/apps/pubsub-bulk-subscriber/app.go
Modified：     tests/apps/pubsub-subscriber-routing/app.go
Modified：     tests/apps/pubsub-subscriber-routing_grpc/app.go
Modified：     tests/apps/pubsub-subscriber/app.go
Modified：     tests/apps/pubsub-subscriber_grpc/app.go
```
Fixed golangci-lint.
image

**Pull request merged**
