### PR TITLE
dapr support rocketmq

### PR DESCRIPTION
**Pull request by x-shadow-man**
I have combined dapr and rocketmq by rocketmq component. Now dapr can support rocketmq. thank you for merge.

BTW, I follow the instruction of DCO(https://docs.dapr.io/contributing/contributing-overview/#i-didnt-sign-my-commit-now-what.). But always can't make it. I'm confused.

### CODE REVIEW

**Comment by daixiang0** [comment]
Please try `git rebase master`, you can see the merge commit has DCO issue. Do not open new one again, it does not fix issues.

**Comment by x-shadow-man** [comment]
> go.mod

> Please try `git rebase master`, you can see the merge commit has DCO issue. Do not open new one again, it does not fix issues.

hi, daixiang0, thx for reply. I execute cmd of "git rebase master" and get the result of "当前分支 pubsub-loader-for-rockect 是最新的。" There's no remind about DCO issues.

**Comment by x-shadow-man** [comment]
> Please try `git rebase master`, you can see the merge commit has DCO issue. Do not open new one again, it does not fix issues.

BTW,  I execute the command below. there's no error locally.

git commit --amend --no-edit --signoff
git push --force-with-lease origin pubsub-loader-for-rockect

**Comment by x-shadow-man** [comment]
> > Please try `git rebase master`, you can see the merge commit has DCO issue. Do not open new one again, it does not fix issues.
> 
> BTW, I execute the command below. there's no error locally.
> 
> git commit --amend --no-edit --signoff git push --force-with-lease origin pubsub-loader-for-rockect



> > go.mod
> 
> > Please try `git rebase master`, you can see the merge commit has DCO issue. Do not open new one again, it does not fix issues.
> 
> hi, daixiang0, thx for reply. I execute cmd of "git rebase master" and get the result of "当前分支 pubsub-loader-for-rockect 是最新的。" There's no remind about DCO issues. @daixiang0

**Comment by daixiang0** [comment]
You can see the merge commit has DCO issue in the Github page here, not when execute command.

**Comment by x-shadow-man** [comment]
> You can see the merge commit has DCO issue in the Github page here, not when execute command.

I struggle a lot @daixiang0 . Now it seems ok. Pls feel free to check it. thx a lot.

**Comment by x-shadow-man** [comment]
> > You can see the merge commit has DCO issue in the Github page here, not when execute command.
> 
> I struggle a lot @daixiang0 . Now it seems ok. Pls feel free to check it. thx a lot.

@yaron2 I've finished commit. Please feel free to check it.

**Review by yaron2 — APPROVED** [review]
lgtm

**Comment by yaron2** [comment]
Thanks @x-shadow-man

**Comment by x-shadow-man** [comment]
> Thanks @x-shadow-man

Thanks Dapr & RocketMQ， thanks @yaron2 @daixiang0

**Pull request merged**
