### PR TITLE
Fix data race and concurrency problems of actor placement

### LINKED ISSUE #2961: Data race and concurrency problems of actor placement
## In what area(s)?

> /area placement
> /area actor

## What version of Dapr?

> 1.0.x

## Expected Behavior

Codes can handle concurrency robustly.

## Actual Behavior

Tether are some obvious data race and concurrency problems in implementation of `ActorPlacement`.  And there are lots of error when we run test with race detect.

#### Actual
Read:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L254  

Write:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L158
#### Expected
Should use atomic operation or guarded by mutex.

#### Actual
Read:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L144  

Write:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L234
#### Expected
Should use atomic operation or guarded by mutex.

#### Actual
Read:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L385

Write:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L361
#### Expected
Should be guarded by mutex

#### Actual
Read:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L374  
Write:
>https://github.com/dapr/dapr/blob/034022589c6fb4f9cf32aebc6278bd18d45e23b5/pkg/actors/internal/placement.go#L339

There both have data race and memory order problem.

#### Expected
Use condition variable to do wait and signal.

### streamConnAlive&streamConnectedCh
Similiar to `tableIsBlocked&unblockSignal`

## Steps to Reproduce the Problem

```Shell
cd pkg/actors/internal
go test ./... -race
```

## Release Note

RELEASE NOTE: **FIX** Data race and concurrency problems of actor placement.

### PR DESCRIPTION
**Pull request by luckyxiaoqiang**
# Description

Fix data race and concurrency problems of actor placement.

## Issue reference

Close #2961 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by skyao** [comment]
@luckyxiaoqiang Thank you for your gread PR to fix the data race problem.

I give some conments for the lock/unlock usage. To be safe to unlock, suggest to use defer.

**Comment by skyao** [comment]
@luckyxiaoqiang please help to resolve conflicts.

**Comment by luckyxiaoqiang** [comment]
> @luckyxiaoqiang please help to resolve conflicts.

Resolved.

**Review by skyao — APPROVED** [review]

**Comment by skyao** [comment]
@luckyxiaoqiang thank you for your PR.

**Pull request merged**
