### PR TITLE
Remove destination id header from app channel

### PR DESCRIPTION
**Pull request by yaron2**
Removes destination ID header from the app channel.

### CODE REVIEW

**Comment by yaron2** [comment]
@pruthvidhodda please verify with this fix that the header doesn't make its way to the client.

**Comment by pruthvidhodda** [comment]
> @pruthvidhodda please verify with this fix that the header doesn't make its way to the client.

Still able to see it at the receiving end
```bash
== APP ==   'destination-app-id': 'nodeapp',
```

**Comment by yaron2** [comment]
> > @pruthvidhodda please verify with this fix that the header doesn't make its way to the client.
> 
> Still able to see it at the receiving end
> 
> ```shell
> == APP ==   'destination-app-id': 'nodeapp',
> ```

Yeah, I found the problem, we have two VERY similar methods for HTTP/gRPC for adding the headers.

I just added the exclusion to the HTTP function, re-check.

We should really try and merge those two functions.

**Comment by pruthvidhodda** [comment]
Yeah, I just noticed that. For most part those two methods are doing the same thing.

Just verified, good to merge.

**Pull request merged**
