### PR TITLE
FIX input binding subscription when direction is defined

### PR DESCRIPTION
**Pull request by Syuparn**
# Description

Fix input binding to send only events that the app subscribes when direction is explicitly defined.

## Issue reference

Please reference the issue this PR will close: #7629

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by JoshVanL** [comment]
Thanks @Syuparn! Please can you add integration tests for this change?
https://github.com/dapr/dapr/tree/master/tests/integration

**Comment by yaron2** [comment]
@Syuparn the purpose of the input direction is to stop Dapr from sending an OPTIONS request to the app to check if the path is available, since this is explicitly telling Dapr that the app is expected to have a valid endpoint.

**Comment by Syuparn** [comment]
@yaron2 
> since this is explicitly telling Dapr that the app is expected to have a valid endpoint.

Does it mean that all apps in the cluster should be able to subscribe to the binding component when the input direction is specified in the component?

(If any app does not subscribe to it, the binding event may be sent to the app and an error is raised.)

**Comment by yaron2** [comment]
> @yaron2
> 
> > since this is explicitly telling Dapr that the app is expected to have a valid endpoint.
> 
> Does it mean that all apps in the cluster should be able to subscribe to the binding component when the input direction is specified in the component?
> 
> (If any app does not subscribe to it, the binding event may be sent to the app and an error is raised.)

You can use component scopes to limit the binding only to apps that are subscribing: https://docs.dapr.io/operations/components/component-scopes/

**Comment by Syuparn** [comment]
@yaron2 
> You can use component scopes to limit the binding only to apps that are subscribing: https://docs.dapr.io/operations/components/component-scopes/

Thank you for the information! When scopes are specified, events are sent to the expected app. I understand the input/output direction works as expected.

**Pull request closed without merging**
