### PR TITLE
add metrics for resiliency

### PR DESCRIPTION
**Pull request by piotrkpc**
# Description

## Issue reference

https://github.com/dapr/dapr/issues/4524

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@piotrkpc FYI we are in release code freeze for 1.8 at 6/21.

**Comment by yaron2** [comment]
@halspang can you review this also please? overall looks good.

**Comment by piotrkpc** [comment]
@yaron2 could you please approve this for CI jobs? It's strange that it failed for one version because all tests passes on my local env.

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
