### PR TITLE
Enable flag `ServiceInvocationStreaming` in all builds by default

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
As we work on enabling streaming everywhere, this PR changes the Makefile to enable the flag `ServiceInvocationStreaming`. This will allow us to test Dapr with the feature flag enabled more actively in the next weeks (just like we did before making Resiliency stable).

### CODE REVIEW

**Review by mukundansundar — APPROVED** [review]
lgtm. all failures in IT or E2E are not related to streaming.

**Comment by ItalyPaleAle** [comment]
SDK tests are currently failing due to bugs in the SDKs.

- Go: https://github.com/dapr/go-sdk/pull/424
- Python: https://github.com/dapr/python-sdk/pull/579

**Comment by mukundansundar** [comment]
@ItalyPaleAle Do we know why the Python SDK tests have failed here?

**Comment by ItalyPaleAle** [comment]
> @ItalyPaleAle Do we know why the Python SDK tests have failed here?

Bug in the SDK being tracked here: https://github.com/dapr/python-sdk/pull/579

**Comment by ItalyPaleAle** [comment]
Since this PR was tainted by the bot's bug, I'll re-create it

**Pull request closed without merging**
