### PR TITLE
Set Metadata option to get state store API

### PR DESCRIPTION
**Pull request by ksashikumar**
# Description

This PR sets `Metadata` option to [`state.GetRequest`](https://github.com/dapr/components-contrib/blob/08e654c0cd73207d21372eb95eda1f7ebc38208b/state/requests.go#L11) from Dapr Runtime.

As a follow up to this, the docs should also be updated [here](https://github.com/dapr/docs/blob/master/reference/api/state_api.md#get-state) ?

## Issue reference

This PR will close: https://github.com/dapr/dapr/issues/956

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

---
This change is [Reviewable](https://reviewable.io/reviews/dapr/dapr/1542)

### CODE REVIEW

**Comment by amanbha** [comment]
Thanks for the contribution @ksashikumar Could you please resolve conflicts and update the PR?

**Comment by ksashikumar** [comment]
> Thanks for the contribution @ksashikumar Could you please resolve conflicts and update the PR?

I've updated the PR. But the actions failed while bootstrapping the environment. Possibly because of the [Github Incident](https://www.githubstatus.com/incidents/6tcfpztf6j9m) ? 🤔

**Comment by ksashikumar** [comment]
@amanbha @yaron2 @shalabhms  is this good to merge?

**Comment by youngbupark** [comment]
> @amanbha @yaron2 @shalabhms is this good to merge?

yup we will merge once pr build is done.

**Pull request merged**
