### PR TITLE
Register APNs Output Binding

### PR DESCRIPTION
**Pull request by mfcollins3**
# Description

I updated `main.go` to register the APNs output binding that was added to `components-contrib`.

## Issue reference

See dapr/components-contrib#480 and dapr/components-contrib#481.

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#830
* [x] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#830
* [x] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#830

### CODE REVIEW

**Comment by youngbupark** [comment]
I do not see the go.mod change. Can you please run step 4 in this doc - https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md#submit-your-component ?

```
go get -u github.com/dapr/components-contrib
```

**Comment by mfcollins3** [comment]
Sorry, I didn't read the instructions properly. I just added it.

**Review by youngbupark — APPROVED** [review]
Thanks for your contribution!

**Comment by youngbupark** [comment]
seems like there is linter error. can you please run `make lint` and fix the lint issue?

**Comment by mfcollins3** [comment]
> seems like there is linter error. can you please run `make lint` and fix the lint issue?

It seems that the `go get -u github.com/dapr/components-contrib@master` is causing the problem. I'm looking at it.

**Comment by youngbupark** [comment]
```
Running [/home/runner/golangci-lint-1.31.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=warning msg="[runner] Can't run linter goanalysis_metalinter: bodyclose: failed prerequisites: 
[buildssa@github.com/dapr/dapr/pkg/components/exporters [github.com/dapr/dapr/pkg/components/exporters.test]: analysis skipped: errors in package: [/home/runner/work/dapr/dapr/pkg/components/exporters/registry_test.go:44:11: cannot use mockExporter (variable of type *\"github.com/dapr/dapr/pkg/testing\".MockExporter) as exporters.Exporter value in return statement: missing method Unregister]]"
  level=warning msg="[runner] Can't run linter unused: buildir: analysis skipped: errors in package: [/home/runner/work/dapr/dapr/pkg/components/exporters/registry_test.go:44:11: cannot use mockExporter (variable of type *\"github.com/dapr/dapr/pkg/testing\".MockExporter) as exporters.Exporter value in return statement: missing method Unregister]"
  level=error msg="Running error: buildir: analysis skipped: errors in package: [/home/runner/work/dapr/dapr/pkg/components/exporters/registry_test.go:44:11: cannot use mockExporter (variable of type *\"github.com/dapr/dapr/pkg/testing\".MockExporter) as exporters.Exporter value in return statement: missing method Unregister]"
```

This is related to this pr - https://github.com/dapr/components-contrib/pull/491

Please add `Unregister` method to test mock. Then it will be resolved.

https://github.com/dapr/dapr/blob/master/pkg/testing/exporter_mock.go

**Review by youngbupark — APPROVED** [review]

**Comment by youngbupark** [comment]
Thanks for your contribution!

**Comment by youngbupark** [comment]
@mfcollins3 Once [this build](https://github.com/dapr/dapr/actions/runs/301496485) is done, please download the [edge binary](https://github.com/dapr/dapr/actions/runs/301496485) and validate it. 

Please ensure that you have written the doc for APN binding component. 

Thanks for your contribution again! :)

**Pull request merged**
