### PR TITLE
Removed duplicate defaults from usage

### PR DESCRIPTION
**Pull request by jjcollinge**
# Description
Removed the duplicate defaults from `daprd` usage.

```
./dist/linux_amd64/release/daprd -h

Usage of ./dist/linux_amd64/release/daprd:
  -allowed-origins string
        Allowed HTTP origins (default "*")
  -alsologtostderr
        log to standard error as well as files
  -app-id string
        A unique ID for Dapr. Used for Service Discovery and state
  -app-port string
        The port the application is listening on
  -components-path string
        Path for components directory. Standalone mode only (default "./components")
  -config string
        Path to config file, or name of a configuration object
  -control-plane-address string
        Address for a Dapr control plane
  -dapr-grpc-port string
        gRPC port for the Dapr API to listen on (default "50001")
  -dapr-http-port string
        HTTP port for Dapr API to listen on (default "3500")
  -dapr-internal-grpc-port string
        gRPC port for the Dapr Internal API to listen on
  -enable-metrics
        Enable prometheus metric (default true)
  -enable-mtls
        Enables automatic mTLS for daprd to daprd communication channels
  -enable-profiling string
        Enable profiling (default "false")
  -log-as-json
        print log as JSON
  -log-level string
        Options are debug, info, warning, error, or fatal (default "info")
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -logtostderr
        log to standard error instead of files
  -max-concurrency int
        Controls the concurrency level when forwarding requests to user code (default -1)
  -metrics-port string
        The port for the metrics server (default "9090")
  -mode string
        Runtime mode for Dapr (default "standalone")
  -placement-address string
        Address for the Dapr placement service
  -profile-port string
        The port for the profile server (default "7777")
  -protocol string
        Protocol for the application: grpc or http (default "http")
  -sentry-address string
        Address for the Sentry CA service
  -stderrthreshold value
        logs at or above this threshold go to stderr
  -v value
        log level for V logs
  -version
        Prints the runtime version
  -vmodule value
        comma-separated list of pattern=N settings for file-filtered logging
```

## Issue reference
Please reference the issue this PR will close: #1388

## Notes
Not currently sure why `log-as-json` doesn't appear to print the default automatically like the other vars, therefore, I've had to leave the default in the description for the time being.

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by jjcollinge** [comment]
@yaron2 - just curious if there's a reason `enable-profiling` is a `flag.String` where as other toggles such as `enable-mtls` are `flag.Bool`. If there's no reason are you happy for me to change it to a `flag.Bool` and ensure whereever it's used (`pod_patch`) is updated accordingly?

**Comment by youngbupark** [comment]
> @yaron2 - just curious if there's a reason `enable-profiling` is a `flag.String` where as other toggles such as `enable-mtls` are `flag.Bool`. If there's no reason are you happy for me to change it to a `flag.Bool` and ensure whereever it's used (`pod_patch`) is updated accordingly?

I agree with @jjcollinge opinion. We need to make it consistent with the others.

**Comment by youngbupark** [comment]
@yaron2 Please review this pr.

**Comment by jjcollinge** [comment]
I have a commit to change the `enable-profiling` from string to bool but can't get e2e to pass locally. Will investigate tomorrow.

**Comment by youngbupark** [comment]
> I have a commit to change the `enable-profiling` from string to bool but can't get e2e to pass locally. Will investigate tomorrow.

I just fixed the e2e test. so it should work now.

**Comment by jjcollinge** [comment]
Can we please run e2e tests

**Comment by yaron2** [comment]
Well we certainly tested this now...

**Comment by jjcollinge** [comment]
I take it this isn’t transient as it failed twice, let me go rerun the e2e tests on my cluster.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jjcollinge** [comment]
Interesting, my local e2e tests were failing as the operator was in a crashloopbackoff due to the `dapr_mtls_off_config.yaml` using "false" for `spec.mtls.enabled`. Will rerun and investigate whether that was the only issue now.

**Comment by jjcollinge** [comment]
Ok so looks like this is an issue in `getSidecarContainer` - it has to set the container args using strings and therefore sets `enable-profiling` using `"true/false", so this messes up dapr's initialization given the new changes. Will look for a fix or roll this back.

**Comment by jjcollinge** [comment]
Note this changes behaviour slightly - rather than `--enable-profiling="false"` being set in `getSidecarContainer(...)` it is either absent if false or set `--enable-profiling` if true. This is similar to how the mTLS flag works.

**Comment by jjcollinge** [comment]
Can we rerun the e2e tests please

**Pull request merged**
