### PR TITLE
remaining comments from #4808 addressed

### PR DESCRIPTION
**Pull request by juazasan**
Signed-off-by: Juan Carlos Zamora <juazasan@msn.com>

# Description

This PR fixes the following comments from #4808 :
- https://github.com/dapr/dapr/pull/4808#discussion_r938967016
- https://github.com/dapr/dapr/pull/4808#discussion_r938969301
- https://github.com/dapr/dapr/pull/4808#discussion_r938969542
- https://github.com/dapr/dapr/pull/4808#discussion_r938969837

As for now, I am not addressing https://github.com/dapr/dapr/pull/4808#discussion_r938966348 as per the reasoning provided.

## Issue reference

Please reference the issue this PR will close: #4981 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Created/updated tests
* [X] Unit tests passing
* [X] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@juazasan is this ready now? Can we move this out of draft?

**Comment by juazasan** [comment]
> @juazasan is this ready now? Can we move this out of draft?

@yaron2 I am only waiting for @ItalyPaleAle he is fine with my response here: https://github.com/dapr/dapr/pull/4808#discussion_r973541983

**Comment by ItalyPaleAle** [comment]
@juazasan sorry I was on vacation and missed this PR. Yes, LGTM and also no concerns with your response to that comment :)

**Review by ItalyPaleAle — APPROVED** [review]
Please mark it as ready for review!

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
