### PR TITLE
Update README for discord and cleanup

### PR DESCRIPTION
**Pull request by AaronCrawfis**
Update links for Discord

Cleanup stale information

### CODE REVIEW

**Comment by artursouza** [comment]
Are we doing it? I am all in for Discord.

**Comment by AaronCrawfis** [comment]
> Are we doing it? I am all in for Discord.

Yes, waiting on a couple small things before we merge, but we will be going with discord

**Comment by yaron2** [comment]
@AaronCrawfis can we merge this?

**Review by orizohar — APPROVED** [review]

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis can we merge this?

Yes, I'll remove the label. We can merge this + community PR + docs PR

**Comment by yaron2** [comment]
> > @AaronCrawfis can we merge this?
> 
> Yes, I'll remove the label. We can merge this + community PR + docs PR

You need to resolve conflicts

**Pull request merged**
