### PR TITLE
initial impl for oci registry push

### LINKED ISSUE #6834: Feature Request: OCI Artefact support
## In what area(s)?

> /area runtime

> /area operator

> /area placement

> /area docs

/area test-and-release

## Describe the feature

Hello,

Before submitting a PR, I'd like to check if the team is open to releasing the Helm chart as an OCI artifact as well.

I've recently implemented this for the Argo CD helm-charts, which can be seen here: https://github.com/argoproj/argo-helm/pull/2209. The changes to the workflow were quite minimal.

Releasing the dapr charts as an OCI artifact would simplify distribution, especially within enterprise settings that use systems like Artifactory or Harbor.

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by salaboy**
# Description

Initial steps to push Helm Charts to OCI registry for easier distribution. 

## Issue reference
Fixes #6834

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by salaboy** [comment]
@yaron2 @artursouza can you folks help me out on this one? I need to find someone who has experience with the Dapr release pipelines to see if we can add these steps.. because it is just the last step.. I guess that if it fails we can just re-run this step alone

**Comment by artursouza** [comment]
@salaboy Can you show this working in your fork? This way we know it works. That is the best way to validate these before merging.

**Comment by salaboy** [comment]
@artursouza I did try this but unfortunately something before that step is failing in the pipeline -> https://github.com/salaboy/dapr/actions/runs/6272350965/job/17034136853 
I am not sure if someone can validate this if they have a stable way to do it

**Comment by daixiang0** [comment]
@artursouza check the log, seems we need create oci repo for it?

**Comment by salaboy** [comment]
@daixiang0 can you please give me a link to the logs? an OCI registry is just the dockerhub account, the same that we are using for the Dapr containers.

**Pull request closed without merging**
