### PR TITLE
Handle CEL expressions with more than one usage of a variable

### LINKED ISSUE #3693: PubSub routing fails when using `event` more than once
I ran into an issue with the following CEL expression for PubSub Routing.

`has(event.data.important) && event.data.important == true`

Using `event` more than once causes an error because it tries to compile an underlying CEL program with the variable defined multiple times.

## What version of Dapr?

1.4.0

## Expected Behavior

The `event` variable should be able to appear in the CEL expression multiple times.

## Actual Behavior

`event` can only appear once.

## Steps to Reproduce the Problem

Use the CEL expression above

## Release Note

RELEASE NOTE: **FIX** Allow PubSub routing CEL expressions with `event` used more than once.

### PR DESCRIPTION
**Pull request by pkedy**
# Description

Fixes handling CEL expressions with a root level variable that is used more than once

## Issue reference

Closes #3693

## Checklist

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

RELEASE NOTE: **FIX** Handle CEL expressions with more than one usage of a variable

### CODE REVIEW

**Review by artursouza — APPROVED** [review]

**Review by artursouza — CHANGES_REQUESTED** [review]
Please, add release notes and helm chart update for hotfix.

**Comment by yaron2** [comment]
Please merge into master.

**Comment by pkedy** [comment]
@yaron2 I'm also merging this into master after #3673 is merged

**Comment by yaron2** [comment]
> @yaron2 I'm also merging this into master after #3673 is merged

This won't be a hotfix.

**Pull request closed without merging**
