### PR TITLE
pin latest contrib, update all direct dependencies

### PR DESCRIPTION
**Pull request by berndverst**
Signed-off-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>

# Description

Pins latest contrib and updates all direct dependencies.

The version downgrades are correct, please ignore. These are indirect dependencies that were erroneously upgraded in contrib previously.

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by berndverst** [comment]
@artursouza I had already run /ok-to-test and it succeeded.

What are all these new test scenarios you are adding here?

**Comment by berndverst** [comment]
Thanks for rerunning the test. Looks like it was flakiness.

**Comment by berndverst** [comment]
@artursouza I removed the failing Fossa check on this PR also.

**Review by ItalyPaleAle — APPROVED** [review]

**Review by artursouza — APPROVED** [review]

**Pull request merged**
