### PR TITLE
Update missed labels to use `global.k8sLabels` instead

### PR DESCRIPTION
**Pull request by shubham1172**
Signed-off-by: Shubham Sharma <shubhash@microsoft.com>

# Description
As part of #5148, we introduced some new global labels, and updated charts to use them instead of hardcoding the labels directly. A few instances were missed in that PR. Note, there is no functional or behavioural difference, the chart will be exactly the same post rendering.

## Issue reference

Please reference the issue this PR will close: #5029 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by daixiang0 — APPROVED** [review]

**Comment by daixiang0** [comment]
Thanks, do we have a doc for all labels?

**Comment by shubham1172** [comment]
> Thanks, do we have a doc for all labels?

No @daixiang0, these are standard ones recommended by K8s https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

**Review by pravinpushkar — APPROVED** [review]

**Comment by daixiang0** [comment]
Sure, that is good.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
