### PR TITLE
Graceful Shutdown: Updates function signatures to match new API, and add context.TODO()s

### PR DESCRIPTION
**Pull request by JoshVanL**
Part of https://github.com/dapr/dapr/issues/2478

This PR updates functions with contexts as implemented [here](https://github.com/dapr/components-contrib/pull/2474).

Callers of these functions use a `context.TODO()`, with the intention of implementing proper context propagation in later PRs.

/milestone v1.11
/cc @ItalyPaleAle

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
Moving to draft until https://github.com/dapr/components-contrib/pull/2474 is merged

@JoshVanL please ping me on Discord and I'll explain the next steps to get PRs that modify the interfaces merged

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
I incorporated the latest master from components-contrib. Also had to update the linter or it wouldn't pass with Go 1.20 on my machine...

Please prioritize merging this now, or we won't be able to merge the release-1.10 branch into master for components-contrib

**Comment by ItalyPaleAle** [comment]
I incorporated the latest master from components-contrib. Also had to update the linter or it wouldn't pass with Go 1.20 on my machine...

@artursouza @yaron2 @mukundansundar 
Please prioritize merging this now, or we won't be able to merge the release-1.10 branch into master for components-contrib

**Comment by ItalyPaleAle** [comment]
The Azure tests are failing due to capacity issues: https://github.com/dapr/dapr/actions/runs/4199235143

**Comment by yaron2** [comment]
> The Azure tests are failing due to capacity issues: https://github.com/dapr/dapr/actions/runs/4199235143

Missed this.. :-\

**Pull request merged**
