### PR TITLE
Added ItalyPaleAle to dapr-bot

### PR DESCRIPTION
**Pull request by ItalyPaleAle**

### CODE REVIEW

**Comment by mukundansundar** [comment]
@ItalyPaleAle DCO fix ...

**Review by artursouza — DISMISSED** [review]

**Review by artursouza — DISMISSED** [review]

**Comment by yaron2** [comment]
Please add @daixiang0 as well to prevent the extra PR.

**Comment by ItalyPaleAle** [comment]
@yaron2  done

**Review by yaron2 — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
UGHHHH I just noticed the typo `[[`

**Pull request merged**
