### PR TITLE
[WIP] Pluggable components configuration

### PR DESCRIPTION
**Pull request by mcandeia**
Signed-off-by: Marcos Candeia <marrcooos@gmail.com>

# Description

As a part of the Pluggable Components feature coming on 1.9 version, this PR is a proposal on how the user would declare a pluggable component.

The idea behind having pluggable components is to provide extensibility for the components' developers, and commodity for the users

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprsystem
  namespace: default
spec:
  components:
    registries:
      ## to avoid component name clash, all components loaded from the registry should be prefixed with the registry alias.
      ## mcandeia.my-awesome-component@v1
      - name: mcandeia
        url: https://github.com/mcandeia/dapr-components ## same idea as github actions, the repository should contain a dapr.yaml in the root folder, which declares all components.
    inline:
      my-awesome-component:
        implements: [state, lock]
        container:
          # In runtime dapr defines an ENV VAR: DAPR_COMPONENT_SOCKET_PATH=~/.dapr/sockets/my-awesome-component.sock
          image: mcandeia/in-memory-state-store
          env:
            MY_ENV_VAR: value
```
The above format has support to:

- Define a pluggable component.
- Support for remote component registry. Allow declaring components and import them by just providing the registry url. Multiple could be used, github.com/dapr/components-contrib could have its own dapr.yaml file. (components certified by dapr-team)
### Registries
A pluggable component is nothing more than an ordinary image implementing a well-defined behavior. There are challenges associated on how the container

### Inline Pluggable Component
The key refers to the component name and the value are related to "how to run this container properly"

### Implements

As you can see a single container can implement multiples components at once. 

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@mcandeia I encourage you to close this PR and discuss this on the relevant issue. Specifically, the ideas proposed here deviate much from what was communicated on the issue, namely the registries concept. Can you explain why a registry is needed?

**Comment by yaron2** [comment]
In addition, the `ContainerSpec` we decided was not going to be implemented. See discussion here: https://github.com/dapr/dapr/issues/4925.

**Comment by yaron2** [comment]
> components certified by dapr-team

@mcandeia who or what is `dapr-team`?

**Comment by yaron2** [comment]
> this PR is a proposal on how the user would declare a pluggable component.

PRs do not replace or act as design discussions. As this PR contradicts the current design, please close this PR and engage in a discussion if you wish to change this. cc @johnewart

**Comment by mcandeia** [comment]
Thanks for the explanation @yaron2 , I wasn't aware of the discussion in the initial issue, this PR was still in progress and there's a lot of information missing because of it [Draft]+[WIP], and my idea is actually to propose something more elaborate. The registry idea is embryonic and will not be implemented, I just wanted to propose space for it to be possible (and I don't want to block it in the future).

Anyway I will comment directly on John's issue, thanks again!

**Comment by yaron2** [comment]
> Thanks for the explanation @yaron2 , I wasn't aware of the discussion in the initial issue, this PR was still in progress and there's a lot of information missing because of it [Draft]+[WIP], and my idea is actually to propose something more elaborate. The registry idea is embryonic and will not be implemented, I just wanted to propose space for it to be possible (and I don't want to block it in the future).
> 
> Anyway I will comment directly on John's issue, thanks again!

No problem, one of our responsibilities as maintainers is to coach new contributors and community members and I'm happy to do that.

As maintainers and approvers (reviewers), it is crucial for us to respond to PRs and issues in a timely fashion. This is not special for Dapr but is true for almost all OSS projects out there. To do that, we use a time and tested method of:

1. Finding / Creating the relevant issue
2. If this is a feature, propose a design and let maintainers know what they are going to expect when the PR(s) land
3. Get approval and start working, ideally by `/assign`ing yourself on an issue

This process is consistent across many OSS projects and newcomers, whether they are maintainers or contributors, can expect this familiar setting.

This ensures that:

1. Maintainers time isn't wasted by trying to reverse engineer a PR into a design
2. Contributor time isn't wasted by having their needing a major rewrite or rejected all-together
3. The community can weigh in and remains included. PRs are not where people expect discussions to happen - this is the place where code reviews happen

Regarding features that you would like to implement one day but not now, as in the case of your PR here, it's highly recommended to start a new issue completely and discuss everything there. Our fellow project Kubernetes calls these practices of doing anything more than what you need for now ["antiethical"](https://www.kubernetes.dev/docs/guide/pull-requests/#kiss-yagni-mvp-etc), with good reason.

**Comment by mcandeia** [comment]
I appreciate your advices @yaron2 , thanks again, and sorry for the confusion.

**Pull request closed without merging**
