### PR TITLE
simplify query JSON and fix typo in the nested label

### PR DESCRIPTION
**Pull request by dmitsh**
# Description

Simplify query JSON and fix typo in the nested label

## Issue reference

Please reference the issue this PR will close: #3960

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#2011
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by dmitsh** [comment]
cc @mukundansundar - this should simplify your work in Java SDK

**Comment by daixiang0** [comment]
Need to comment this change?

**Comment by dmitsh** [comment]
> Need to comment this change in doc?

Yes, I created an issue in docs for this. Will send a PR there once this one is merged.

**Review by mukundansundar — APPROVED** [review]
lgtm

**Review by artursouza — APPROVED** [review]

**Pull request merged**
