### PR TITLE
Disable actor state e2e for cosmos db

### PR DESCRIPTION
**Pull request by JoshVanL**
Currently, e2e test runs are failing on actor state TTL https://github.com/dapr/dapr/actions/workflows/dapr-test.yml

This looks to be because we are using the CosmosDB without TTL being enabled at the container level.

PR enables TTL, but set _no_ default value.

See: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-time-to-live?tabs=dotnet-sdk-v3

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]

**Review by mukundansundar — APPROVED** [review]

**Comment by mukundansundar** [comment]
@JoshVanL the tests seem to fail with a similar error.

**Review by ItalyPaleAle — CHANGES_REQUESTED** [review]

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by mukundansundar** [comment]
For now the newly added E2E actor state test has been disabled for cosmos's

**Review by ItalyPaleAle — CHANGES_REQUESTED** [review]
I think we figured out the issue.

Can you merge this commit?

```sh
curl -L "https://github.com/dapr/dapr/commit/ab73a6dee28c79cbf2b5a355b07c6aae0a49c57e.patch" | git am
```

Then if you re-enable the test, it should work

It was my mistake, I accidentally corrupted the partition key for cosmos DB while storing actor state. We'll need this PR ported into the release branch then

**Comment by JoshVanL** [comment]
Thanks @ItalyPaleAle, done!

**Comment by ItalyPaleAle** [comment]
Fixed now in #6199, so I'll close this

Additional issues included:

- In the Bicep file, the TTL property had to be put inside `resources`, otherwise it wasn't recongized
- There was a race condition in `assert.Eventually`. Because the function defined inside is executed in a background goroutine, storing state in variables defined outside of the lambda was causing data race conditions (our GitHub Actions agents seem to be very slow...

**Pull request closed without merging**
