### PR TITLE
Added proto for metadata api

### PR DESCRIPTION
**Pull request by jigargandhi**
# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2527 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by jigargandhi** [comment]
@mukundansundar  please review the proto changes

**Comment by jigargandhi** [comment]
@yaron2, @youngbupark  please review

**Comment by yaron2** [comment]
> @yaron2, @youngbupark please review

Will do tomorrow

**Review by yaron2 — APPROVED** [review]
lgtm

**Pull request merged**
