### PR TITLE
Helm chart tlc

### PR DESCRIPTION
**Pull request by trondhindenes**
# Description
Various Helm chart improvements. Some of these are to align the chart better with Kubernetes defaults, and to allow overriding options that were hard-coded:
- all subcharts now have a blank `resources` block as default, which can be overridden. Imiho this is much better than the existing hard-coded defaults, which were (imho) way off. (We need to improve documentation on the fact that users are expected to set resource settings themselves, and provide some sane examples)
- all subcharts now allow overriding the `runAsNonRoot`. This is a requirement in order to install the chart onto Minikube on Linux at least (if Minikube is using the default Docker driver)
- for docker-dashboard, allows specifying the service type
- sets the default `global.imagePullPolicy` to `IfNotPresent` which aligns with Kubernetes default (an important setting now that docker has implemented rate limiting. We want to be good citizens and not pull more than we have to)
- perform lookup on the cert data in `dapr-trust-bundle`. If this secret is already filled, and the `tls.issuer` vars are _not_ specified re-use existing cert (this makes running `helm upgrade` a lot smoother)
- for the `dapr-sidecar-injector-cert`, the ca cert is now stored in the secret, and lookup logic is added to let Helm re-use existing certs if they exist.This _should_ allow running helm upgrade without first exporting existing secrets.

The secret lookup/reuse can be tested as follows:
```bash
helm install dapr
# wait until initial secrets are "filled"
kubectl get secret dapr-trust-bundle -o go-template='{{range $k,$v := .data}}{{$k}}={{$v|base64decode}}{{"\n"}}{{end}}' > first.txt
helm upgrade
kubectl get secret dapr-trust-bundle -o go-template='{{range $k,$v := .data}}{{$k}}={{$v|base64decode}}{{"\n"}}{{end}}' > second.txt
cmp first.txt second.txt  # Command should not output anything, proving that the files are identical
```

Also restructures the table of available options into a less overwhelming format.

I'll add doc PR(s), but would like some feedback from the maintainers first that these changes are welcome

## Issue reference
Please reference the issue this PR will close: #212

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by trondhindenes** [comment]
ping @yaron2 I've added some lookup logic which _should_ allow us to run `helm upgrade` without first exporting existing certs. Very interested in your feedback on this.

**Comment by yaron2** [comment]
@trondhindenes this looks great, are there any breaking changes in this PR in some way or form?

**Comment by trondhindenes** [comment]
As far as I can see, there should be no breaking change here. Doc updates are needed, but that's it. Would be awesome to get this in before 1.0 to make upgrades safer.

**Review by yaron2 — APPROVED** [review]
LGTM

**Comment by yaron2** [comment]
@trondhindenes it's merged. docs time :)

**Comment by trondhindenes** [comment]
thanks @yaron2 ! :-)

**Pull request merged**
