### PR TITLE
Add JSON format log option to helm chart and sidecar

### PR DESCRIPTION
**Pull request by youngbupark**
# Description

Add JSON format log to helm chart and sidecar.
* Disable JSON format log for system components and sidecar by default
* Upgrade helm version from 0.2.0 to 0.2.1

## Issue reference

#1078 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by yaron2** [comment]
I am fairly confident we should not enable JSON formatting by default, but I want to be sure.

So I ask the following:

Can we take a look at what are the default logging formats for **production-grade** cloud-native systems so that we can judge better? My suggestion is to check:

1. Kubernetes
2. Linkerd
3. Istio
4. Prometheus

Just for the record, I do not know what their default formatting is.

**Comment by youngbupark** [comment]
> I am fairly confident we should not enable JSON formatting by default, but I want to be sure.
> 
> So I ask the following:
> 
> Can we take a look at what are the default logging formats for **production-grade** cloud-native systems so that we can judge better? My suggestion is to check:
> 
> 1. Kubernetes
> 2. Linkerd
> 3. Istio
> 4. Prometheus
> 
> Just for the record, I do not know what their default formatting is.

Istio/Knative are JSON formatted output by default.

Also, all production services that I worked on was json formatted log with metadata because JSON formatted log is easy to be parsed by collector such as collecterd or fluentd. I saw some service use csv format, but at the end, they had to change to json formatted.

But, plain text makes sense for Standalone mode.

**Comment by yaron2** [comment]
> > I am fairly confident we should not enable JSON formatting by default, but I want to be sure.
> > So I ask the following:
> > Can we take a look at what are the default logging formats for **production-grade** cloud-native systems so that we can judge better? My suggestion is to check:
> > 
> > 1. Kubernetes
> > 2. Linkerd
> > 3. Istio
> > 4. Prometheus
> > 
> > Just for the record, I do not know what their default formatting is.
> 
> Istio/Knative are JSON formatted output by default.
> 
> Also, all production services that I worked on was json formatted log with metadata because JSON formatted log is easy to be parsed by collector such as collecterd or fluentd. I saw some service use csv format, but at the end, they had to change to json formatted.
> 
> But, plain text makes sense for Standalone mode.

Knative is irrelevant, first because its not yet production grade, and second because its not a CNCF project.

> Also, all production services that I worked on was json formatted log with metadata because JSON formatted log is easy to be parsed by collector such as collecterd or fluentd. I saw some service use csv format, but at the end, they had to change to json formatted.

I understand, but a maintainer's personal experience should not be the criteria to dictate JSON formatting.
I used to run production workloads (and know many Azure customers) who do not use JSON formatting for their logs.

**Comment by yaron2** [comment]
> Istio/Knative are JSON formatted output by default

Also, I just installed Istio on default profiling mode, and it does not format to JSON by default.

**Comment by youngbupark** [comment]
> > > I am fairly confident we should not enable JSON formatting by default, but I want to be sure.
> > > So I ask the following:
> > > Can we take a look at what are the default logging formats for **production-grade** cloud-native systems so that we can judge better? My suggestion is to check:
> > > 
> > > 1. Kubernetes
> > > 2. Linkerd
> > > 3. Istio
> > > 4. Prometheus
> > > 
> > > Just for the record, I do not know what their default formatting is.
> > 
> > 
> > Istio/Knative are JSON formatted output by default.
> > Also, all production services that I worked on was json formatted log with metadata because JSON formatted log is easy to be parsed by collector such as collecterd or fluentd. I saw some service use csv format, but at the end, they had to change to json formatted.
> > But, plain text makes sense for Standalone mode.
> 
> Knative is irrelevant, first because its not yet production grade, and second because its not a CNCF project.
> 
> > Also, all production services that I worked on was json formatted log with metadata because JSON formatted log is easy to be parsed by collector such as collecterd or fluentd. I saw some service use csv format, but at the end, they had to change to json formatted.
> 
> I understand, but a maintainer's personal experience should not be the criteria to dictate JSON formatting.
> I used to run production workloads (and know many Azure customers) who do not use JSON formatting for their logs.


ok then, let me ask differently? How can we send logs and parse metadata from log before sending to ES or Azure monitor to allow operator to search the logs? If you have the better idea for this, I would like to learn.

**Comment by yaron2** [comment]
> Istio/Knative are JSON formatted output by default

Also, I just installed Istio on default profiling mode, and it does not format to JSON by default.

**Comment by yaron2** [comment]
> ok then, let me ask differently? How can we send logs and parse metadata from log before sending to ES or Azure monitor to allow operator to search the logs? If you have the better idea for this, I would like to learn.

Simple: by giving users the option to turn on JSON formatting, which we have. Simply not do it by default, which is what my comment is about.

**Comment by artursouza** [comment]
> > ok then, let me ask differently? How can we send logs and parse metadata from log before sending to ES or Azure monitor to allow operator to search the logs? If you have the better idea for this, I would like to learn.
> 
> Simple: by giving users the option to turn on JSON formatting, which we have. Simply not do it by default, which is what my comment is about.

Docker's log driver is JSON by default: https://docs.docker.com/config/containers/logging/configure/

If JSON is not the default what is the alternative?

**Comment by yaron2** [comment]
> > > ok then, let me ask differently? How can we send logs and parse metadata from log before sending to ES or Azure monitor to allow operator to search the logs? If you have the better idea for this, I would like to learn.
> > 
> > 
> > Simple: by giving users the option to turn on JSON formatting, which we have. Simply not do it by default, which is what my comment is about.
> 
> Docker's log driver is JSON by default: https://docs.docker.com/config/containers/logging/configure/
> 
> If JSON is not the default what is the alternative?

The alternative is plain text formatting, like we did so far, and like most (currently, every single one I've seen) projects do it **by default**.

**Comment by artursouza** [comment]
> > > > ok then, let me ask differently? How can we send logs and parse metadata from log before sending to ES or Azure monitor to allow operator to search the logs? If you have the better idea for this, I would like to learn.
> > > 
> > > 
> > > Simple: by giving users the option to turn on JSON formatting, which we have. Simply not do it by default, which is what my comment is about.
> > 
> > 
> > Docker's log driver is JSON by default: https://docs.docker.com/config/containers/logging/configure/
> > If JSON is not the default what is the alternative?
> 
> The alternative is plain text formatting, like we did so far, and like most (currently, every single one I've seen) projects do it **by default**.

How will users switch in production? A setting in the yaml?

**Comment by yaron2** [comment]
> > > > > ok then, let me ask differently? How can we send logs and parse metadata from log before sending to ES or Azure monitor to allow operator to search the logs? If you have the better idea for this, I would like to learn.
> > > > 
> > > > 
> > > > Simple: by giving users the option to turn on JSON formatting, which we have. Simply not do it by default, which is what my comment is about.
> > > 
> > > 
> > > Docker's log driver is JSON by default: https://docs.docker.com/config/containers/logging/configure/
> > > If JSON is not the default what is the alternative?
> > 
> > 
> > The alternative is plain text formatting, like we did so far, and like most (currently, every single one I've seen) projects do it **by default**.
> 
> How will users switch in production? A setting in the yaml?

Yes, it's an update in the Helm properties and then `helm update --`.

**Comment by msfussell** [comment]
I think the common scenario here is text logs and then developers turn on structured logging when then need to dive deeper into the info. Let's keep text log for now and hear from customers

**Comment by yaron2** [comment]
Envoy, used in production inside of Azure, has the log format default to `TEXT`.

https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log#default-format-string

**Comment by amanbha** [comment]
Rather than looking at from it json vs text logging perspective, I would like to pick a format which allows easy filtering in tools (may be like kibana) based on:
- Dapr or app I'd.
- timestamp.
- category, type of error.
- level of error.

**Comment by yaron2** [comment]
@amanbha I think that has already been covered by Young Bu in a PR that led to this. 

But in any case, even after you pick the properties, you still need to format it as text or Json.

**Comment by amanbha** [comment]
Yes, I know that, I am saying pick the format which makes filtering easier and afster

**Comment by yaron2** [comment]
In that case, text format is much more readable than JSON and more efficient.

It's a preference of the operator, and considering most other projects choose text formatting as the default, it makes sense.

**Comment by amanbha** [comment]
Looks like, we have a decision then :)

**Comment by youngbupark** [comment]
> In that case, text format is much more readable than JSON and more efficient.
> 
> It's a preference of the operator, and considering most other projects choose text formatting as the default, it makes sense.

I agree that text formatted log is more *human*-readable than JSON formatted logs.
but, text formatted log is difficult to be parsed as compare to JSON formatted with less parsing error. That's why I suggest using it by default in production.

When it comes to Enjoy logs you mentioned, text-format is similar to CSV formatted, but with space delimit.
```
[2016-04-15T20:17:00.310Z] "POST /api/v1/locations HTTP/2" 204 - 154 0 226 100 "10.0.35.28"
"nsq2http" "cc21d9b0-cf5c-432b-8c7e-98aeb7988cd2" "locations" "tcp://10.0.2.1:80"
```
As I mentioned in the beginning, I saw that some services uses CSV-like formatted text, but sometimes collector failed to parse it due to the incorrectly formatted log.

When it comes to the supported fields in log, **current Dapr plain-text formatted log provides the limited information** (excluded fields - timestamp, instance, ver, app_id), but JSON formatted has all. (@amanbha @yaron2 maybe we need to make both consistent. let me know if you all think we need to provide same info)

We can change the default option to text-plain, but users cannot filter and query the logs as much as they can do with json-formatted logs from ES and Azure Monitor.

User must use json-format log to query and filter their logs properly in es+kibana and Azure monitor. 

I do not think that investing time on parsing plain-text is worth.

**Comment by yaron2** [comment]
> but, text formatted log is difficult to be parsed as compare to JSON formatted with less parsing error

That is not entirely accurate, Azure Monitor and other tools actually allow for advanced query capabilities over text log formats + custom log formats.

> When it comes to Enjoy logs you mentioned, text-format is similar to CSV formatted, but with space delimit.

Indeed, not JSON, and even more so, space delimited.

>(@amanbha @yaron2 maybe we need to make both consistent 

**Yes, I believe we need to make them consistent. It is not reasonable that the level of details is affected by the text format.**

> We can change the default option to text-plain

Isn't it the default now, and this PR is to make it JSON?

> User must use json-format log to query and filter their logs properly in es+kibana and Azure monitor.

Again, that is not accurate. As it turns out, you have advanced query capabilities natively with Azure Monitor over non JSON formats. (some info [here](https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/parse-text) and [here](https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/get-started-queries).

Plus, Azure monitor does not expect JSON as default, and requires the user to use a special construct to query json, which it considers a custom data type. info [here](https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/json-data-structures).

I did some investigation into this, and actually `fluentd` has [built-in parsers](https://docs.fluentd.org/configuration/parse-section#parse-parameters) to transform text formats (and custom formats) into `json`, keeping the format has human readable and efficient on `stdout` and `stderr` but allowing for advanced manipulation in the forwarder.

**Comment by youngbupark** [comment]
> Plus, Azure monitor does not expect JSON as default, and requires the user to use a special construct to query json, which it considers a custom data type. info [here](https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/json-data-structures).

You point it out correctly. The reason why I want to use json-formated log is because of `parsejson()`. 
This is one of my favorite keywords in AzureMonitor and Kusto. *This is really powerful and really fast.*

OMS agent in AKS node collects container logs (no parsing) and emit to containerlogs table in Azure monitor. with a single keyword, you can convert to searchable fields. 

If you use plain-text, then you need to use complicated parsing keywords. I would like to avoid this. User may prefer simpler query. So I strongly recommend to use json-formatted log for azure monitor.

> I did some investigation into this, and actually `fluentd` has [built-in parsers](https://docs.fluentd.org/configuration/parse-section#parse-parameters) to transform text formats (and custom formats) into `json`, keeping the format as human readable and efficient on `stdout` and `stderr` but allowing for advanced manipulation in the forwarder.

If you convert to json, you need to specify field name specifically in plain-text log. Why not just using built-in json? fluentd has its own built-in json filter. In production, user rarely entered into production cluster. They do not want to access production cluster to see raw container logs unless their monitoring tools or services don't work. They should want to see and query on search engine such as azure monitor and es+kibana and creating dashboards. they're not seeing json formatted log. they see correctly-parsed log, not complicated json-formatted log. 

I disabled json-formatted logs now, but I would not spend the time to spend plain-text log search as much as user can search with json-formatted.

**Comment by yaron2** [comment]
Great!

So we have concluded that:

1. Most (if not all) production grade systems use text formatted logs
2. It is *possible* to filter and query text formatted logs in system such as Azure Monitor, GCP Stackdriver and AWS Cloudwatch
3. Using built-in tools inside systems such as `fluentd` and others, it is possible to convert text formats into JSON without outputting directly to JSON, which calls for work that is normally done and set-up by an SRE or app operator

We need to make sure that the same info (properties/fields) is used in all formats we support currently/will support in the future.

**Comment by youngbupark** [comment]
> Great!
> 
> So we have concluded that:
> 
> 1. Most (if not all) production grade systems use text formatted logs

I do not fully agree with this :) The production grade system provides json formatted logs. Production grade systems does not mean production service. 

> 2. It is _possible_ to filter and query text formatted logs in system such as Azure Monitor, GCP Stackdriver and AWS Cloudwatch

it is possible, but they will need additional complicated parsing query if they choose plain-text log. (at least Azure monitor)

> 3. Using built-in tools inside systems such as `fluentd` and others, it is possible to convert text formats into JSON without outputting directly to JSON, which calls for work that is normally done and set-up by an SRE or app operator

Converting text plain log to json may require additional work for our side and as I mentioned, it is possible to fail to convert text plain log to json--more error-prune as compared to json formated. In this iteration, we will not support the same search experience for plain-text logs like we support for json-formatted logs.

> We need to make sure that the same info (properties/fields) is used in all formats we support currently/will support in the future.

Agree I will create a pr to support the same fields. 

So the conclusion is:
1. Disable json formatted log by default
2. User needs to enable JSON formatted log if they want to use full-featured search experience that Dapr provides; if user choose text-formatted log, search capability will be limited.
3. If users want to use the full-featured search experience with plain-text log, we will prioritize it in the next milestone.

**Comment by yaron2** [comment]
> I do not fully agree with this :) The production grade system provides json formatted logs. Production grade systems does not mean production service.

Sorry, maybe I wasn't clear: I meant production-grade, stable software that is being run in production by external customers as well as in internal cloud managed environments, such as: Kubernetes, Linkerd, Envoy, Istio, Prometheus and others, provide TEXT formatted logs *by default*.

> Converting text plain log to json may require additional work for our side and as I mentioned, it is possible to fail to convert text plain log to json--more error-prune as compared to json formated. In this iteration, we will not support the same search experience for plain-text logs like we support for json-formatted logs.

This is not Dapr's responsibility, it's the app operator, done in the log-forwarder level and/or the query engine.

Something else to consider:

For production environments, users may use JSON or TEXT formatted logs.
For dev/test environments, users are likely to use TEXT.
For local dev, whether standalone OR k8s (minikube/kind/micro-k8s), users are likely to use TEXT.

In that case, it's preferable to set defaults to account for the majority of use cases.

I agree with what you wrote, and also with @msfussell. We'll keep TEXT as the default, and we can switch if there's user feedback saying they want it on by default. This is a non-code change.

**Comment by youngbupark** [comment]
* Set plain-text by default log format
* Keep consistent between plain-text and json logs - https://github.com/dapr/dapr/pull/1106

**Pull request merged**
