### PR TITLE
Use a different AKS cluster for perf tests (#2590)

### PR DESCRIPTION
**Pull request by wcs1only**
# Description

Add a separate per cluster with more powerful instance types for the perf tests.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2590
## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by wcs1only** [comment]
Manual test:

```
dapr % ./tests/test-infra/find_cluster.sh tests/test-infra/perf-list.txt
Selected Dapr Test Resource group: dapre2e
Selected Kubernetes Namespace: dapr-tests
Scanning dapr-aks-perf-01 ...
Switching to dapr-aks-perf-01 context...
The behavior of this command has been altered by the following extension: aks-preview
Merged "dapr-aks-perf-01" as current context in /Users/willardstanley/.kube/config
Trying to create dapr-tests namespace...
namespace/dapr-tests created
Created dapr-tests successfully and use dapr-aks-perf-01 cluster

dapr % make perf-build-deploy-run          
kubectl create namespace dapr-tests
namespace/dapr-tests created
kubectl create namespace dapr-tests-2
namespace/dapr-tests-2 created
helm repo add bitnami https://charts.bitnami.com/bi
...

**Review by yaron2 — APPROVED** [review]
lgtm

**Pull request merged**
