### PR TITLE
Update to latest contrib commit

### PR DESCRIPTION
**Pull request by yaron2**
Incorporate fix from https://github.com/dapr/components-contrib/pull/2268.

### CODE REVIEW

**Comment by yaron2** [comment]
The interface between `daprd` and contrib has been broken:

```
pkg/components/state/pluggable.go:457:10: cannot use fromConnector(l, pluggable.NewGRPCConnectorWithDialer(dialer, newStateStoreClient)) (value of type *grpcStateStore) as type "github.com/dapr/components-contrib/state".Store in return statement:
	*grpcStateStore does not implement "github.com/dapr/components-contrib/state".Store (missing GetComponentMetadata method)
```

@mcandeia can you advise?

**Comment by ItalyPaleAle** [comment]
That’s due to @berndverst’s change on metadata

**Comment by berndverst** [comment]
Just add this please: https://github.com/berndverst/dapr/commit/159383e4fac0e505f9d092ffa88e04aead8c13b5

In `components/state/pluggable.go`

```go
func (ss *grpcStateStore) GetComponentMetadata() map[string]string {
	return map[string]string{}
}
```

I was planning to make the PR to dapr/dapr, but I have a couple more such breaking changes for other component types.

**Comment by berndverst** [comment]
@yaron2 I'm adding `GetComponentMetadata() map[string]string` to every component type, which isn't a problem generally.. but it turns out the way the pluggable components code works, this must be updated in `dapr/dapr` for each pluggable component type.

**Comment by berndverst** [comment]
I'll open a separate PR to add this everywhere! @yaron2

**Comment by berndverst** [comment]
Please merge this PR first @yaron2  @artursouza 
https://github.com/dapr/dapr/pull/5494

**Comment by berndverst** [comment]
Merge master into this branch now and it should work!

**Comment by yaron2** [comment]
> Merge master into this branch now and it should work!

Thanks :)

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by yaron2** [comment]
Still failing @berndverst

**Comment by berndverst** [comment]
Oh there are a lot more places that need this method added apparently. But only in tests - what I added lets you build Dapr. Will take a look.

**Comment by berndverst** [comment]
@yaron2 please close this PR.

I kept your commits in my new PR which also fixes the error experienced here and also pins an even newer contrib.

https://github.com/dapr/dapr/pull/5496

**Pull request merged**
