### PR TITLE
Support k6 loadtesting + Actor Activation Stress test for Double Activation

### PR DESCRIPTION
**Pull request by mcandeia**
# Description

This PR adds support to k6 loadtesting by including a new `LoadTest` method to our test platform. For k6 specifically it is implemented only for kubernetes.

Summary is not experted yet but k6 supports its own internal checks and those are being used to verify if test was successfully executed.

> In draft until a new https://github.com/grafana/k6-operator is released including my fix, meanwhile I'm using my private k6 operator image.

## The double activation test

The double activation test is basically a stress test under a single actor ID that uses a single a redis instance for locking purposes.

So the idea behind is that for each single call to the actor's `Lock` [method](https://github.com/dapr/dapr/pull/5514/files#diff-271e6fe59970199442db695883c2dc697825cc66909dea31657d6e7a95fd2980R52) will 

1) Acquire lock for 1s
2) Release lock and, if error, wait for 1s to make sure the lock was released before returning

Notice that if any disruption occurs on redis or on the app side between these two steps so a false-positive double activation could be caught.

The idea is that if we allow for double activation it means that the `Lock` could be executed before the lock is released.

## Issue reference

Please reference the issue this PR will close: #5471 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by mcandeia** [comment]
@sarsharma @akhilac1 would love to receive feedback from you folks

See [this](https://github.com/dapr/dapr/pull/5514/files#diff-f444ea727e20de932ac66bfd89ee17f18f622cdaf8cc10b3e2a5ab1804e1954aR74) as an example

Considerations:

1. The test summary is being printed on console and the test result is based on k6 job status - I'm having conversations regard exporting these metrics to somewhere (perhaps grafana cloud would work?)
2. There's no way to use any JS bundle yet (which means that you can't have node_modules or something like this, so you're limited to xk6 extensions)

**Review by ItalyPaleAle — APPROVED** [review]

**Review by artursouza — APPROVED** [review]

**Pull request merged**
