### PR TITLE
Do not type convert data to string for transaction API.

### PR DESCRIPTION
**Pull request by mukundansundar**
# Description

Found an issue for Transaction API via Java Integration Tests.

When the state is stored via an upsert call made and the got back via the normal getState API call, it can be observed that there is an extra Json Marshal happening in the code.

Example:

```json
data: "\"{\\\"propertyA\\\":\\\"data in property A\\\",\\\"propertyB\\\":\\\"data in property B\\\"}\""
```
Instead of

```json
data: "{\"propertyA\":\"data in property A\",\"propertyB\":\"data in property B\"}"
```
The second output is what we have when we have a normal save and get state call done via Dapr.

The code change here, checks if the incoming request value is a byte array or not and then properly serializes the value.
## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/2016

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by mukundansundar** [comment]
Code still needs the change from components contrib to be merged first and ref updated in this repo.

**Comment by mukundansundar** [comment]
Need to run the E2E tests only after the new components contrib is merged in. Will be updating this PR once that code is merged in.

**Review by youngbupark — APPROVED** [review]

**Review by wcs1only — APPROVED** [review]

**Review by mchmarny — APPROVED** [review]
/lgtm

**Review by vinayada1 — APPROVED** [review]

**Review by artursouza — APPROVED** [review]

**Pull request merged**
