### PR TITLE
Removing the alicloud prefix from the alicloud OSS components to matc…

### PR DESCRIPTION
**Pull request by pkedy**
* Removed the `alicloud.` prefix from the Alibaba OSS components to match the documentation site.
* Did some alphabetical sorting of components here and there...  tidying up.  Didn't do all of them so there wasn't too much noise in this PR.

### CODE REVIEW

**Review by artursouza — APPROVED** [review]
@yaron2  I think this change should be in for 1.. Thoughts?

**Review by halspang — APPROVED** [review]
I like the change. Should we also unify it across azure/aws/gcp? As though are already released I know it'd break existing configs, but it could be worth unifying the naming convention for components.

**Comment by yaron2** [comment]
> @yaron2 I think this change should be in for 1.. Thoughts?

We should add the alicloud prefix only if the component is specific to Alicloud.

There's nothing to change for Azure/AWS/GCP.

**Comment by halspang** [comment]
> We should add the alicloud prefix only if the component is specific to Alicloud.
> 
> There's nothing to change for Azure/AWS/GCP.

Just for my own clarification, what you're saying is components that **run** in AWS/Azure/GCP get the prefix and the distinguishing factor here is that these can run external to Alicloud?

**Comment by yaron2** [comment]
> > We should add the alicloud prefix only if the component is specific to Alicloud.
> > There's nothing to change for Azure/AWS/GCP.
> 
> Just for my own clarification, what you're saying is components that **run** in AWS/Azure/GCP get the prefix and the distinguishing factor here is that these can run external to Alicloud?

Correct.

**Pull request merged**
