### PR TITLE
feat(diagnostics/binding): add binding reading event to report metrics for grpc protocol

### PR DESCRIPTION
**Pull request by 1046102779**

### CODE REVIEW

**Review by yaron2 — APPROVED** [review]
lgtm

**Comment by yaron2** [comment]
@1046102779 there are minor linter issues.

**Review by yaron2 — CHANGES_REQUESTED** [review]
Fix linter issues

**Comment by 1046102779** [comment]
> Fix linter issues

fixed.

**Comment by 1046102779** [comment]
successed.
wecom-temp-5fe13ca999b53e94db7018833d04762e

**Pull request merged**
