### PR TITLE
Upgrade to Go1.19, Golangci-lint v1.48.0, address all linter issues

### PR DESCRIPTION
**Pull request by berndverst**
# Description

Upgrades to Go1.19
Now requires Golangci-lint v1.48.0
Address all existing linter issues in the codebase
All pints latest components-contrib

Re-enables gosec linter
Disables exhaustruct linter

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by berndverst** [comment]
The only real change is `grpc.WithInsecure()` which is deprecated now being `grpc.WithTransportCredentials(insecure.NewCredentials())`

**Comment by berndverst** [comment]
@yaron2 @artursouza please review as soon as possible to avoid merge conflicts etc

**Comment by yaron2** [comment]
> @yaron2 @artursouza please review as soon as possible to avoid merge conflicts etc

Thanks for this change. Was the non-snake case replacement a nightmare?

**Comment by berndverst** [comment]
> > @yaron2 @artursouza please review as soon as possible to avoid merge conflicts etc
> 
> Thanks for this change. Was the non-snake case replacement a nightmare?

@yaron2 yes the non-snake stuff was horrible. I really wish that linter would not complain about imports. Would be great if it were smart enough only to look at new variable declarations ARGH

**Review by artursouza — APPROVED** [review]

**Pull request merged**
