### PR TITLE
Populate traceparent and grpc-trace-bin in response header

### PR DESCRIPTION
**Pull request by shalabhms**
# Description

Populate traceparent and grpc-trace-bin in response header

## Issue reference

#1513 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
My jokes are better...

**Comment by shalabhms** [comment]
As discussed with @youngbupark  , we will be using 2nd approach, 
PR https://github.com/dapr/dapr/pull/1638/files

Closing this PR.

**Pull request closed without merging**
