### PR TITLE
Add json util to unmarshal numbers into int/float

### PR DESCRIPTION
**Pull request by hueifeng**
# Description

This PR adds  json file to pkg/json. Consider that there is a lot of code to change, I will submit it in batches to this PR. In order to ensure code specification, please Review these codes first.

 cc @yaron2 @artursouza 

## Issue reference

Please reference the issue this PR will close: #3837 #4026  

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by daixiang0** [comment]
Could you share the background about these changes?

**Comment by hueifeng** [comment]
@daixiang0 I added json pkg to provide several util methods via `Encoding / json. In the runtime.go file, the reference to jsoniter "github.com/json-iterator/go" is replace with json pkg, this modification solved the issue of Unmarshal numbers into int/float.

**Comment by daixiang0** [comment]
Based on what you said, seems "github.com/json-iterator/go" cannot support unmarshal numbers into int/float, so is it a bug in "github.com/json-iterator/go"?

Codes looks good, but if there is a library can do the same things, I prefer to use it rather than implement by myself.

**Comment by hueifeng** [comment]
>Based on what you said, seems "github.com/json-iterator/go" cannot support unmarshal numbers into int/float, so is it a bug in "github.com/json-iterator/go"?

Serialization is used in runtime.go, but when it encounters 64bit it automatically identifies Number as float64. In this [Issue](https://github.com/dapr/dapr/issuss/3837), you can see the problem related to github.com/json-iterator/go`.

**Comment by yaron2** [comment]
@hueifeng thanks, can you please replace all occurrences of jsoniter? we want to remove this dependency completely.

@daixiang0 jsoniter maintainers stated this package optimizes for efficiency over stability and precision. As Dapr deals with user data, we cannot afford to sacrifice serialization accuracy. Also, it seems like since Go 1.14 the `encoding/json` package is more performant.

**Comment by daixiang0** [comment]
@yaron2 thanks for details.

**Comment by yaron2** [comment]
ping @hueifeng

**Comment by hueifeng** [comment]
@yaron2 @daixiang0 Can I change `map[interface{}]interface{}` to `map[string]interface{}` ？Because the key of the map defined by encoding/json cannot be interface{}. https://github.com/dapr/dapr/blob/57f82682498d2e58558a0bcd0b2ae94175c45a42/pkg/http/api.go#L1263

**Comment by yaron2** [comment]
> @yaron2 @daixiang0 Can I change `map[interface{}]interface{}` to `map[string]interface{}` ？Because the key of the map defined by encoding/json cannot be interface{}.
> 
> https://github.com/dapr/dapr/blob/57f82682498d2e58558a0bcd0b2ae94175c45a42/pkg/http/api.go#L1263
> 
> image

This shoule be ok.

**Comment by hueifeng** [comment]
@daixiang0 Now I don't know how to fix this DCO. What should I do?

**Comment by daixiang0** [comment]
Please check https://github.com/dapr/dapr/pull/4069/checks?check_run_id=4710984566

**Comment by hueifeng** [comment]
> Please check https://github.com/dapr/dapr/pull/4069/checks?check_run_id=4710984566

I followed this step in the local branch, but it didn't work.

image

image

**Comment by daixiang0** [comment]
You have conflicts when `git merge`, so please fix it first, Google will tell you how to fix it.

**Comment by yaron2** [comment]
> > Please check https://github.com/dapr/dapr/pull/4069/checks?check_run_id=4710984566
> 
> I followed this step in the local branch, but it didn't work.
> 
> image
> 
> image

If you're having trouble, feel free to close the PR and open a new one.

**Pull request closed without merging**
