### PR TITLE
Fix Membership Unit Test Flakiness

### PR DESCRIPTION
**Pull request by cicoyle**
Update membership test to fix unit test flakiness. Should be no diff other than indentation and wrapping the `membercount` call in the `require.EventuallyWithT`

### CODE REVIEW

**Review by yaron2 — APPROVED** [review]

**Comment by elena-kolevska** [comment]
Thanks for looking into this @cicoyle 🙏  
We already have a PR that fixes the membership test flakiness here: 
https://github.com/dapr/dapr/pull/7790, but it's blocked by the failing e2e pubsub tests, most probably related to the kafka components-contrib changes. 
Since I see this one is not passing all tests, I can either split 7790 into two PRs, or we can wait a bit until we fix the e2e.

**Comment by JoshVanL** [comment]
@elena-kolevska I think it is best for use to split out the fixes to CI on master, and merging in 1.13 branch.

**Comment by elena-kolevska** [comment]
Of course. I'll push to this branch.

**Comment by elena-kolevska** [comment]
@cicoyle I didn't have permission to push directly, so I opened this PR https://github.com/cicoyle/dapr/pull/70.

**Comment by cicoyle** [comment]
Thanks @elena-kolevska - I didn't see this fix in your PR, thanks for pulling it out. I squash merged your PR into my branch. The other test failures I'm working to fix in a [diff PR here](https://github.com/dapr/dapr/pull/7818). Looks like the only test failure in that PR is due to this Membership unit test, so looks like I fixed the rest of them 🤞🏻

**Review by elena-kolevska — APPROVED** [review]

**Review by JoshVanL — APPROVED** [review]

**Review by mikeee — APPROVED** [review]
lgtm

**Pull request merged**
