### PR TITLE
Fix transaction del API for null etag.

### PR DESCRIPTION
**Pull request by artursouza**
# Description

Fix transaction del API for null etag.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2126 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by tcnghia — APPROVED** [review]

**Comment by mukundansundar** [comment]
previous e2e tests were cancelled. latest one did not start correctly with failing to install Helm. Can try and run the test again after sometime.

**Review by youngbupark — APPROVED** [review]

**Review by youngbupark — CHANGES_REQUESTED** [review]
DO NOT MERGE this. I am fixing conflicts.

**Comment by youngbupark** [comment]
no need to merge by #2132

**Pull request closed without merging**
