### PR TITLE
Fix a concurrent bug and a typo about state api

### PR DESCRIPTION
**Pull request by seeflood**
# Description

1. fix a race condition in grpc/api.go, see https://github.com/dapr/dapr/issues/3323

2. fix a typo.Change 'getSecretStore' to 'getStateStore' in pkg/components/state/registry.go

## Issue reference
#3323

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by beiwei30 — APPROVED** [review]
LGTM.

**Review by artursouza — APPROVED** [review]

**Review by mukundansundar — APPROVED** [review]

**Comment by seeflood** [comment]
I'm sorry I don't understand why the ci/cd failed?

**Comment by yaron2** [comment]
> I'm sorry I don't understand why the ci/cd failed?

I ran the build again.
@seeflood please notice that you have the Dapr GitHub Actions pipeline running in your fork and it causes an email spam about the failed runs. please disable it :)

**Comment by seeflood** [comment]
> > I'm sorry I don't understand why the ci/cd failed?
> 
> I ran the build again.
> @seeflood please notice that you have the Dapr GitHub Actions pipeline running in your fork and it causes an email spam about the failed runs. please disable it :)
> 
> /cc @artursouza

@yaron2  Thanks for your explanation,I disabled all the actions in my forked repo

**Pull request merged**
