### PR TITLE
Correct the title of the 'decision records' file 

### PR DESCRIPTION
**Pull request by helpta**
Correct the title of the 'decision records' file (API-011: State Store APIs Parity)

### CODE REVIEW

**Comment by helpta** [comment]
@shalabhms

**Comment by daixiang0** [comment]
@helpta thanks for your contribution! Please fix DCO then we can make it land.

**Comment by helpta** [comment]
> @helpta thanks for your contribution! Please fix DCO then we can make it land.

yeah,! It's done!

**Review by daixiang0 — APPROVED** [review]
LGTM

**Pull request merged**
