### PR TITLE
optimize(tests): format log to add newline

### PR DESCRIPTION
**Pull request by 1046102779**
Signed-off-by: 1046102779 <seachen@tencent.com>

# Description

ImageID:localhost:5000/dapr/daprd@sha256:b49e9340018007d567ac9df91e839397a3d555e385a306d2d49d1576e62af2fd ContainerID:containerd://56f2476bf37ba40a01fbbd470e19d312704b73b71de3c1add1e0b94b7c291def Started:0xc0002c9f35}]] error: timed out waiting for the condition2022/10/11 13:04:46 Running teardown...

**After format:**

ImageID:localhost:5000/dapr/daprd@sha256:b49e9340018007d567ac9df91e839397a3d555e385a306d2d49d1576e62af2fd ContainerID:containerd://56f2476bf37ba40a01fbbd470e19d312704b73b71de3c1add1e0b94b7c291def Started:0xc0002c9f35}]] error: timed out waiting for the condition
2022/10/11 13:04:46 Running teardown...

### CODE REVIEW

**Comment by daixiang0** [comment]
Please fix lint.

**Comment by 1046102779** [comment]
> Please fix lint.

Fixed.

**Review by ItalyPaleAle — CHANGES_REQUESTED** [review]
Thanks for this contribution! However, I don't think we need it. Our logging library does add newlines even when using `log.Printf`

**Review by daixiang0 — DISMISSED** [review]

**Comment by daixiang0** [comment]
@ItalyPaleAle From the log, it does not have a new linebreak. Is it related to screen size? @1046102779 please confirm it.

**Comment by ItalyPaleAle** [comment]
@daixiang0 I have never seen our logs _not_ having a line break at the end. We log in two ways:

- When formatting as JSON, the trailing line break doesn't matter as it's removed
- When formatting as text, the formatter adds extra info such as log level, time, etc, and the line break is added automatically

@1046102779 are you doing something "unusual" with your app and the way you use Dapr logs?

**Comment by 1046102779** [comment]
> @daixiang0 I have never seen our logs _not_ having a line break at the end. We log in two ways:
> 
> * When formatting as JSON, the trailing line break doesn't matter as it's removed
> * When formatting as text, the formatter adds extra info such as log level, time, etc, and the line break is added automatically
> 
> @1046102779 are you doing something "unusual" with your app and the way you use Dapr logs?

I took a closer look this problem and I did see some non-wrapping in the e2e test, which I thought was caused by `log.Printf`

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
> I took a closer look this problem and I did see some non-wrapping in the e2e test, which I thought was caused by 

Oh I'm very sorry. I missed the part that this was in the E2E test apps. Then yes, this makes a lot of sense :) LGTM!

**Comment by daixiang0** [comment]
@1046102779 please fix conflicts then we can make it land.

**Comment by ItalyPaleAle** [comment]
@1046102779 please fix DCO

**Comment by 1046102779** [comment]
> @1046102779 please fix DCO

Fixed.

**Comment by 1046102779** [comment]
> @1046102779 please fix conflicts then we can make it land.

Fixed.

**Review by daixiang0 — DISMISSED** [review]

**Comment by daixiang0** [comment]
Need rebase.

**Comment by artursouza** [comment]
Can this come from a personal fork? We will never be able to merge this PR because maintainers don't have permission to update it.

**Pull request closed without merging**
