### PR TITLE
hotfix: operator component crd resouces update all dapr runtime

### PR DESCRIPTION
**Pull request by 1046102779**
all pods  in running state：
wecom-temp-710f5ce2aed971ccbc57386b528c047a

when i deployed a new privateassist service, and binding.mysql,  and mysql configuration has a unavaliable network problem. 

And I did not write the scope in binding.msyql component, so the scope is empty, it should cause all pod crash, but actually the result is as bellow:

wecom-temp-0c5b9e092541fe3a4a25985f3622dd5e

The really reason that is dapr-system/dapr-operator service only notify  a daprd runtime ， the daprd runtime is to preempt successful updateChan resources. 

So the solution is dapr-system/dapr-operator will notify all daprd runtime

### CODE REVIEW

**Comment by 1046102779** [comment]
@artursouza please review the PR.  thanks.

**Comment by 1046102779** [comment]
> @artursouza please review the PR. thanks.

tomorrow i check failed e2e tests

**Comment by 1046102779** [comment]
@artursouza can you help me to get k8s logs ?

kubectl -n dapr-tests get events --sort-by='{.lastTimestamp}'

image

**Comment by 1046102779** [comment]
@artursouza please review the pr. thks.

**Review by artursouza — APPROVED** [review]

**Comment by 1046102779** [comment]
> Is there a way to turn this behaviour in a feature. Or can we turn this one with any config?
> With last version we were trating this behaviour as a good thing, since when we try to apply a missconfiguration the application wouldn't stop and it wouldn't be applied.

you maybe use params `scopes` to control scope of action.

image

**Comment by 1046102779** [comment]
> > > Is there a way to turn this behaviour in a feature. Or can we turn this one with any config?
> > > With last version we were trating this behaviour as a good thing, since when we try to apply a missconfiguration the application wouldn't stop and it wouldn't be applied.
> > 
> > 
> > you may use params `scopes` to control scope of action.
> > image
> 
> Thanks, But we are using scopes for our applications. The idea was if someone tries to apply one yaml wrongly configured (like wrong host), the 2/2 running pods would't restart ... would bring only the 1/2 crashingloopoff , without stopping the previous App.

How do you think the following measures ?

```shell
When a daprd sidecar dynamicly inits  a component failed, it modify `readyStatus` to false for healthy flag?  

k8s liveness httpGet : /v1.0/healthz
```

**Pull request merged**
