### PR TITLE
Register Huawei OBS bindings component into the Dapr main

### PR DESCRIPTION
**Pull request by jasonlica**
Signed-off-by: jasonlica <jasonli@huawei.com>

# Description

Register new Dapr bindings component for the Huawei OBS.

## Issue reference

Components contrib proposal/PR: https://github.com/dapr/components-contrib/issues/1718

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#https://github.com/dapr/docs/issues/2436
* [x] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#https://github.com/dapr/docs/issues/2436
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by artursouza — CHANGES_REQUESTED** [review]
This change is flagging FOSSA on license.

**Review by artursouza — APPROVED** [review]
LGTM. Needs to resolve conflict.

**Comment by yaron2** [comment]
cc @jasonlica

**Comment by jasonlica** [comment]
@artursouza / @yaron2 I resolved conflicts but couldn't commit the changes. Not sure whether I am following the correct steps.
dapr-main-pr

**Comment by yaron2** [comment]
> @artursouza / @yaron2 I resolved conflicts but couldn't commit the changes. Not sure whether I am following the correct steps. dapr-main-pr

I'll resolve this soon.

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
Thanks @jasonlica!

**Comment by jasonlica** [comment]
> Thanks @jasonlica!

@yaron2/ @artursouza  thanks for the review and approval. Thanks to the community!

**Pull request merged**
