### PR TITLE
WIP: Revert Redis JSON Update

### PR DESCRIPTION
**Pull request by halspang**
# Description
This reverts commit 551722f533afa5dfee97482fe3e63d8ff6233d50.

Signed-off-by: Hal Spang <halspang@microsoft.com>

## Issue reference

Please reference the issue this PR will close: Endgame

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
It'd be great for both approver/maintainer and community visibility to get at least a short sentence explaining what problem this PR fixes.

**Comment by halspang** [comment]
> It'd be great for both approver/maintainer and community visibility to get at least a short sentence explaining what problem this PR fixes.

We're experimenting with different PRs that might have affected the perf tests. I can't run them directly right now (working on a fix). I was going to add more info in once I had something more substantial here :)

**Comment by yaron2** [comment]
> > It'd be great for both approver/maintainer and community visibility to get at least a short sentence explaining what problem this PR fixes.
> 
> We're experimenting with different PRs that might have affected the perf tests. I can't run them directly right now (working on a fix). I was going to add more info in once I had something more substantial here :)

Do the actor reminders in the performance test target Redis?

**Comment by halspang** [comment]
@yaron2 - Seems to be. Do we have a strong reason to think it wouldn't/shouldn't be? People keep seeming surprised.

From the container logs:
```
➜  ~/Workspace/dapr git:(1.7_investigation) 
$ for i in $(grep -roE 'detected actor state store: [^"]+' ~/Downloads/perf_container_logs | awk '{ print $5 }' | uniq); do
grep -r "name: $i" ~/Downloads/perf_container_logs
done
/Users/hal/Downloads/perf_container_logs/tester-6cccf9df75-bncqg.daprd.log:time="2022-03-05T18:17:26.146149832Z" level=info msg="component loaded. name: statestore, type: state.redis/v1" app_id=tester instance=tester-6cccf9df75-bncqg scope=dapr.runtime type=log ver=edge
```

**Comment by yaron2** [comment]
> @yaron2 - Seems to be. Do we have a strong reason to think it wouldn't/shouldn't be? People keep seeming surprised.
> 
> From the container logs:
> 
> ```
> ➜  ~/Workspace/dapr git:(1.7_investigation) 
> $ for i in $(grep -roE 'detected actor state store: [^"]+' ~/Downloads/perf_container_logs | awk '{ print $5 }' | uniq); do
> grep -r "name: $i" ~/Downloads/perf_container_logs
> done
> /Users/hal/Downloads/perf_container_logs/tester-6cccf9df75-bncqg.daprd.log:time="2022-03-05T18:17:26.146149832Z" level=info msg="component loaded. name: statestore, type: state.redis/v1" app_id=tester instance=tester-6cccf9df75-bncqg scope=dapr.runtime type=log ver=edge
> ```

I remember someone saying it was CosmosDB at some point. Good to know :)

**Comment by artursouza** [comment]
> > @yaron2 - Seems to be. Do we have a strong reason to think it wouldn't/shouldn't be? People keep seeming surprised.
> > From the container logs:
> > ```
> > ➜  ~/Workspace/dapr git:(1.7_investigation) 
> > $ for i in $(grep -roE 'detected actor state store: [^"]+' ~/Downloads/perf_container_logs | awk '{ print $5 }' | uniq); do
> > grep -r "name: $i" ~/Downloads/perf_container_logs
> > done
> > /Users/hal/Downloads/perf_container_logs/tester-6cccf9df75-bncqg.daprd.log:time="2022-03-05T18:17:26.146149832Z" level=info msg="component loaded. name: statestore, type: state.redis/v1" app_id=tester instance=tester-6cccf9df75-bncqg scope=dapr.runtime type=log ver=edge
> > ```
> 
> I remember someone saying it was CosmosDB at some point. Good to know :)

I said that but I mixed it up with the E2E tests on AKS. We don't use Azure services for perf, apart from AKS.

**Comment by mukundansundar** [comment]
close in lieu of #4490

**Pull request closed without merging**
