### PR TITLE
fix for config subscribe all

### PR DESCRIPTION
**Pull request by pravinpushkar**
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

# Description

Removed fetch all key logic when `subscribe all` is needed.

## Issue reference

Please reference the issue this PR will close: #5183 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by artursouza — CHANGES_REQUESTED** [review]
We have cherry-picked this into the release-1.9 - in the meantime, can this have an e2e test to reproduce the issue?

**Comment by pravinpushkar** [comment]
> We have cherry-picked this into the release-1.9 - in the meantime, can this have an e2e test to reproduce the issue?

Thanks for cherry-picking this to 1.9 rel. 

Regarding E2E, ATM we do not have E2E for any of the configuration apis. 
IMO we should create a different issue to add E2E for all config apis and we can cover this scenario as well there
Let me know your thoughts, I would create another issue and PR.

**Comment by artursouza** [comment]
> > We have cherry-picked this into the release-1.9 - in the meantime, can this have an e2e test to reproduce the issue?
> 
> Thanks for cherry-picking this to 1.9 rel.
> 
> Regarding E2E, ATM we do not have E2E for any of the configuration apis. IMO we should create a different issue to add E2E for all config apis and we can cover this scenario as well there. Let me know your thoughts, I can create another issue and PR and we can merge this as is to avoid conflict.

Please, track that in a separate issue. it would be great to have it on 1.10

**Comment by artursouza** [comment]
Zero delta now. Closing PR.

**Pull request closed without merging**
