### PR TITLE
add check-proto-version to verify if all the versions of related proto generation tools are expectd

### PR DESCRIPTION
**Pull request by skyao**
# Description

Add check-proto-version to verify if all the versions of related proto generation tools are expectd, this checking will be executed in target gen-proto: if the version is not correct, the build will exist with error notification.

the new added target check-proto-version will check these three version: 

1. protoc: expected is 3.14.0
2. protoc-gen-go: expected is v1.25.0
3. protoc-gen-go-grpc: expected is 1.1.0

As command shows:

```
% protoc --version
libprotoc 3.14.0
% protoc-gen-go --version
protoc-gen-go v1.25.0
% protoc-gen-go-grpc --version
protoc-gen-go-grpc 1.1.0
```

## Issue reference

See discussion in PR:

https://github.com/dapr/dapr/pull/3037

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by skyao** [comment]
One special thing is that protoc-gen-go use stderr (NOT stdout) to output version information, so I have to redirect the stderr to stdout to catch the output version:

```
@test "$(shell protoc-gen-go --version 2>&1)" = "protoc-gen-go v1.25.0" \
```

**Comment by yaron2** [comment]
@skyao look at the build errors

**Comment by skyao** [comment]
I added a checking in the build process which is similar to "go mod tidy check diff", as @artursouza suggested.

```
      - name: Run go mod tidy check diff
        if: matrix.target_arch == 'amd64' && matrix.target_os == 'linux'
        run: make modtidy check-diff
      - name: Run gen-proto check diff
        if: matrix.target_arch == 'amd64' && matrix.target_os == 'linux'
        run: make gen-proto check-proto-diff
```

But now see in the build there is no command for gen-proto/protoc-gen-go-grpc/protoc:

```
Run make gen-proto check-proto-diff
make: protoc: Command not found
make: protoc-gen-go-grpc: Command not found
/bin/sh: 1: protoc-gen-go: not found
please use protoc 3.14.0 to generate proto, see https://github.com/dapr/dapr/blob/master/dapr/README.md#proto-client-generation
make: *** [Makefile:287: check-proto-version] Error 1
Error: Process completed with exit code 2.
```

So should I remove this checking in build process?

**Comment by artursouza** [comment]
> I added a checking in the build process which is similar to "go mod tidy check diff", as @artursouza suggested.
> 
> ```
>       - name: Run go mod tidy check diff
>         if: matrix.target_arch == 'amd64' && matrix.target_os == 'linux'
>         run: make modtidy check-diff
>       - name: Run gen-proto check diff
>         if: matrix.target_arch == 'amd64' && matrix.target_os == 'linux'
>         run: make gen-proto check-proto-diff
> ```
> 
> But now seems in the build evn there are no such commands( gen-proto/protoc-gen-go-grpc/protoc):
> 
> ```
> Run make gen-proto check-proto-diff
> make: protoc: Command not found
> make: protoc-gen-go-grpc: Command not found
> /bin/sh: 1: protoc-gen-go: not found
> please use protoc 3.14.0 to generate proto, see https://github.com/dapr/dapr/blob/master/dapr/README.md#proto-client-generation
> make: *** [Makefile:287: check-proto-version] Error 1
> Error: Process completed with exit code 2.
> ```
> 
> So should I remove this checking in build process?


The required binaries need to be installed upfront. There should be new steps installing those.

**Comment by artursouza** [comment]
@skyao  Please, look at the broken build for this PR.

**Comment by yaron2** [comment]
ping @skyao

**Comment by skyao** [comment]
> The required binaries need to be installed upfront. There should be new steps installing those.

I don't know how to add the steps to install required binaries in the build env.

**Comment by artursouza** [comment]
> > The required binaries need to be installed upfront. There should be new steps installing those.
> 
> I don't know how to add the steps to install required binaries in the build env.


Gh actions is basically a structured shell script. You can run shell script that downloads and copies files just like you would on your Linux desktop.

**Comment by skyao** [comment]
> > > The required binaries need to be installed upfront. There should be new steps installing those.
> > 
> > 
> > I don't know how to add the steps to install required binaries in the build env.
> 
> Gh actions is basically a structured shell script. You can run shell script that downloads and copies files just like you would on your Linux desktop.

Done, add commands to download  and install protoc.  Please help to review.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
