### PR TITLE
Fixed issue with tracing not working in HTTP service invocation

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
This PR fixes a regression reported by @artursouza that was caught thanks the E2E tests in the Java SDK repos.

The regression was introduced by #5316 . When we converted the HTTP middlewares from fasthttp to net/http, we used two "adapters" to convert between the frameworks. As part of that, user values set in the HTTP context were not passed correctly from the router to the tracing middleware, and they were lost in the conversion. These user values are used by the router to store the values from the URLs (e.g. the method name and target ID app).

This PR fixes the issue by forking the [fasthttpadaptor](https://github.com/valyala/fasthttp/tree/master/fasthttpadaptor) and adding an extension to preserve changes to user values across the adaptors. I opted for a hard fork given that the upstream package seems to be mostly stable and this change is pretty much Dapr-specific. It's also meant to be temporary, until #4979 is addressed.

### CODE REVIEW

**Comment by yaron2** [comment]
I just verified that HTTP tracing is working in Dapr 1.9.4, I can see traces with method names and app_id. Can you explain in more detail which scenarios are broken?

**Comment by yaron2** [comment]
Does this PR contain tests to capture this regression?

**Comment by ItalyPaleAle** [comment]
No. But @artursouza told me he wanted to create an E2E test. I'll let him chime in if he's still planning to do that, otherwise I can do (even on a separate PR).

It should be an E2E and not unit test because it'd be very hard to write this as unit test AND this situation is hopefully temporary (see #4979)

**Comment by artursouza** [comment]
> 

I am writing E2E test to catch this bug. It is taking some time because we will need to install zipkin and use zipkin's API directly for the first time in our tests. This PR can wait for the E2E tests to be completed from my side.

**Review by artursouza — APPROVED** [review]
I will follow up with the E2E test myself. Merging for the sake of having higher quality nightly builds.

**Pull request merged**
