### PR TITLE
pref:  unify the YAML format of CRD resources

### PR DESCRIPTION
**Pull request by ZhangSetSail**
# Description

### CODE REVIEW

**Comment by ZhangSetSail** [comment]
The crd resources are not unified, and it is very troublesome to process through the helm API

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by mukundansundar** [comment]
@ZhangSetSail can you please describe why this change is needed?

**Comment by ZhangSetSail** [comment]
You can restore it with the following command
`helm repo add dapr https://dapr.github.io/helm-charts/ && helm show all dapr/dapr`
You can see that there is a problem with the yaml display of crd

**Comment by ZhangSetSail** [comment]
I can handle it more easily by unifying the yaml format of crd

**Pull request merged**
