### PR TITLE
Fixing version skew e2e tests

### PR DESCRIPTION
**Pull request by shivamkm07**
# Description

Dapr sidecar version-skew-e2e tests are failing currently. An example run: https://github.com/dapr/dapr/actions/runs/7188604424

The failure is because of breaking changes in http metrics and deprecation of `RenameReminder` API. The PR adds patches to modify the tests accordingly.

## Issue reference

Please reference the issue this PR will close: #7241 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by JoshVanL — CHANGES_REQUESTED** [review]
@shivamkm07 The version skew tests are intended to run against the latest release's e2e test suite by design. Running against the latest release ensures that version skew has conformance from a common feature and API support base. Running the e2e tests from master will not work as it includes tests for features which do not exist in the latest release.

The version skew tests are currently failing due to breaking changes made as described https://github.com/dapr/dapr/issues/7295 https://github.com/dapr/dapr/issues/7241

**Comment by shivamkm07** [comment]
`/test-version-skew` is not taking the updated yaml file and so failing. I ran the same changes in my fork and it is passing now: https://github.com/shivamkm07/dapr/actions/runs/7262120437/job/19784641315

P.S. The overall action failure is because of not `GITHUB_TOKEN` set in my fork, Ignore that. `Run Tests` step is passing.

**Review by JoshVanL — APPROVED** [review]

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
