### PR TITLE
Remove exporter components registration

### PR DESCRIPTION
**Pull request by tcnghia**
# Description

Remove exporter components registration, to prepare to delete the code in component-contribs.

## Issue reference

Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/2522

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation
* [x] Specification has been updated 
* [x] Provided sample for the feature

### CODE REVIEW

**Comment by tcnghia** [comment]
@yaron2 @msfussell now that we moved the tracing setup into Dapr core, we can remove the exporter component registration. Please do let me know if you want to keep this around longer to allow users some grace period to move, in which case we can hold this PR for a while.

**Comment by msfussell** [comment]
We should the remove component registration for the upcoming RC2 release. RC1 was the grace period for this. Breaking sooner is the best approach. Please make sure there is a good description in the release notes for how to move to the new settings.

**Comment by tcnghia** [comment]
> We should the remove component registration for the upcoming RC2 release. RC1 was the grace period for this. Breaking sooner is the best approach. Please make sure there is a good description in the release notes for how to move to the new settings.

Thanks @msfussell 

@youngbupark can you please help review/approve? thanks

**Review by youngbupark — APPROVED** [review]
Will you remove the exporters in component-contrib later?

**Comment by tcnghia** [comment]
> Will you remove the exporters in component-contrib later?

Yes, there is still a unit test that uses the string_exporter, so I will follow up with inlining that before removing.

**Pull request merged**
