### PR TITLE
use soft anti-affinity rules

### PR DESCRIPTION
**Pull request by andrey-dubnik**
#3788

### CODE REVIEW

**Comment by andrey-dubnik** [comment]
There seem to be a glitch in the testing pipeline....

**Review by artursouza — APPROVED** [review]

**Comment by Taction** [comment]
@andrey-dubnik Thanks for this PR! Would you please fix DCO issue?

**Comment by andrey-dubnik** [comment]
> @andrey-dubnik Thanks for this PR! Would you please fix DCO issue? You can refer to [here](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) about how to fix it.

@Taction I can see the commit DCO complains about is signed... do you see any possible cause why DCO complains about it?

**Comment by yaron2** [comment]
> 

See here: https://docs.dapr.io/contributing/contributing-overview/#i-didnt-sign-my-commit-now-what

**Comment by Taction** [comment]
@andrey-dubnik You do have pushed a signed commit with hash `cda2ae0`, but your first commit with hash `2e30320` is still there with unsigned status. The expected behaviour should be to replace the first commit rather than append a new commit.  
Besides, if it is too confusing for you to solve this, feel free to open another pr and copy your changes to that.

**Comment by andrey-dubnik** [comment]
By the looks of it the PR does not actually have all the necessary changes, I will create a new one

**Pull request closed without merging**
