### PR TITLE
Fix actor_state test

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Includes the Bicep fix from #6172 and some additional fixes

### CODE REVIEW

**Comment by mukundansundar** [comment]
the same error seems to be happening.

**Comment by ItalyPaleAle** [comment]
Still not working :( Will debug more tomorrow

**Comment by ItalyPaleAle** [comment]
We're almost there. Looks like one more issue is that the Cosmos DB collection is still deployed without support for TTLs. Here's what it looks like in the Portal:
image

**Comment by ItalyPaleAle** [comment]
Looks like everything is working now!! 🙌

In the first 2 tests above, I updated the CosmosDB used by Linux but not Windows. In the 3rd test Windows has been updated too.

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
