### PR TITLE
feat: Use pod anti-affinity for spreading across node

### LINKED ISSUE #3147: Helm - Spread instances across zones in Kubernetes cluster for high availability
## In what area(s)?

/area runtime
/area operator
/area placement
> /area docs
> /area test-and-release

## Describe the feature
Spread instances across zones in the Kubernetes cluster to not all be scheduled on the same failure zone.

This can be done by using [pod anti-affinity](https://www.danielstechblog.io/increase-your-application-availability-with-pod-anti-affinity-settings-in-azure-kubernetes-service/) or [pod topology spread constraints](https://www.danielstechblog.io/distribute-your-application-across-different-availability-zones-in-aks-using-pod-topology-spread-constraints/) (Kubernetes 1.19+).

This could potentially only be enabled when running in HA is enabled.

## Release Note

RELEASE NOTE: **ADD:** Spread Dapr instances across zones in Kubernetes cluster for high-availability

### PR DESCRIPTION
**Pull request by tomkerkhove**
# Description

Introduce pod anti-affinity for all components, except dashboard, to spread pods across various zones of nodes. This is to spread them across availability zones of cloud providers such as Azure.

## Issue reference

Closes #3147

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@skyao can you please review this?

**Comment by yaron2** [comment]
> @skyao can you please review this?

Ping @skyao

**Comment by tomkerkhove** [comment]
Let me know what you think @skyao!

**Comment by skyao** [comment]
> Let me know what you think @skyao!

I am learning the background knowledge of pod anti-affinity, just wait me a moment.

One question: since this feature requires k8s 1.19+, if we add this feature into dapr, is it that dapr should requires k8s 1.19+? And if k8s is lower then 1.19, what will happen: ignore or report error ?

**Comment by skyao** [comment]
@yaron2 what the strategy of k8s version in dapr? I have checked the doc of Dapr but not found any information about this.

**Comment by tomkerkhove** [comment]
Initially, I was going to use [pod topology spread constraints](https://www.danielstechblog.io/distribute-your-application-across-different-availability-zones-in-aks-using-pod-topology-spread-constraints/) which is only available as of Kubernetes 1.19 and above but noticed that [pod anti-affinity](https://www.danielstechblog.io/increase-your-application-availability-with-pod-anti-affinity-settings-in-azure-kubernetes-service/) was already used so aligned with that.

There are no new Kubernetes version requirements with this change.

**Comment by yaron2** [comment]
> @yaron2 what the strategy of k8s version in dapr? I have checked the doc of Dapr but not found any information about this.

Min required version is Kubernetes 1.18. We will be documenting that. as @tomkerkhove mentioned, there are no changes to the minimum k8s version with this change.

**Review by skyao — APPROVED** [review]
No special comments. 

Thanks for @tomkerkhove

**Comment by tomkerkhove** [comment]
Thank you for merging!

**Pull request merged**
