### PR TITLE
Pin contrib `v1.11.0-rc.1`

### PR DESCRIPTION
**Pull request by berndverst**
# Description

Pinning latest contrib again.

### CODE REVIEW

**Review by yaron2 — DISMISSED** [review]

**Comment by berndverst** [comment]
@yaron2 @artursouza 

FYI I pushed another update to include:
https://github.com/dapr/components-contrib/pull/2811

**Review by artursouza — DISMISSED** [review]

**Comment by berndverst** [comment]
FYI prior to the PR update this already exceeded the 3 MB diff slightly.

There are only 2 contrib PRs included:
https://github.com/dapr/components-contrib/pull/2825
https://github.com/dapr/components-contrib/pull/2656

And with the latest update we are only adding:
https://github.com/dapr/components-contrib/pull/2811

**Review by artursouza — APPROVED** [review]

**Comment by berndverst** [comment]
Updated this PR again with **latest** contrib which includes the Sarama downgrade to 1.37.2 (same as Hotfix 1.10.6)

**Comment by berndverst** [comment]
Pinned contrib `v1.11.0-rc.1`

**Comment by naah69** [comment]
hello,i want to know when will release v1.11.0

**Comment by naah69** [comment]
> Pinned contrib `v1.11.0-rc.1`

hello,i want to know when will release v1.11.0

**Pull request merged**
