### PR TITLE
Allow setting seccompProfile and drop all capabilities for control plane services

### LINKED ISSUE #6233: Seccomp profile configuration support needs to be added for dapr-dashboard, sentry, sidecar-injector, operator, placement-server
## Description
Hello @mukundansundar , As discussed in today's meeting [FYNDNA]
The Seccomp profile support is available for dapr sidecar in version 1.11
However the same vulnerability has been also reported in following dapr components
- dapr-dashboard
- dapr-sentry
- dapr-sidecar-injector
- dapr-operator
- dapr-placement-server

I am raising this issue as per our discussion
Please let me know if you need any more details on this

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
# Description

With #5945 we added the possibility to configure seccompProfile and drop all capabilities for injected sidecars.

This completes the work by:

- Allowing setting the seccompProfile for control plane services using the Helm option `global.seccompProfile`
- Dropping all capabilities for control plane services by default (unless debug is enabled)

## Issue reference

Fixes #6233

### CODE REVIEW

**Comment by mukundansundar** [comment]
@ItalyPaleAle Can we add a test for enabling the `RuntimeDefault` seccomp profile and run E2E against that configuration?

**Review by mukundansundar — APPROVED** [review]
lgtm

**Comment by mukundansundar** [comment]
> ould validate that Dapr's control plane can run with the RuntimeDefault seccomp profile, which is not what is the purpose of this PR (t

I really think that we need a test that validates that Dapr control plane will work as expected with seccomp profile set to `RuntimeDefault`. 

cc @dapr/maintainers-dapr wdyt?

**Comment by ItalyPaleAle** [comment]
> @ItalyPaleAle Can we add a test for enabling the `RuntimeDefault` seccomp profile and run E2E against that configuration?

@mukundansundar I created an issue #6589 to follow up on this, since it's a different issue than what this PR aims to solve.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
