### PR TITLE
Remove annotations from pluggable components injector feature

### PR DESCRIPTION
**Pull request by mcandeia**
Signed-off-by: Marcos Candeia <marrcooos@gmail.com>

# Description

The pluggable components injector feature will no longer use annotations for defining the container attributes. Instead, a new Pluggable Components CRD will take in place as a entirely replacement for the annotations usage as discussed in the following issue #5668 

## Issue reference

Please reference the issue this PR will close: #5668 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@mcandeia there's a small linter warning failing the build.

**Comment by mcandeia** [comment]
hopefully fixed now @yaron2 lets wait for the tests results

**Comment by mcandeia** [comment]
Some weird infrastructure error happened “ There is not enough capacity to create the namespace. Please contact your Service Bus administrator. For more information visit …”

lets try again

**Comment by mcandeia** [comment]
Pubsub e2e test is failing on AKS. Let's wait to get it passed.

**Comment by mcandeia** [comment]
@yaron2 pubsub test is failing but its unrelated, its failing in master too, since [this](https://github.com/dapr/dapr/pull/5662) got merged. I pinged Deepanshu already.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
