### PR TITLE
chore: fix some function names in comment

### PR DESCRIPTION
**Pull request by davidwoood**
# Description

fix some function names in comment

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] Code compiles correctly
- [ ] Created/updated tests
- [ ] Unit tests passing
- [ ] End-to-end tests passing
- [ ] Extended the documentation / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Specification has been updated / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_
- [ ] Provided sample for the feature / Created issue in the <https://github.com/dapr/docs/> repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by elena-kolevska — APPROVED** [review]
Thanks David!

**Review by cicoyle — APPROVED** [review]

**Comment by cicoyle** [comment]
Hey @davidwoood - thanks for opening this PR, [mind fixing DCO](https://github.com/dapr/dapr/pull/8215/checks?check_run_id=31809566675)?

**Comment by davidwoood** [comment]
> Hey @davidwoood - thanks for opening this PR, [mind fixing DCO](https://github.com/dapr/dapr/pull/8215/checks?check_run_id=31809566675)?

Of course. Modified

**Review by yaron2 — APPROVED** [review]
LGTM. Thanks for your contribution

**Comment by marcduiker** [comment]
@holopin-bot @davidwoood Thank you David!

**Pull request merged**
