### PR TITLE
Revert back - Transactional state store API

### PR DESCRIPTION
**Pull request by youngbupark**
# Description

Transactional state store API

## Issue reference

n/a

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by youngbupark** [comment]
@chinzhiweiblank We revert your contribution in 0.9.0 because SDKs and docs need to be updated. This PR will be merged once we release 0.9.0.

**Comment by chinzhiweiblank** [comment]
> @chinzhiweiblank We reverted your contribution in 0.9.0 because SDKs and docs need to be updated. This PR will be merged once we release 0.9.0.

No problem. Are you planning to merge this for 0.10.0?

**Comment by yaron2** [comment]
> > @chinzhiweiblank We reverted your contribution in 0.9.0 because SDKs and docs need to be updated. This PR will be merged once we release 0.9.0.
> 
> No problem. Are you planning to merge this for 0.10.0?

@youngbupark can we merge back?

**Comment by amanbha** [comment]
> > > @chinzhiweiblank We reverted your contribution in 0.9.0 because SDKs and docs need to be updated. This PR will be merged once we release 0.9.0.
> > 
> > 
> > No problem. Are you planning to merge this for 0.10.0?
> 
> @youngbupark can we merge back?

IMO, before we merge this, we need to handle this https://github.com/dapr/dapr/issues/1736 to surface this api with metadata at transaction level.

**Comment by youngbupark** [comment]
> > > > @chinzhiweiblank We reverted your contribution in 0.9.0 because SDKs and docs need to be updated. This PR will be merged once we release 0.9.0.
> > > 
> > > 
> > > No problem. Are you planning to merge this for 0.10.0?
> > 
> > 
> > @youngbupark can we merge back?
> 
> IMO, before we merge this, we need to handle this #1736 to surface this api with metadata at transaction level.

Right, I will take care of it.

**Comment by youngbupark** [comment]
reopened https://github.com/dapr/dapr/pull/1892

**Pull request closed without merging**
