### PR TITLE
[1.8.1 hotfix] Updated pinned components-contrib

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Also includes release notes.

### CODE REVIEW

**Review by artursouza — APPROVED** [review]

**Comment by yaron2** [comment]
Build's failing.

**Comment by ItalyPaleAle** [comment]
@yaron2 it's a flaky test. can you please re-trigger it?

**Comment by yaron2** [comment]
> @yaron2 it's a flaky test. can you please re-trigger it?

Done.

**Pull request merged**
