### PR TITLE
Pin latest Contrib for CosmosDB fix

### PR DESCRIPTION
**Pull request by berndverst**
Signed-off-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>

# Description

Pin latest Contrib for CosmosDB fix

### CODE REVIEW

**Comment by artursouza** [comment]
This is still not enough to fix the regression.

**Comment by berndverst** [comment]
> This is still not enough to fix the regression.

That makes no sense actually. Very weird. I'll write a conformance test instead to see what's going on.

**Comment by berndverst** [comment]
@artursouza as @ItalyPaleAle the issue is that the test app images are cached, so our code changes were never actually run in this test! Alessandro will purge the cache and rerun.

**Comment by artursouza** [comment]
The test app cache should not matter because the fix is in the sidecar.

**Review by artursouza — DISMISSED** [review]

**Comment by berndverst** [comment]
Didn't pin the right contrib commit earlier. Whoops

**Review by artursouza — APPROVED** [review]

**Pull request merged**
