### PR TITLE
Update controller-tools to 0.15.0

### PR DESCRIPTION
**Pull request by JoshVanL**
Updates k6-operator to `v0.0.14`. Installs `controller-gen` before running k6-operator Makefile targets.

Fixes panic when running controller-tools on Go 1.22

### CODE REVIEW

**Comment by mikeee** [comment]
`k6-operator` is using a legacy version too.  Appears controller-gen 0.14.0 doesn't panic either, additionally removed the azure blob upload step which is causing issues: https://github.com/dapr/dapr/pull/7730/files
Hopefully this run is a bit more green: https://github.com/dapr/dapr/actions/runs/9307003908

**Comment by JoshVanL** [comment]
Thanks @mikeee! Sorry didn't see your PR.. indeed was heading down that rabbit hole :slightly_smiling_face: 
I guess the controller-gen CLI has changed quite a bit since then.

Closing in favor of https://github.com/dapr/dapr/pull/7730

**Comment by mikeee** [comment]
Hopefully not too deep of a rabbit hole - https://github.com/dapr/dapr/actions/runs/9307369325/job/25618709618
Already looking more promising

**Comment by cicoyle** [comment]
are the informer `should_receive_app_events_on_batch_events_in_order` unit tests && `hotreload/operator/informer/subscriptions` int tests flaky?

**Review by cicoyle — APPROVED** [review]
approving assuming the failing tests are just flaky

**Comment by elena-kolevska** [comment]
Yeah, they are, they've been failing sporadically...

**Review by yaron2 — APPROVED** [review]

**Review by mikeee — CHANGES_REQUESTED** [review]
I don't want to be a blocker but I think there may be more to this than just flakiness -
https://github.com/dapr/dapr/actions/runs/9319295117/job/25653751242#step:18:289
Does not look healthy, that's failing with a timeout.

**Pull request merged**
