### PR TITLE
upgrade logrus to v1.4.2

### PR DESCRIPTION
**Pull request by thinkerou**
# Description

as title, closing #693 

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by thinkerou** [comment]
```
 Run make lint25s
##[error]Process completed with exit code 2.
Run make lint
  make lint
  shell: /bin/bash -e {0}
  env:
    GOVER: 1.13.3
    GOOS: darwin
    GOARCH: amd64
    GOPROXY: https://proxy.golang.org
    ARCHIVE_OUTDIR: dist/archives
    GOROOT: /Users/runner/hostedtoolcache/go/1.13.3/x64
    REL_VERSION: edge
golangci-lint run --fix
level=error msg="Running error: context loading failed: no go files to analyze"
make: *** [lint] Error 5
##[error]Process completed with exit code 2.
```

**Comment by yaron2** [comment]
Will check.

**Comment by thinkerou** [comment]
the new error:
```
Run make release to build and archive binaries1s
##[error]Process completed with exit code 2.
Run mkdir -p dist/archives
CGO_ENABLED=0 GOOS=linux GOARCH=arm go build  -ldflags="-X github.com/dapr/dapr/pkg/version.commit=9926c5e -X github.com/dapr/dapr/pkg/version.version=edge -s -w" -o ./dist/linux_arm/release/daprd -mod=vendor ./cmd/daprd/main.go;
##[error]vendor/github.com/dapr/components-contrib/bindings/aws/s3/s3.go:12:2: case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"
make: *** [dist/linux_arm/release/daprd] Error 1
##[error]Makefile:132: recipe for target 'dist/linux_arm/release/daprd' failed
##[error]Process completed with exit code 2.
```
related https://github.com/dapr/components-contrib/pull/82

**Comment by yaron2** [comment]
We need to do this for contrib first.

We removed the vendor dir there, can you open a PR that upgrades to logrus for contrib?

**Comment by thinkerou** [comment]
@yaron2 ok!

**Comment by thinkerou** [comment]
```
# github.com/dapr/dapr/pkg/placement
##[error]pkg/placement/placement.go:60:2: undefined: logrus.Infof
##[error]pkg/placement/placement.go:79:4: undefined: logrus.Infof
##[error]pkg/placement/placement.go:115:4: undefined: logrus.Errorf
##[error]pkg/placement/placement.go:151:4: undefined: logrus.Errorf
##[error]pkg/placement/placement.go:162:4: undefined: logrus.Errorf
##[error]pkg/placement/placement.go:221:3: undefined: logrus.Fatalf
##[error]pkg/placement/placement.go:228:3: undefined: logrus.Fatalf
# github.com/dapr/dapr/pkg/components
##[error]pkg/components/kubernetes_loader.go:70:3: undefined: logrus.Info
##[error]pkg/components/standalone_loader.go:44:5: undefined: logrus.Warnf
##[error]pkg/components/standalone_loader.go:51:5: undefined: logrus.Warnf
```

**Comment by yaron2** [comment]
Closing this as we were forced to merge [this](https://github.com/dapr/dapr/pull/906) PR and make the Sirupsen -> sirupsen changes as part of that PR to make it work.

Thanks @thinkerou, you've been really helpful in driving this change in components-contrib and overall in Dapr. I'll be really glad to see more of your contributions!

**Pull request closed without merging**
