### PR TITLE
Fix dissemination of placement tables

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Fixes (hopefully) #7193

Fixes two issues in the process of disseminating placement tables.

First, dissemination should always have a background context, and not be tied to the context of a specific stream. Otherwise, if the stream is disconnected before the dissemination, all connected hosts may be left in a broken state.

Second, the dissemination process was meant to follow a 3-step process: acquire a lock, disseminate the tables, then release the lock. The current implementation performed all 3 operations in parallel, effectively not waiting for all nodes to be locked before disseminating the tables. This means that the nodes could potentially have inconsistent tables.

### CODE REVIEW

**Comment by artursouza** [comment]
LGTM overall. Waiting on the tests to pass.

**Comment by artursouza** [comment]
I assume this affects 1.12 - if so, can this be merged to 1.12 instead?

**Comment by mukundansundar** [comment]
> I assume this affects 1.12 - if so, can this be merged to 1.12 instead?

@ItalyPaleAle Is this being merged into 1.12 to be released as a hot fix?

**Comment by ItalyPaleAle** [comment]
> @ItalyPaleAle Is this being merged into 1.12 to be released as a hot fix?

This is up to you to decide. Can also be cherry-picked from master as another option.

**Review by daixiang0 — APPROVED** [review]
LGTM

**Pull request merged**
