### PR TITLE
Fix performance tests

### PR DESCRIPTION
**Pull request by johnewart**
# Description

Converted app name magic strings to constants in perf tests and added their identifiers to actor state store configurations so that the performance tests utilizing actors can run. 

Signed-off-by: John Ewart <johnewart@microsoft.com>

/cc @skyao

### CODE REVIEW

**Review by yaron2 — APPROVED** [review]

**Comment by skyao** [comment]
@yaron2 why the statue of this PR is still open, not merged.

**Comment by yaron2** [comment]
> @yaron2 why the statue of this PR is still open, not merged.

It shows as merged.

**Comment by skyao** [comment]
> 

OK, it seems a bug of github. I refreshed the pages for times and it was open all the time. 

And now it is merged.

**Comment by skyao** [comment]
@johnewart  @yaron2  the perf test is not recovered after this PR merged.  We need to follow it: the perf test is NOT work for more than one week now.

**Pull request merged**
