### PR TITLE
Fixing Issue 1101

### PR DESCRIPTION
**Pull request by cmendible**
# Description

Returning 204 for missing state and not 200

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1101

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by yaron2** [comment]
The e2e tests fail because the state test needs to be changed to account for now getting a `204` response instead of `200`.

The logs from the test:
```
--- FAIL: TestStateApp (150.58s)
    --- PASS: TestStateApp/Test_get_save_delete_with_empty_request_response_for_single_app_and_single_hop (1.46s)
    --- FAIL: TestStateApp/Test_save_get_and_delete_a_single_item_for_single_app_and_single_hop (0.14s)
        stateapp_test.go:245: 
            	Error Trace:	stateapp_test.go:245
            	Error:      	Should be true
            	Test:       	TestStateApp/Test_save_get_and_delete_a_single_item_for_single_app_and_single_hop
    --- FAIL: TestStateApp/Test_save_get_and_delete_on_multiple_items_for_single_app_and_single_hop (0.14s)
        stateapp_test.go:245: 
            	Error Trace:	stateapp_test.go:245
            	Error:      	Should be true
            	Test:       	TestStateApp/Test_save_get_and_delete_on_multiple_items_for_single_app_and_single_hop
FAIL
```

**Comment by yaron2** [comment]
cc @cmendible

**Comment by cmendible** [comment]
> ```go
> respondEmpty(c.RequestCtx, 204)
> ```

Roger that. Should I open an issue to make the same change in the Secret API?

**Comment by yaron2** [comment]
Yes, please.

**Pull request merged**
