### PR TITLE
Add release note and update helm chart for 0.11.3

### PR DESCRIPTION
**Pull request by youngbupark**
# Description

Add release note and update helm chart for 0.11.3

## Issue reference

#2309 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by yaron2 — APPROVED** [review]
LGTM

**Review by artursouza — APPROVED** [review]

**Comment by youngbupark** [comment]
the failure is related to aks cluster. I reran it.

**Pull request merged**
