### PR TITLE
Added dependabot config

### PR DESCRIPTION
**Pull request by aditirao7**
# Description

Added configuration file for dependabot updates.

## Issue reference

Please reference the issue this PR will close: #3415.

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by daixiang0** [comment]
I am not sure it is good enough here, better in SDK repo or component-contrib repo.

/cc @artursouza @yaron2

**Comment by aditirao7** [comment]
> I am not sure it is good enough here, better in SDK repo or component-contrib repo.
> 
> /cc @artursouza @yaron2

I don't mind setting up dependabot in those repos as well, should I open issues for it?

**Comment by daixiang0** [comment]
Please do it first to get more feedback.

**Comment by yaron2** [comment]
@artursouza can you please review?

**Review by artursouza — APPROVED** [review]

**Comment by berndverst** [comment]
@aditirao7 **please do not set up dependabot in contrib**

**Pull request merged**
