### PR TITLE
[Release 1.12] Updates contrib to 1.12.0-rc.4

### PR DESCRIPTION
**Pull request by elena-kolevska**
Updates contrib to 1.12.0-rc.4 for fixes to the two GCP components that were failing to authenticate

### CODE REVIEW

**Comment by elena-kolevska** [comment]
@ItalyPaleAle Yeah, I did run it. Does something look off?

**Comment by ItalyPaleAle** [comment]
> @ItalyPaleAle Yeah, I did run it. Does something look off?

Yes, it was not run, or at least not in this commit. You should have a few more files changed. Can you try running it again?

**Comment by artursouza** [comment]
I ran `make modtidy-all` and it shows no diff locally.

**Review by artursouza — APPROVED** [review]

**Review by ItalyPaleAle — APPROVED** [review]
Something must have been off with my env, it showed a diff but the CI passes.

**Pull request merged**
