### PR TITLE
Add Azure SignalR output binding

### PR DESCRIPTION
**Pull request by fbeltrao**
# Description

Add Azure SignalR registration

## Issue reference

dapr/components-contrib#147

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by davidfowl** [comment]
Should we close this one?

**Comment by yaron2** [comment]
> Should we close this one?

No, this will merge the SignalR binding into the Dapr runtime. We'll do it after we cut the release for 0.3.0 tomorrow, as we want this and other components updates to make it to 0.4.0.

**Comment by yaron2** [comment]
Hey @fbeltrao, since we moved on with the version of components-contrib to a newer version than specified here, I suggest you close this PR and open a new one just with the registration code in the runtime.

**Comment by fbeltrao** [comment]
> Hey @fbeltrao, since we moved on with the version of components-contrib to a newer version than specified here, I suggest you close this PR and open a new one just with the registration code in the runtime.

Hi @yaron2, just for me to understand: what would be the drawback of syncing upstream/master on my branch and pushing the changes?

Do you want me to remove the tests I added?

**Comment by yaron2** [comment]
If you can resolve the conflicts peacefully, that works too :)

**Pull request merged**
