### PR TITLE
K8S debug support

### PR DESCRIPTION
**Pull request by beiwei30**
# Description

Debug support in K8S for dapr_operator, dapr_placement, dapr_sentry and dapr_sidecar_injector.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #3007

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#1380

### CODE REVIEW

**Comment by yaron2** [comment]
This also neds a corresponding docs update to explain how to Debug the sidecars on k8s.

**Comment by beiwei30** [comment]
> This also neds a corresponding docs update to explain how to Debug the sidecars on k8s.

will do

**Comment by beiwei30** [comment]
> This also neds a corresponding docs update to explain how to Debug the sidecars on k8s.

@yaron2, pls. check.

**Comment by beiwei30** [comment]
I also revised the doc (https://github.com/dapr/docs/pull/1381) according to the review comments, pls. check.

**Comment by AaronCrawfis** [comment]
Docs are approved. Waiting on this PR

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
Thanks @beiwei30!

**Pull request merged**
