### PR TITLE
gRPC invoke: Do not return error if message is nil

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Should fix https://github.com/dapr/java-sdk/pull/822

### CODE REVIEW

**Review by yaron2 — CHANGES_REQUESTED** [review]
Please remove the added certs.

**Comment by artursouza** [comment]
I have verified that this fixed the regression identified in ITs in Java SDK.

**Comment by yaron2** [comment]
Tests are falling (e2e).

**Comment by artursouza** [comment]
So, there is something else then. I wonder if we just need to change the IT for Java SDK to assert for a different error code now.

**Comment by ItalyPaleAle** [comment]
I am not surprised this broke some E2E tests since it did change the behavior.

Let me know what you prefer. The previous code was returning "Unknown" and although "internal" isn't necessarily better, I am not sure if unknown is good either.

Otherwise, I will look into fixing the tests for this tomorrow, if quick, or Monday :)

**Comment by ItalyPaleAle** [comment]
@artursouza 

> Right now, the HTTP API returns UNKNOWN error code too.

What do you mean? Are you talking about gRPC invoke to HTTP endpoint?

**Comment by ItalyPaleAle** [comment]
After discussing with Artur, we're closing this as the tests will be updated instead

**Pull request closed without merging**
