### PR TITLE
Optimize overriding reminder by reducing one state store operation

### LINKED ISSUE #2985: Optimize overriding reminder
## In what area(s)?

> /area actors

## Describe the feature

Optimize overriding reminder by reduce one state store operation.

Current implementation(v1.0.x) of overriding a reminder will delete the reminder firstly which includes a state store set operation, then update the reminder which also includes a state store set operation. The first state store set operation can be reduced.

Related codes:
>https://github.com/dapr/dapr/blob/3b38d1301fb26219e1c23a16cd6fca813610ad28/pkg/actors/actors.go#L765
>https://github.com/dapr/dapr/blob/3b38d1301fb26219e1c23a16cd6fca813610ad28/pkg/actors/actors.go#L771
>https://github.com/dapr/dapr/blob/3b38d1301fb26219e1c23a16cd6fca813610ad28/pkg/actors/actors.go#L1003

## Release Note

RELEASE NOTE: **Update** Overriding reminder by reducing one state store operation.

### PR DESCRIPTION
**Pull request by luckyxiaoqiang**
# Description

Optimize overriding reminder by reducing one state store operation.

## Issue reference

Close #2985 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by daixiang0** [comment]
Please fix CI.

**Comment by luckyxiaoqiang** [comment]
> Please fix CI.

Fixed.

**Review by artursouza — CHANGES_REQUESTED** [review]
Thanks for the contribution but this change will not be applicable anymore with this refactor: https://github.com/dapr/dapr/pull/3297/files

Also, optimizing performance in a single record db is not ideal since we have a case where the database exceeds the max bytes allowed on the record. We should optimize for the partitioned data solution - which will be added by the change above.

**Comment by luckyxiaoqiang** [comment]
> Thanks for the contribution but this change will not be applicable anymore with this refactor: https://github.com/dapr/dapr/pull/3297/files
> 
> Also, optimizing performance in a single record db is not ideal since we have a case where the database exceeds the max bytes allowed on the record. We should optimize for the partitioned data solution - which will be added by the change above.

Got it. Thanks for your reply.

**Pull request closed without merging**
