### PR TITLE
Pin latest contrib

### PR DESCRIPTION
**Pull request by berndverst**
Signed-off-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>

Pin latest contrib

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by berndverst** [comment]
Something odd happening with go.mods.. looking

**Review by ItalyPaleAle — DISMISSED** [review]

**Review by ItalyPaleAle — DISMISSED** [review]

**Pull request closed without merging**
