### PR TITLE
Added reminder to ActiveReminder in case of restart

### PR DESCRIPTION
**Pull request by jigargandhi**
# Description

Added reminder to ActiveReminder in case of restart

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2049

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by jigargandhi** [comment]
@yaron2 please review this; I think its ready for merge

**Review by yaron2 — APPROVED** [review]
lgtm

**Comment by yaron2** [comment]
Thanks for this @jigargandhi

**Comment by youngbupark** [comment]
@jigargandhi Thanks for the contribution. Can you please add the unit-test to cover this scenario?

**Pull request merged**
