### PR TITLE
#2498 Add metadata for stateStore

### PR DESCRIPTION
**Pull request by cvictory**
# Description

Add metadata into GetStateResponse and BulkStateItem.

## Issue reference

https://github.com/dapr/dapr/issues/2498

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
Is this implemented in the HTTP API also?

**Comment by cvictory** [comment]
> Is this implemented in the HTTP API also?

Maybe in some situation, the metadata can't transfer to app.  refer to: https://github.com/dapr/dapr/issues/2518

**Comment by yaron2** [comment]
@cvictory we can now merge this PR, but there are conflicts here. Can you please resolve?

**Comment by cvictory** [comment]
> @cvictory we can now merge this PR, but there are conflicts here. Can you please resolve?

done

**Review by yaron2 — APPROVED** [review]
lgtm

**Pull request merged**
