### PR TITLE
test e2e with dependencies on 0.7

### PR DESCRIPTION
**Pull request by vinayada1**
# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
Shouldn't the e2e deps be for 0.8?

**Comment by vinayada1** [comment]
> Shouldn't the e2e deps be for 0.8?

I am looking into this issue: https://github.com/dapr/dapr/issues/1553 which is reproducible with release-0.7. Had made some changes and wanted to test. I was only trying to run the e2e tests for my validation and it is okay to close this PR

**Pull request closed without merging**
