### PR TITLE
Pin latest contrib

### PR DESCRIPTION
**Pull request by berndverst**
# Description

Pin latest contrib

As a result:

```
go: upgraded cloud.google.com/go v0.110.4 => v0.110.7
go: upgraded cloud.google.com/go/compute v1.20.1 => v1.23.0
go: upgraded cloud.google.com/go/datastore v1.13.0 => v1.14.0
go: upgraded cloud.google.com/go/iam v1.1.0 => v1.1.1
go: upgraded cloud.google.com/go/storage v1.31.0 => v1.32.0
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/azcore v1.7.0 => v1.7.1
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.3.0 => v1.3.1
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/data/azcosmos v0.3.5 => v0.3.6
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azkeys v1.0.0 => v1.0.1
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets v1.0.0 => v1.0.1
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/internal v0.8.0 => v1.0.0
go: upgraded github.com/AzureAD/microsoft-authentication-library-for-go v1.0.0 => v1.1.1
go: upgraded github.com/aliyun/aliyun-log-go-sdk v0.1.50 => v0.1.54
go: upgraded github.com/aliyun/aliyun-oss-go-sdk v2.2.7+incompatible => v2.2.9+incompatible
go: upgraded github.com/aliyun/aliyun-tablestore-go-sdk v1.7.7 => v1.7.10
go: upgraded github.com/aws/aws-sdk-go v1.44.315 => v1.44.333
go: upgraded github.com/camunda/zeebe/clients/go/v8 v8.2.8 => v8.2.12
go: upgraded github.com/choleraehyq/pid v0.0.16 => v0.0.17
go: upgraded github.com/cloudwego/thriftgo v0.2.8 => v0.3.0
go: upgraded github.com/coreos/go-systemd/v22 v22.3.3-0.20220203105225-a9a7ef127534 => v22.5.0
go: upgraded github.com/dapr/components-contrib v1.11.3-0.20230814210647-01646b8833e1 => v1.11.3-0.20230830004725-1c657f7b5b3e
go: upgraded github.com/eapache/go-resiliency v1.3.0 => v1.4.0
go: upgraded github.com/eapache/go-xerial-snappy v0.0.0-20230111030713-bf00bc1b83b6 => v0.0.0-20230731223053-c322873962e3
go: upgraded github.com/google/s2a-go v0.1.4 => v0.1.5
go: upgraded github.com/google/uuid v1.3.0 => v1.3.1
go: upgraded github.com/googleapis/enterprise-certificate-proxy v0.2.4 => v0.2.5
go: upgraded github.com/hamba/avro/v2 v2.13.0 => v2.15.0
go: upgraded github.com/hashicorp/consul/api v1.22.0 => v1.24.0
go: upgraded github.com/hashicorp/golang-lru/v2 v2.0.4 => v2.0.6
go: upgraded github.com/huaweicloud/huaweicloud-sdk-go-obs v3.22.11+incompatible => v3.23.4+incompatible
go: upgraded github.com/huaweicloud/huaweicloud-sdk-go-v3 v0.1.28 => v0.1.56
go: upgraded github.com/jackc/pgx/v5 v5.4.2 => v5.4.3
go: upgraded github.com/jackc/puddle/v2 v2.2.0 => v2.2.1
go: upgraded github.com/klauspost/compress v1.16.5 => v1.16.7
go: upgraded github.com/labd/commercetools-go-sdk v1.2.0 => v1.3.1
go: upgraded github.com/lestrrat-go/jwx/v2 v2.0.11 => v2.0.12
go: upgraded github.com/mrz1836/postmark v1.4.0 => v1.6.1
go: upgraded github.com/nats-io/nats.go v1.27.1 => v1.28.0
go: upgraded github.com/open-policy-agent/opa v0.49.2 => v0.55.0
go: upgraded github.com/pierrec/lz4/v4 v4.1.17 => v4.1.18
go: upgraded github.com/prometheus/procfs v0.10.1 => v0.11.0
go: upgraded github.com/redis/go-redis/v9 v9.0.5 => v9.1.0
go: upgraded github.com/sendgrid/sendgrid-go v3.12.0+incompatible => v3.13.0+incompatible
go: upgraded github.com/sijms/go-ora/v2 v2.7.9 => v2.7.17
go: upgraded github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.608 => v1.0.732
go: upgraded github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/ssm v1.0.608 => v1.0.732
go: upgraded github.com/tetratelabs/wazero v1.3.0 => v1.5.0
go: upgraded github.com/valyala/fasthttp v1.48.0 => v1.49.0
go: upgraded github.com/vmware/vmware-go-kcl v1.5.0 => v1.5.1
go: upgraded github.com/yashtewari/glob-intersection v0.1.0 => v0.2.0
go: upgraded go.mongodb.org/mongo-driver v1.12.0 => v1.12.1
go: upgraded golang.org/x/crypto v0.11.0 => v0.12.0
go: upgraded golang.org/x/exp v0.0.0-20230801115018-d63ba01acd4b => v0.0.0-20230817173708-d852ddb80c63
go: upgraded golang.org/x/net v0.13.0 => v0.14.0
go: upgraded golang.org/x/oauth2 v0.10.0 => v0.11.0
go: upgraded golang.org/x/term v0.10.0 => v0.11.0
go: upgraded golang.org/x/text v0.11.0 => v0.12.0
go: upgraded golang.org/x/tools v0.11.0 => v0.12.1-0.20230815132531-74c255bcf846
go: upgraded google.golang.org/api v0.128.0 => v0.138.0
go: upgraded google.golang.org/genproto v0.0.0-20230706204954-ccb25ca9f130 => v0.0.0-20230821184602-ccc8af3d0e93
go: upgraded google.golang.org/genproto/googleapis/api v0.0.0-20230629202037-9506855d4529 => v0.0.0-20230803162519-f966b187b2e5
go: upgraded google.golang.org/genproto/googleapis/rpc v0.0.0-20230711160842-782d3b101e98 => v0.0.0-20230807174057-1744710a1577
go: upgraded google.golang.org/grpc v1.56.2 => v1.57.0
go: upgraded k8s.io/klog/v2 v2.80.1 => v2.90.1
go: upgraded modernc.org/sqlite v1.24.0 => v1.25.0
```

### CODE REVIEW

**Comment by berndverst** [comment]
Note that there are many more dependency upgrades for indirect dependencies like sarama going from Shopify/sarama@v1.37.2 to IBM/sarama@v1.41.0

**Review by mukundansundar — APPROVED** [review]
overall lgtm

**Pull request merged**
