### PR TITLE
Refactor gRPC and protobuf messages

### PR DESCRIPTION
**Pull request by youngbupark**
# Description

**Agreed change from the meeting**
* Move duplicated messages to common.proto
* Any -> bytes
* Use `Request` suffix for request message and `Response` suffix for response message
* DaprClient -> AppCallback
* daprinternal -> Internal.ServiceInvocation **(If you don't like this naming, please leave the comment)**
* PlacementService -> Placement

**New changes** - If you do not agree, please leave the comment.
* Add self-descriptive comments to gRPC / protobuf message.
* Use `List` prefix for the method which gets the list of items rather than `Get` - I referred to [google api proto](https://github.com/googleapis/googleapis)

## Issue reference

#1464 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by youngbupark** [comment]
@yaron2 

Can we merge appcallback/v1 to dapr/v1 ? So dapr api service and appcallback service will share the same package `dapr.proto.dapr.v1`.

So the full service names will be:
1. dapr.proto -> dapr.proto.dapr.v1.Dapr
2. appcallback.proto -> dapr.proto.dapr.v1.AppCallback

What is your thought on this?

**Comment by yaron2** [comment]
I'm ok with merging, what I don't like in general is the long namespace and the repitition of dapr

**Comment by amanbha** [comment]
> @yaron2
> 
> Can we merge appcallback/v1 to dapr/v1 ? So dapr api service and appcallback service will share the same package `dapr.proto.dapr.v1`.
> 
> So the full service names will be:
> 
> 1. dapr.proto -> dapr.proto.dapr.v1.Dapr
> 2. appcallback.proto -> dapr.proto.dapr.v1.AppCallback

Are you suggesting to merge in same file?

**Comment by youngbupark** [comment]
> > @yaron2
> 
> > 
> 
> > Can we merge appcallback/v1 to dapr/v1 ? So dapr api service and appcallback service will share the same package `dapr.proto.dapr.v1`.
> 
> > 
> 
> > So the full service names will be:
> 
> > 
> 
> > 1. dapr.proto -> dapr.proto.dapr.v1.Dapr
> 
> > 2. appcallback.proto -> dapr.proto.dapr.v1.AppCallback
> 
> 
> 
> Are you suggesting to merge in same file?

No, i am suggesting to merge directories. So those are separated files in the same directory.

**Comment by youngbupark** [comment]
> I'm ok with merging, what I don't like in general is the long namespace and the repitition of dapr

@yaron2 @amanbha 

If you do not like repetition of `dapr`, can we rename `dapr` to `api` ?

For example,

1. dapr/proto/api/v1
   - dapr.proto -> Fullname: `dapr.proto.api.v1.Dapr`
   - appcallback.proto -> Fullname: `dapr.proto.api.v1.AppCallback`
2. dapr/proto/internal/v1 -> service_invocation.proto
3. dapr/proto/placement/v1
4. dapr/proto/operator/v1
5. dapr/proto/sentry/v1

**Comment by yaron2** [comment]
That's better, but I'd look for something a little more descriptive, like runtime or sidecar.

**Comment by youngbupark** [comment]
> That's better, but I'd look for something a little more descriptive, like runtime or sidecar.

I like `runtime` rather than `sidecar`.

**Comment by youngbupark** [comment]
@amanbha @artursouza @LMWF @mchmarny what are your thoughts on this naming ?

**Comment by amanbha** [comment]
@youngbupark LGTM with runtime

**Comment by LMWF** [comment]
My vote is for "runtime" too.

**Comment by youngbupark** [comment]
Thanks for all the feedbacks. I updated PR accordingly based on the feedbacks. 

I have renamed `dapr` to `runtime` and updated README.md as well. please review the pr again. 

cc/ @yaron2 @amanbha

**Pull request merged**
