### PR TITLE
Remove `ActorScanInterval`

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Small refactoring to the actors subsystem to remove the "ActorScanInterval" configuration. Idle actors are now deactivated automatically shortly after the idle timeout for their actor type.

> The priority queue implemented in this PR in `pkg/actors/internal` is the same code used in #6716 . It should be possible to review and merge the 2 PRs independently.

Benefits:

- Simplifies the experience for users who now need to worry about one less property
- Makes the actor subsystem more predictable: idle actors are now deactivated after the idle timeout, and there's no uncertainty due to the next scan interval.
- Offers perf improvements since we are not scanning the map of active actors on regular intervals (by default 30s)
   - All active actors are placed in a priority queue (heap-based), with the actor that is the first to reach its "deadline" at the top. Lookups for the first actor are O(1)
   - Every time an actor gets invoked, its "idle at" time, and thus its position in the queue, are updated. This operation's complexity is an efficient O(log n)
   - A goroutine is blocked waiting on the time the next actor becomes idle at, and ready to be deactivated.
   - There's no background goroutine if there's no active actor running.

Why this is **not** a breaking change:

- Actors are considered in a state where they can be deactivated after they are idle for "idle timeout".
- The current implementation performs deactivation using a "garbage collection" loop that runs every "scan interval". This is 30s by default. This means that there are "optimistic" and "pessimistic" cases:
   - In the optimistic case, the GC loop happens right after the actor becomes idle and gets deactivated right away.
   - In the pessimistic case, an actor's lifetime is extended by a full "scan interval" duration
- The point of the "scan interval" property is to configure the pessimistic case, knowing that:
   - A short "scan interval" uses more resources
   - A long "scan interval" makes actors alive for longer, thus using more resources in a different way.
      - Additionally, an actor that is idle but hasn't been GC'd yet could be re-activated right away if a call comes in. This is a potentially unexpected behavior for users, and _could be considered a bug_. Developers should expect an actor to become deactivated after its idle timeout has passed, and additional calls should activate the actor again possibly on a different host, not keeping it alive for longer
- Because this PR makes the "optimistic case" the only possible case, the scan interval property becomes irrelevant, not deprecated. There's no change in user-facing behavior, as the contract stating that actors are deactivated after _at least_ "idle timeout" remains valid.
   - We have removed other configuration options from Dapr in the past without any fuss or deprecation notice when they became irrelevant and their absence did not cause the user-observed behavior to change.

### CODE REVIEW

**Review by artursouza — CHANGES_REQUESTED** [review]
Please, start a discussion. This is not minor and this setting has been key to balance timely GC and CPU usage.

**Comment by ItalyPaleAle** [comment]
> This is not minor and this setting has been key to balance timely GC and CPU usage.

Yes, that's why it's been removed :) Before there was a goroutine that on an interval was scanning all actors, thus with the concerns around GC and CPU. Now, we block the goroutine until we know an actor becomes idle.

You can see the single commit here: https://github.com/dapr/dapr/pull/6715/commits/c75700f48c63ca4f056979f1a2cf0909cce813d4

**Comment by yaron2** [comment]
We can't remove this for this release as it's a breaking chang. We can mark this as deprecated in 1.12 (if there's consensus for it) and then remove in 1.14.

**Comment by ItalyPaleAle** [comment]
> We can't remove this for this release as it's a breaking change. We can mark this as deprecated in 1.12 (if there's consensus for it) and then remove in 1.14.

There's no breaking change and it's a pretty important perf improvement (see #6592)

**Comment by yaron2** [comment]
> > We can't remove this for this release as it's a breaking change. We can mark this as deprecated in 1.12 (if there's consensus for it) and then remove in 1.14.
> 
> There's no breaking change and it's a pretty important perf improvement (see #6592)

It's documented as part of the API and contract between Dapr and the app. Removing this will result in a breaking behavioral change.

**Comment by yaron2** [comment]
> > > We can't remove this for this release as it's a breaking change. We can mark this as deprecated in 1.12 (if there's consensus for it) and then remove in 1.14.
> > 
> > 
> > There's no breaking change and it's a pretty important perf improvement (see #6592)
> 
> It's documented as part of the API and contract between Dapr and the app. Removing this will result in a breaking behavioral change.

cc @daixiang0 @mukundansundar

**Comment by ItalyPaleAle** [comment]
> > > We can't remove this for this release as it's a breaking change. We can mark this as deprecated in 1.12 (if there's consensus for it) and then remove in 1.14.
> > 
> > 
> > There's no breaking change and it's a pretty important perf improvement (see #6592)
> 
> It's documented as part of the API and contract between Dapr and the app. Removing this will result in a breaking behavioral change.

It doesn't alter the behavior that actors are deactivated after they become idle for a certain amount of time. If the scan interval option is passed, it is ignored.

This just makes it more efficient and more predictable. Before, if scan interval was 5s, an idle actor could be deactivated right away or after 5s. Now, idle actors are deactivated "as soon as" their timeout expires.

There's no user-facing behavior change. Per the contract, users should have assumed that an actor could be deactivated any time after its idle timeout passed. This doesn't change that at all.

**Comment by yaron2** [comment]
> 

Ok, so to be clear:

If a user passes an ActorScanInterval value of 1m, can they expect an actor to become deactivated after 1m?

**Comment by ItalyPaleAle** [comment]
> > 
> 
> Ok, so to be clear:
> 
> If a user passes an ActorScanInterval value of 1m, can they expect an actor to become deactivated after 1m?

If a user passes "ActorIdleTimeout" of 1m, they can expect an actor to be deactivated after 1m of inactivity. This was the case before and is the case after

What changed is:

- Before: if users passed "ActorScanInterval" of 1m, the (idle) actor could be deactivated after 1 min of becoming idle in the "best case" scenario, and 2 mins in the "worst case" scenario. This was not guaranteed and it depended on where in the scan loop the actor runtime was. Users should have assumed the actor's lifetime was not to extend 1m after becoming idle.
- After: there's no "ActorScanInterval", so an actor that becomes idle is deactivated "right after". This means that an idle actor gets deactivated after 1 min of becoming idle in all cases.

https://docs.dapr.io/developing-applications/building-blocks/actors/actors-runtime-config/

**Comment by yaron2** [comment]
> > > 
> > 
> > 
> > Ok, so to be clear:
> > If a user passes an ActorScanInterval value of 1m, can they expect an actor to become deactivated after 1m?
> 
> If a user passes "ActorIdleTimeout" of 1m, they can expect an actor to be deactivated after 1m of inactivity. This was the case before and is the case after
> 
> What changed is:
> 
> * Before: if users passed "ActorScanInterval" of 1m, the (idle) actor could be deactivated after 1 min of becoming idle in the "best case" scenario, and 2 mins in the "worst case" scenario. This was not guaranteed and it depended on where in the scan loop the actor runtime was. Users should have assumed the actor's lifetime was not to extend 1m after becoming idle.
> * After: there's no "ActorScanInterval", so an actor that becomes idle is deactivated "right after". This means that an idle actor gets deactivated after 1 min of becoming idle in all cases.
> 
> https://docs.dapr.io/developing-applications/building-blocks/actors/actors-runtime-config/

I'm not debating the benefits or correctness of this change, simply this is a clear breaking change and should be treated as such. Will wait for feedback of other maintainers on this.

**Comment by ItalyPaleAle** [comment]
> I'm not debating the benefits or correctness of this change, simply this is a clear breaking change and should be treated as such. Will wait for feedback of other maintainers on this.

I am not sure I follow. Why do you consider this a breaking change?

**Comment by artursouza** [comment]
Can this be enabled via a configuration. If ActorScanInterval <= 0 then it is the new behavior, otherwise it is the old behavior.

**Comment by ItalyPaleAle** [comment]
I didn't think this would be controversial as it shouldn't be a breaking change at all.

The current behavior is that there's an optimistic case, which is that actors are deactivated as soon as the idle timeout passes, and a pessimistic case, which is that actors stay alive for longer, as long as the scan interval. There's obviously a trade-off between the two things: keeping actors alive for longer uses more resources, while a shorter scan interval means more frequent scans which use more resources too. I believe @artursouza when he says that the scan interval option was added to find the right balance with GC and CPU usage.

The point of this change is to remove the make the optimistic case the only case. It's quite literally the "have your cake and eat it too": you get actors that are deactivated right away after the idle timeout (so not wasting more resources and acting very predictably), and you don't pay the cost of the periodic scan interval.

Although it's true this PR does remove a configuration option, it does that by retaining the same functionality, so users are not missing out on anything. I would be surprised to hear from anyone complaining about this.

> The only situation where users would be impacted here is if they were counting on actor scan interval as a way to "extend" the lifetime of an actor beyond its idle timeout. I am not concerned about these users much because they shouldn't have done this to begin with: in some cases the actors were alive for an extra "scan interval" time, but in others they'd be terminated right away, and users should not have taken a dependency on this random behavior.

**Comment by yaron2** [comment]
> I would be surprised to hear from anyone complaining about this

Personally knowing how many users are using it, I wouldn't be.

> Although it's true this PR does remove a configuration option, it does that by retaining the same functionality

Yes, but that same functionality is retained by utilizing a different configuration option. If you had said that users who previously set `ActorScanInterval` to `7h` and expected that actors get deactivated after 7 hours (at minimum) or later would expect the exact same behavior when moving to 1.12 without code changes, then I would have agreed this should ot be considered a breaking change. To my understanding, this is not what's being said.

**Comment by yaron2** [comment]
> > Yes, but that same functionality is retained by utilizing a different configuration option. If you had said that users who previously set `ActorScanInterval` to `7h` and expected that actors get deactivated after 7 hours (at minimum) or later would expect the exact same behavior when moving to 1.12 without code changes, then I would have agreed this should not be considered a breaking change. To my understanding, this is not what's being said.
> 
> Hold on, I think I understand where the misunderstanding is. Are you maybe thinking of `ActorIdleTimeout`?
> 
> * `ActorIdleTimeout` is what determines how long after the last message the actor is considered idle.
> * `ActorScanInterval` indicates how often the loop runs to check which actors are idle and are past `ActorIdleTimeout`.
> 
> If you want actors to have a 7h lifetime minimum, you set `ActorIdleTimeout` to 7h. This will not change in this PR.

I will make this clearer - If users set `ActorScanInterval` to any value in 1.11.x and expected the scan to elapse at the configured interval to check which actors are idle after `ActorIdleTimeout`, and after having upgraded to 1.12.x have not changed anything in their code or configuration and are observing a different behavior, then this is a breaking change.

**Comment by ItalyPaleAle** [comment]
> if users set ActorScanInterval to any value in 1.11.x and expected the scan to elapse at the configured interval to check which actors are idle after ActorIdleTimeout

Users must not have this expectation. Actors in 1.11 can be terminated any time after ActorIdleTimeout lapses. In the "optimistic case", the loop happens immediately after so actors are terminated right away.

For users to rely on the pessimistic case to determine the lifecycle of an actor is a bug even in 1.11 because it is not deterministic.

**Comment by yaron2** [comment]
> > if users set ActorScanInterval to any value in 1.11.x and expected the scan to elapse at the configured interval to check which actors are idle after ActorIdleTimeout
> 
> Users must not have this expectation. Actors in 1.11 can be terminated any time after ActorIdleTimeout lapses. In the "optimistic case", the loop happens immediately after so actors are terminated right away.
> 
> For users to rely on the pessimistic case to determine the lifecycle of an actor is a bug even in 1.11 because it is not deterministic.

Bug or not, expectation or not - are all subjective. What's not subjective is that we are removing an API field that will no longer do what it was supposed to do, and that is objectively a breaking change that we must, and will, treat as one.

**Comment by yaron2** [comment]
I think the suggestion made by @artursouza to retain backwards-compat is solid and should allow this PR to be merged once implemented.

**Comment by yaron2** [comment]
> PS: please don't "merge master" into draft PRs. When the underlying PR is merged, I'll have to cherry-pick the second commit and having master merged in makes that harder! 🙏

👍

**Comment by yaron2** [comment]
> The current behavior is that a 0 value means "accept the default", which is 30s. So that could be a breaking change too per your definition.

If a user isn't required to perform any changes to their code/config from 1.11 to 1.12 and will observe the exact same behavior as they did before, then this isn't a breaking change.

**Comment by ItalyPaleAle** [comment]
This PR is now ready for review and it's been updated to be even more efficient thanks to using a priority queue, which allows avoiding all scans of the active actors table. (The Queue and Processor structs used by the priority queue are the same used for #6716).

I have expanded the description and also included an explanation on why this does not include a breaking change for users, and at the same time offers very welcome improvements on perf and ease of use.

I ask maintainers to please give this a reconsideration.

**Comment by yaron2** [comment]
> I have expanded the description and also included an explanation on why this does not include a breaking change for users, and at the same time offers very welcome improvements on perf and ease of use.

Thanks for the update. The `ActorScanInterval` field exists as a public contract in all Dapr SDKs. If we remove it from the runtime, we must also remove it from the SDKs. In that case, applications that update their dependencies to a new Dapr SDK version as part of upgrading to Dapr 1.12 will break at compilation time, forcing users to change their code to adapt. Do you agree this is a breaking change for the SDKs, and in general how do you suggest we tackle that issue if we remove `ActorScanInterval`?

**Comment by ItalyPaleAle** [comment]
> > I have expanded the description and also included an explanation on why this does not include a breaking change for users, and at the same time offers very welcome improvements on perf and ease of use.
> 
> Thanks for the update. The `ActorScanInterval` field exists as a public contract in all Dapr SDKs. If we remove it from the runtime, we must also remove it from the SDKs. In that case, applications that update their dependencies to a new Dapr SDK version as part of upgrading to Dapr 1.12 will break at compilation time, forcing users to change their code to adapt. Do you agree this is a breaking change for the SDKs, and in general how do you suggest we tackle that issue if we remove `ActorScanInterval`?

The field can continue to be provided it is just ignored. SDKs can manage the deprecation nicely, and make the property a no-op to avoid breaking users. So outdated SDKs will send the field which is ignored by the runtime. Updated SDKs can continue to have the method which either sends the field (for compat with old Dapr versions), or becomes a no-op.

**Comment by yaron2** [comment]
> > > I have expanded the description and also included an explanation on why this does not include a breaking change for users, and at the same time offers very welcome improvements on perf and ease of use.
> > 
> > 
> > Thanks for the update. The `ActorScanInterval` field exists as a public contract in all Dapr SDKs. If we remove it from the runtime, we must also remove it from the SDKs. In that case, applications that update their dependencies to a new Dapr SDK version as part of upgrading to Dapr 1.12 will break at compilation time, forcing users to change their code to adapt. Do you agree this is a breaking change for the SDKs, and in general how do you suggest we tackle that issue if we remove `ActorScanInterval`?
> 
> The field can continue to be provided it is just ignored. SDKs can manage the deprecation nicely, and make the property a no-op to avoid breaking users. So outdated SDKs will send the field which is ignored by the runtime. Updated SDKs can continue to have the method which either sends the field (for compat with old Dapr versions), or becomes a no-op.

As an SDK maintainer I feel uncomfortable providing a field that has no use, because this not only affects existing users but more so it means developers who are getting started with the SDK have an option that is seemingly provided for them but in fact does nothing. It creates a drift between the API spec of the runtime and the different SDKs. So far changes /removals made to the API spec were followed by SDK changes in the same release, the Configuration API is a recent example. At the very least we need to communicate to SDK maintainers that a runtime flag present as a typed entity in their SDK is going to be removed.

**Comment by ItalyPaleAle** [comment]
Alright, if that’s the consensus among maintainers we’ll merge this PR in our distribution. Actor perf is important to us and we want to provide our users the best experience.

Thanks for the feedback.

**Comment by yaron2** [comment]
> Alright, if that’s the consensus among maintainers we’ll merge this PR in our distribution. Actor perf is important to us and we want to provide our users the best experience.
> 
> Thanks for the feedback.

I don't know if that's the consensus among maintainers.. we're still waiting for feedback here. There's no reason to close this PR.

**Comment by yaron2** [comment]
@mukundansundar @daixiang0 your input on this matter is required as we want to arrive at a resolution of this soon.

**Pull request closed without merging**
