### PR TITLE
Enable route based proxying for HTTP in addition to gRPC #3546

### PR DESCRIPTION
**Pull request by beiwei30**
# Description

a quick prototype for Enable route based proxying for HTTP in addition to gRPC #3546

## Issue reference

Please reference the issue this PR will close: #3546

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#1752
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#1752

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks for this @beiwei30! there's a small lint error that's failing the tests:

```
pkg/http/api.go#L818
var `appId` should be `appID` (golint)
```

**Comment by yaron2** [comment]
Thanks @beiwei30, there's just one linter failure now:

```
Check failure on line 630 in pkg/http/server_test.go

GitHub Actions
/ Build linux_amd64 binaries
pkg/http/server_test.go#L630
File is not `gofmt`-ed with `-s` (gofmt)
```

Should be solved with ```go fmt -s -w ./pkg/http/server_test.go```

**Comment by beiwei30** [comment]
@yaron2 would you mind to start to review this change? I also submit a doc pull request dapr/docs#1753

**Review by yaron2 — APPROVED** [review]
lgtm, great PR 👍

**Pull request merged**
