### PR TITLE
tests: add LoadComponentsFromFile test

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long <long0dai@foxmail.com>

# Description

Add LoadComponentsFromFile test

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks @daixiang0!

Notice one of the tests is failing currently.

**Comment by yaron2** [comment]
@daixiang0 tests are still failing.

**Comment by daixiang0** [comment]
Fixed.

**Review by yaron2 — APPROVED** [review]
lgtm

**Review by yaron2 — CHANGES_REQUESTED** [review]
Tests still failing...

**Comment by daixiang0** [comment]
Sorry for mistakes of indent.

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
