### PR TITLE
tests: accelerate docker load

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long <long0dai@foxmail.com>

# Description

## Issue reference

Please reference the issue this PR will close: #3580

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@wcs1only can you take a quick look? I remember we got burned in the past because we didn't have the `Always` policy in tests?

**Comment by daixiang0** [comment]
@wcs1only could you help look?

**Comment by daixiang0** [comment]
@wcs1only could you help look?

**Comment by artursouza** [comment]
The default 

> @wcs1only can you take a quick look? I remember we got burned in the past because we didn't have the `Always` policy in tests?

Default is still Always, it allows override of the behavior. I am OK with this change as long as the OK to test passes.

**Comment by daixiang0** [comment]
@artursouza @yaron2 all tests pass!

**Review by artursouza — APPROVED** [review]

**Pull request merged**
