### PR TITLE
Fix WF Pause flaky test

### PR DESCRIPTION
**Pull request by DeepanshuA**
# Description

Fixes flaky WF Pause UT.

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by DeepanshuA** [comment]
Should be fixed now:

/usr/local/go/bin/go test -timeout 300s -count=20 -run ^TestPauseResumeWorkflow$ github.com/dapr/dapr/pkg/runtime/wfengine
ok      github.com/dapr/dapr/pkg/runtime/wfengine       208.252s

**Comment by DeepanshuA** [comment]
Following tests are still failing:

=== FAIL: pkg/placement TestPlacementHA/set_and_retrieve_state_in_leader_after_re-election (unknown)

=== FAIL: pkg/placement TestPlacementHA/new_leader_after_leader_fails (11.60s)
=== FAIL: pkg/placement TestPlacementHA/set_and_retrieve_state_in_leader_after_re-election (unknown)

=== FAIL: pkg/placement TestMembershipChangeWorker/faulty_host_detector

But, these shouldn't be related to wf pause code.

**Review by ItalyPaleAle — COMMENTED** [review]
Is there a way we can write the test so it doesn’t depend on a clock. We’ve seen that anything that depends on pausing time will be flaky in our CI agents, probably because they’re just slow.
Can this use some coordination mechanism, for example some Go channels?

**Comment by DeepanshuA** [comment]
> Is there a way we can write the test so it doesn’t depend on a clock. We’ve seen that anything that depends on pausing time will be flaky in our CI agents, probably because they’re just slow. Can this use some coordination mechanism, for example some Go channels?

Yeah, that should be possible - let me take a look how I can modify WF task as per that.

**Comment by DeepanshuA** [comment]
> > Is there a way we can write the test so it doesn’t depend on a clock. We’ve seen that anything that depends on pausing time will be flaky in our CI agents, probably because they’re just slow. Can this use some coordination mechanism, for example some Go channels?
> 
> Yeah, that should be possible - let me take a look how I can modify WF task as per that.

I have based orchestration in test on an event rather than sleep now.

**Review by mukundansundar — APPROVED** [review]
lgtm

**Pull request merged**
