### PR TITLE
feat: add opa http middleware

### PR DESCRIPTION
**Pull request by RichiCoder1**
# Description

Adds the opa middlware from components-contrib

## Issue reference

This PR partially completes #1617 (will open standalone ticket)

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation: https://github.com/dapr/docs/ repo: dapr/docs#787

### CODE REVIEW

**Comment by yaron2** [comment]
@RichiCoder1 can you please resolve the conflicts so we can merge this? thanks!

**Comment by RichiCoder1** [comment]
Rebased & `go mod tidy`'d, should be good?

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
Thanks for your contribution.

Can you open a standalone issue so we can put this in our release notes?

**Comment by RichiCoder1** [comment]
https://github.com/dapr/dapr/issues/2082 done!

**Pull request merged**
