### PR TITLE
Update pinned components-contrib

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Includes some code changes because of the latest components-contrib

- mDNS nameresolver uses different keys for metadata now (resolves a long-standing TODO: see dapr/components-contrib#2596)
- Unregistered bindings.twitter which has been removed
- Allow use if `AzureCliCredential` for Azure components auth

### CODE REVIEW

**Comment by berndverst** [comment]
@ItalyPaleAle Can you update it one more time to also bring in the Queue SDK change?

**Comment by ItalyPaleAle** [comment]
@berndverst done. I have also added a new command `make update-components-contrib` (can optionally choose the branch with env var `COMPONENTS_CONTRIB_BRANCH`)

**Comment by ItalyPaleAle** [comment]
Updated again to pull in latest components-contrib, now without the old (track 1) Azure SDK

**Comment by ItalyPaleAle** [comment]
All tests are failing because the latest components-contrib requires Go 1.20.

We need to update the runtime first: https://github.com/dapr/dapr/pull/5876

**Comment by berndverst** [comment]
Runtime is updated. Now can see if we can merge this :)

**Comment by mukundansundar** [comment]
> Includes some code changes because of the latest components-contrib
> 
> * mDNS nameresolver uses different keys for metadata now (resolves a long-standing TODO: see [Resolve long-standing TODO in mDNS component components-contrib#2596](https://github.com/dapr/components-contrib/pull/2596))
> * Unregistered bindings.twitter which has been removed

@ItalyPaleAle @berndverst twitter binding was only deprecated in 1.10, acc to dapr deprecation policy we should only remove it in 1.12?
But the question also that I have is, has the binding become completely unusable?
Also on removing this are there any other changes to be done in quoickstarts / samples?

**Comment by ItalyPaleAle** [comment]
@mukundansundar the discussion on deprecating the Twitter binding was here: https://github.com/dapr/components-contrib/issues/2503

**Comment by mukundansundar** [comment]
> @mukundansundar the discussion on deprecating the Twitter binding was here: [dapr/components-contrib#2503](https://github.com/dapr/components-contrib/issues/2503)

I agree with the deprecation ... just that based on existing deprecation policy it should only be removed in 1.12 and not in 1.11.

**Comment by mukundansundar** [comment]
> > @mukundansundar the discussion on deprecating the Twitter binding was here: [dapr/components-contrib#2503](https://github.com/dapr/components-contrib/issues/2503)
> 
> I agree with the deprecation ... just that based on existing deprecation policy it should only be removed in 1.12 and not in 1.11.

based on offline discussion, Twitter component is going to be removed in 1.11.

**Review by mukundansundar — APPROVED** [review]
lgtm

**Comment by berndverst** [comment]
@mukundansundar Twitter binding can be removed in 1.11 as the component was Alpha - and additional users can no longer sign up for the required Twitter API accounts for some time now anyway.

The latest contrib included here adds a HUGE feature for Azure users -- support for `AzureCLICredential` which allows you to authenticate to Azure Services by piggybacking on your CLI that is logged in. It works essentially similar to Managed Identity.

**Review by mukundansundar — APPROVED** [review]
lgtm

**Review by yaron2 — APPROVED** [review]

**Comment by berndverst** [comment]
Runtime build matrix / unit tests are so flaky now :(

**Pull request merged**
