### PR TITLE
pin latest dapr/contrib again

### PR DESCRIPTION
**Pull request by berndverst**
Signed-off-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>

# Description

Pin latest dapr/contrib again.

```
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/azcore v1.1.0 => v1.1.3
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/data/azappconfig v0.4.0 => v0.4.1-0.20220914204640-4d445978fe75
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets v0.7.1 => v0.10.1
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal v0.5.0 => v0.7.0
go: upgraded github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus v1.0.1 => v1.1.0
go: upgraded github.com/dapr/components-contrib v1.8.0-rc.1.0.20220921204352-7b787d491072 => v1.8.0-rc.1.0.20220922070409-9772c103c22c
```

### CODE REVIEW

**Review by pravinpushkar — APPROVED** [review]

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
I am running OK to test a few times to see if the E2E tests were broken at this change.

**Pull request merged**
