### PR TITLE
Pass logger to contrib

### PR DESCRIPTION
**Pull request by youngbupark**
# Description

Pass logger to contrib

## Issue reference

n/a

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by yaron2** [comment]
Well this gives a new meaning to failing fast.. :)

**Comment by youngbupark** [comment]
> Well this gives a new meaning to failing fast.. :)

CMD+Z reverted mod change...

**Pull request merged**
