### PR TITLE
Fix missing label on server_server_latency metric

### PR DESCRIPTION
**Pull request by ckcd**
# Description

Fix missing `grpc_server_status` label on `dapr_grpc_io_server_server_latency` metric.

## Issue reference

https://github.com/dapr/dapr/issues/7045

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing

### CODE REVIEW

**Comment by ckcd** [comment]
Seems like we need a `ok-to-test` label, @dapr-bot

**Comment by ckcd** [comment]
@famarting @ItalyPaleAle PTAL, thanks.

**Comment by ckcd** [comment]
@RyanLettieri @ItalyPaleAle @artursouza @JoshVanL PTAL, thanks.

**Review by daixiang0 — APPROVED** [review]
LGTM

**Comment by daixiang0** [comment]
@ckcd thanks for your contribution!

**Pull request merged**
