### PR TITLE
Switch parsing of CLI flags to pflag

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
> Includes #6925 and expands that

Minor refactoring of the CLI flag parsers to be based on pflag rather than the stdlib's flag. Applies to daprd and control plane services.

There are 3 reasons for this change:

- The stdlib's flag package defines all CLI flags in a global state. This means that if we import a library that defines a flag, it gets added to our CLIs. This is not a hypothetical scenario, as we had an issue fixed in Dapr 1.12 where a component was adding a flag to the daprd CLI without us realizing it for a long time.
- pflag has better support for deprecated flags, which can be hidden from the `--help` command. We have 2 deprecated flags in daprd currently, and there may be more if #7028 is worked on
- Lastly, pflag has some very nice features, including a nicer `--help` message and helpers for example for accepting slices. We can define a flag with `StringSliceVar` and it parses automatically multiple instances of the same flag (e.g. `--config a.yaml --config b.yaml`) as well as comma-separated values (`--config a.yaml,b.yaml`) and a combination of the two.

> Yes, this is partly based on #6766, but unlike that it doesn't change the behavior. Apps will continue to crash if unknown flags are passed.

### CODE REVIEW

**Review by daixiang0 — APPROVED** [review]

**Review by mukundansundar — CHANGES_REQUESTED** [review]
please have token audience removal as a separate PR.

**Review by DeepanshuA — COMMENTED** [review]
Do we need to showcase any manual tests here as well, to show the usage of pflag makes no difference in user experience?

**Comment by ItalyPaleAle** [comment]
> Do we need to showcase any manual tests here as well, to show the usage of pflag makes no difference in user experience?

The E2E and IT test should be validating this already, as they invoke the commands using the CLI flags

**Review by DeepanshuA — APPROVED** [review]

**Comment by mukundansundar** [comment]
@ItalyPaleAle Was this change to `daprd` tested with existing `dapr` CLI?

**Comment by ItalyPaleAle** [comment]
> @ItalyPaleAle Was this change to `daprd` tested with existing `dapr` CLI?

Yes it works with the CLI

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
