### PR TITLE
Incorporate oracle database statestore component in dapr runtime

### PR DESCRIPTION
**Pull request by lucasjellema**
# Description
Incorporate oracle database statestore component in dapr runtime

## Issue reference
https://github.com/dapr/dapr/issues/4221

Please reference the issue this PR will close: #_[4221]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by daixiang0** [comment]
Could you run `go mod tidy` to fix CI?

**Comment by lucasjellema** [comment]
Checks failed with this message:
_errors in package: [/home/runner/work/dapr/dapr/pkg/grpc/api_test.go:1889:67: cannot use &(mockConfigStore literal) (value of type *mockConfigStore) as configuration.Store value in map literal: missing method Unsubscribe /home/runner/work/dapr/dapr/pkg/grpc/api_test.go:1922:74: cannot use &(mockConfigStore literal) (value of type *mockConfigStore) as configuration.Store value in map literal: missing method Unsubscribe]_

This is not something todo with this PR and not something I can fix it would seem.

**Comment by daixiang0** [comment]
@lucasjellema could you fix conflicts?

**Comment by lucasjellema** [comment]
> @lucasjellema could you fix conflicts?

done

**Review by daixiang0 — APPROVED** [review]

**Comment by daixiang0** [comment]
@lucasjellema thanks for your contribution!

**Pull request merged**
