### PR TITLE
fix error on invalid status for pubsub.

### PR DESCRIPTION
**Pull request by mukundansundar**
# Description

On invalid status, HTTP and gRPC responds with error. 

On empty status, both protocols respond with success and return nil. 

Updated unit tests and added e2e test for invalid status.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2235 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo:https://github.com/dapr/docs/issues/871
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by mukundansundar** [comment]
This is the response matrix https://github.com/dapr/dapr/issues/2235#issuecomment-707275482

**Comment by mukundansundar** [comment]
From KinD e2e tests: 
```
--- PASS: TestPubSub (67.72s)
    --- PASS: TestPubSub/publish_and_subscribe_message_successfully (5.66s)
    --- PASS: TestPubSub/publish_with_subscriber_returning_empty_json_test_delivery_of_message_once (19.60s)
    --- PASS: TestPubSub/publish_with_no_topic (0.00s)
    --- PASS: TestPubSub/publish_with_subscriber_error_test_redelivery_of_messages (16.52s)
    --- PASS: TestPubSub/publish_with_subscriber_retry_test_redelivery_of_messages (13.51s)
    --- PASS: TestPubSub/publish_with_subscriber_invalid_status_test_redelivery_of_messages (11.41s)
```

**Comment by mukundansundar** [comment]
@artursouza @yaron2 Fixed the pubsub based on https://github.com/dapr/dapr/issues/2235#issuecomment-707275482

Marking it as a breaking change since the error condition for gRPC was changed. A scenario where there is no error on invoking the user application, and also the status does not match SUCCESS, RETRY or DROP, a nil error is returned. 

In this change the proper error of unknown status is returned.

**Review by artursouza — APPROVED** [review]

**Review by youngbupark — COMMENTED** [review]
lgtm

**Pull request merged**
