### PR TITLE
Fix dead letter topic keeping message in original topic

### PR DESCRIPTION
**Pull request by yaron2**
This PR adds a missing return statement that caused messages dropped into the dead letter topic to be kept and retried on the original topic.

Also adds a minor change for code readability and fixes wrong metric from `Retry` to `Success` when the app returns `2xx`.

### CODE REVIEW

**Review by halspang — COMMENTED** [review]
Change makes sense but I see a lot of pubsub errors in the e2e.

**Comment by yaron2** [comment]
> Change makes sense but I see a lot of pubsub errors in the e2e.

Yeah the e2e test needs to be rechecked.

**Comment by yaron2** [comment]
@Taction I want to get your take on the e2e test case you wrote.

This PR fixes a bug where messages would still be kept on the original topic after an app returned an error and the topic was sent to dead letter queue. This means topics would get redelivered to the app from the original topic when they shouldn't have been.

I can confirm the correct behavior by:

1. Publishing 10 messages to topic X
2. Subscribing to topic X and returning an error, with having a dead letter topic Y configured
3. Confirm messages from topic X are not getting delievered
4. Consume 10 messages from dead letter topic Y
5. Confirm messages from dead letter topic Y are not getting redelivered

Looking at the e2e test logs above, it looks like the test was written to expect redelivery of messages sent to the dead letter topic. Can you confirm this needs to be changed?

**Comment by Taction** [comment]
@yaron2 Thanks for your fix, I'll look into the e2e tests.

**Comment by Taction** [comment]
@yaron2 The e2e topic check is changed, fixed now.

**Review by halspang — APPROVED** [review]

**Comment by yaron2** [comment]
> @yaron2 The e2e topic check is changed, fixed now.

Thanks!

**Comment by ItalyPaleAle** [comment]
@yaron2  @Taction  looks like after this PR was merged, E2E tests on AKS are now failing almost every time with errors due to PubSub.

**Comment by ItalyPaleAle** [comment]
My attempt (hoping I understood the intent correctly): https://github.com/dapr/dapr/pull/4792

**Comment by ItalyPaleAle** [comment]
I think I found the issue, it was in the tests. The messages were re-delivered in the DLQ a bit too slow and they came in too late. I increased the sleep times here: https://github.com/dapr/dapr/pull/4793

**Pull request merged**
