### PR TITLE
Fix nil pointer for policyDef in runtime

### PR DESCRIPTION
**Pull request by DeepanshuA**
Signed-off-by: Deepanshu Agarwal <deepanshu.agarwal1984@gmail.com>

# Description

Few Certification tests in dapr/components-contrib are failing, if somehow policyDef is nil. e.g.:
https://github.com/dapr/components-contrib/actions/runs/3872016087/jobs/6600380515#step:23:174
https://github.com/dapr/components-contrib/actions/runs/3872016087/jobs/6600381140#step:23:184
https://github.com/dapr/components-contrib/actions/runs/3872016087/jobs/6600380245#step:23:318

So, for latest dapr/dapr referred in contrib, they are failing:
https://github.com/DeepanshuA/components-contrib/actions/runs/3873108358/jobs/6602751037

This small check fixes that.

Fix verification:
https://github.com/DeepanshuA/components-contrib/actions/runs/3875970689/jobs/6609245631 (FYI: cloud parameters are not set on my env., so cloud related tests are failing, so that's not a concern).

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]

**Review by ItalyPaleAle — CHANGES_REQUESTED** [review]
Upon further consideration (also thanks @mukundansundar ), can you fix this in all other places where there's a similar pattern please?

**Review by ItalyPaleAle — DISMISSED** [review]

**Comment by mukundansundar** [comment]
@DeepanshuA Please fix conflicts and fix DCO also. Rest lgtm.

**Comment by ItalyPaleAle** [comment]
Sorry the DCO issue was my fault. Fixed

**Review by ItalyPaleAle — DISMISSED** [review]

**Review by artursouza — APPROVED** [review]

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
