### PR TITLE
Add metrics to http client of appchannel

### PR DESCRIPTION
**Pull request by youngbupark**
# Description

Add metrics to http client of appchannel

image

## Issue reference

#971 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by youngbupark** [comment]
image

@yaron2 @shalabhms round-trip latency using http client latency stat (example uses helloworld kubernetes samples)

**Comment by yaron2** [comment]
> image
> 
> @yaron2 @shalabhms round-trip latency using http client latency stat (example uses helloworld kubernetes samples)

Wow this is super fast!!! considering it also measures the app calling into Dapr again and then Dapr calling to Redis to save state.

**Comment by youngbupark** [comment]
@jjcollinge I added http_client metrics.

**Comment by youngbupark** [comment]
> Wow this is super fast!!! considering it also measures the app calling into Dapr again and then Dapr calling to Redis to save state.

@yaron2 yup... this is the current latency.

image

**Pull request merged**
