### PR TITLE
change tls server reload

### PR DESCRIPTION
**Pull request by yaron2**
Change to `GetCertificate` instead of stopping and starting the gRPC server on cert reload.

### CODE REVIEW

**Comment by yaron2** [comment]
@youngbupark can you check why the make test is failing? running `make test` locally works fine, and the errors are very weird about code redeclerations, which the linter isn't even complaining about.

**Comment by youngbupark** [comment]
> @youngbupark can you check why the make test is failing? running `make test` locally works fine, and the errors are very weird about code redeclerations, which the linter isn't even complaining about.

```
# github.com/dapr/dapr/pkg/grpc
##[error]pkg/grpc/server.go:89:1: syntax error: non-declaration statement outside function body
##[error]pkg/grpc/server.go:109:2: certWatchInterval redeclared in this block
	previous declaration at pkg/grpc/server.go:26:44
##[error]pkg/grpc/server.go:110:2: renewWhenPercentagePassed redeclared in this block
	previous declaration at pkg/grpc/server.go:27:30
##[error]pkg/grpc/server.go:114:6: Server redeclared in this block
	previous declaration at pkg/grpc/server.go:31:6
##[error]pkg/grpc/server.go:118:6: server redeclared in this block
	previous declaration at pkg/grpc/server.go:35:6
##[error]pkg/grpc/server.go:132:6: NewServer redeclared in this block
	previous declaration at pkg/grpc/server.go:49:112
```

this is error

**Comment by youngbupark** [comment]
@yaron2 golanglint-ci tried to fix unused stop() but the result was weird. maybe we need to remove `--fix` option in `make lint` later.

**Comment by yaron2** [comment]
I support removing --fix, also in contrib.

**Pull request merged**
