### PR TITLE
Hotfix for actor subsystem initialization backported from 1.7 (#4622)

### PR DESCRIPTION
**Pull request by johnewart**
Backporting code changes for actor fix (1.7.3) to 1.5.2

Opening draft PR to run tests before asking for review.

Signed-off-by: John Ewart <johnewart@microsoft.com>

Co-authored-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by artursouza** [comment]
Please, update the helm chart too. The auto-version of helm charts is only at 1.7 release onwards.

**Comment by johnewart** [comment]
The binary build fails on the linter; there is some really weird configuration issue going on where it appears to be trying to use go 1.18 for the linting phase and can't find any of the go libraries it expects / needs. We can either attempt to fix it (it doesn't misbehave for 1.6 or 1.7 builds) or ignore it for this branch of releases

**Comment by artursouza** [comment]
I recommend we turn off linter for 1.5 branch. @yaron2 ?

**Comment by yaron2** [comment]
> I recommend we turn off linter for 1.5 branch. @yaron2 ?

Ok with me

**Review by artursouza — APPROVED** [review]

**Pull request merged**
