### PR TITLE
Save test output as actions artifact

### PR DESCRIPTION
**Pull request by wcs1only**
# Description

Test output will now be saved as a build artifact so we can query it later.

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by wcs1only** [comment]
I forgot, there's no way to test this with /ok-to-test until after it has been merged

**Comment by wcs1only** [comment]
https://github.com/dapr/dapr/suites/2563268053/artifacts/55821004

**Comment by wcs1only** [comment]
https://github.com/dapr/dapr/suites/2563268052/artifacts/55823308

**Review by artursouza — APPROVED** [review]

**Pull request merged**
