### PR TITLE
Update error codes

### PR DESCRIPTION
**Pull request by shaggygi**
Update error codes to help better grouping based on type of error.

Closes: #835

### CODE REVIEW

**Comment by yaron2** [comment]
cc @amanbha please review and lookout for error codes that might break the SDK

**Comment by shaggygi** [comment]
> cc @amanbha please review and lookout for error codes that might break the SDK

I'm about to create a PR for the .NET SDK that go with these changes.

**Comment by shaggygi** [comment]
@amanbha I have one more change for this before possible merge.  give me a minute

**Pull request merged**
