### PR TITLE
Expand http e2e state tests to grpc

### PR DESCRIPTION
**Pull request by mukundansundar**
# Description

Replicated the HTTP test cases for gRPC.

Added checks for successful response codes. 

Negative test cases will be handled in #1810 

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1169 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by youngbupark** [comment]
I can see duplicated pkg reference. pls run this script - https://github.com/dapr/dapr/blob/master/tests/update_testapps_dependencies.sh

**Comment by mukundansundar** [comment]
> I can see duplicated pkg reference. pls run this script - https://github.com/dapr/dapr/blob/master/tests/update_testapps_dependencies.sh

done

**Review by youngbupark — APPROVED** [review]

**Pull request merged**
