### PR TITLE
Update holopin.yml to award runtime badge to contributors

### LINKED ISSUE #7684: Update the holopin.yaml to use the runtime badge
Update the `.github/holopin.yaml` file with the following info to set the default [Holopin badge](https://www.holopin.io/sticker/clrqh1xny39170fl75cawk0h5) for this repo:

```yaml
organization: dapr
defaultSticker: clrqh1xny39170fl75cawk0h5
stickers:
  -
    id: clrqh1xny39170fl75cawk0h5
    alias: runtime-badge
```

Once this is in place, maintainers can award contributors via the Holopin Bot by mentioning the contributors' username in a PR comment when the PR is accepted: `@holopin-bot @username`

---

Please label this as a __good first issue__.

### PR DESCRIPTION
**Pull request by Rutam21**
# Description

The `yaml` file to award contribution badges has been updated such that each contributor can be awarded a Runtime badge for their contribution to this repo.

## Issue reference

This PR fixes #7684 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly.
* [x] Correct and accurate change has been done as per the issue suggestion.
* [x] YAML doesn't throw any error.

### CODE REVIEW

**Comment by Rutam21** [comment]
@marcduiker Please review and suggest changes, if any. Thanks.

**Review by JoshVanL — APPROVED** [review]
Thanks!

**Review by mukundansundar — APPROVED** [review]

**Comment by Rutam21** [comment]
@yaron2 Please check if the YAML works and award me the Runtime badge for this PR 😅

**Comment by marcduiker** [comment]
@holopin-bot @Rutam21 Here you go! Thanks for contributing!

**Pull request merged**
