### PR TITLE
Add robustness to monitoring of workflow URLs.

### PR DESCRIPTION
**Pull request by philliphoff**
# Description

## Issue reference

Please reference the issue this PR will close: #7087 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
LGTM but can you rebase this on release-1.12? Since for master, the issue will be fixed by #6723

**Comment by yaron2** [comment]
I think we can do with this fix (or the other PR) for master only, not entirely sure this needs to go into a patch release as Workflows is beta and this isn't a showstopper to using the APIs

**Comment by ItalyPaleAle** [comment]
> I think we can do with this fix (or the other PR) for master only,

In master, please don't merge this as it will just cause more conflicts on #6723 which then will need to be fixed

> Workflows is beta and this isn't a showstopper to using the APIs

While that's true, it's causing daprd to panic so it could even be considered a DoS

**Comment by philliphoff** [comment]
I'll rebase it to `release-1.12`.

**Review by ItalyPaleAle — APPROVED** [review]
LGTM but it's up to the maintainers to accept this

**Review by daixiang0 — APPROVED** [review]
Approve, wait for DCO fix.

**Comment by philliphoff** [comment]
@daixiang0 I'm not sure what GH is complaining about; it's a single commit that contains the sign off (for me), as best I can tell.

**Comment by ItalyPaleAle** [comment]
@philliphoff i think this PR is in a broken state after the rebase. Could you try force-pushing your commit again?

**Comment by mukundansundar** [comment]
@philliphoff can you fix the lint error that is seen here?

**Review by artursouza — APPROVED** [review]

**Pull request merged**
