### PR TITLE
Adding Solace PubSub+ AMQP Component

### PR DESCRIPTION
**Pull request by TKTheTechie**
# Description

Adding a PubSub+ AMQP Component

## Issue reference

Please reference the issue this PR will close: https://github.com/dapr/components-contrib/pull/2383

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: https://github.com/dapr/docs/issues/3022
* [x] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: https://github.com/dapr/docs/issues/3022
* [x] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo:https://github.com/dapr/docs/issues/3022

### CODE REVIEW

**Comment by berndverst** [comment]
Please make sure to merge the latest master branch into this PR, and also import the latest commits from components-contrib via `go get github.com/dapr/components-contrib@master`. After doing so, please also run `make modtidy-all` which updates the various nested go modules' go.mod files.

**Review by berndverst — CHANGES_REQUESTED** [review]
Left some instructions in a comment for the steps required to complete this PR now.

**Comment by TKTheTechie** [comment]
> Left some instructions in a comment for the steps required to complete this PR now.

Ok, I think I did this correctly but here are the steps I took:

`go get -u github.com/dapr/components-contrib/pubsub/solace/amqp@master`

and 

`make modtidy-all`

**Comment by artursouza** [comment]
DCO is failing. Also, there are conflicts with master.

**Pull request closed without merging**
