### PR TITLE
Allow canceling recurring reminders after execution for non-internal actors

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
> Related issue: #6666

Internal actors have the ability to cancel a recurring reminder by responding to an execution with the special error [`ErrReminderCanceled`](https://github.com/dapr/dapr/blob/9e2bcdc3d8a64b02466a9274e9259f166eedc95a/pkg/actors/actors.go#L894-L898) after a reminder is executed.

However, the capability was never exposed to "external" actors.

This PR adds the ability for an actor to stop recurring reminders (and timers) after they are executed also for "external" actors. This is possible by including the header `X-DaprReminderCancel` with a truthy value in the response when a reminder or timer is executed.

This will require support in SDKs, but it allows something that is particularly helpful (and today can be buggy, as in #6666)

Integration test is included

### CODE REVIEW

**Comment by mukundansundar** [comment]
> > Related issue: #6666
> 
> Internal actors have the ability to cancel a recurring reminder by responding to an execution with the special error [`ErrReminderCanceled`](https://github.com/dapr/dapr/blob/9e2bcdc3d8a64b02466a9274e9259f166eedc95a/pkg/actors/actors.go#L894-L898) after a reminder is executed.
> 
> However, the capability was never exposed to "external" actors.
> 
> This PR adds the ability for an actor to stop recurring reminders (and timers) after they are executed also for "external" actors. This is possible by including the header `X-DaprReminderCancel` with a truthy value in the response when a reminder or timer is executed.
> 
> This will require support in SDKs, but it allows something that is particularly helpful (and today can be buggy, as in #6666)
> 
> Integration test is included

@ItalyPaleAle So in this scenario, as soon as a reminder is deregistered/unregistered, then the SDK/app sends the the specific header, that returns the response `ErrReminderCancelled`. But won't the reminder still be there in the DB to be executed again? 

Or is this a specific scenario where the app deregisters the reminder first and then sets the header? 

Finally why is an error returned in `callLocalActor`? Wouldn't that trigger the resiliency retry if present which we do not want for deregistered reminders?

**Comment by ItalyPaleAle** [comment]
> > > Related issue: #6666
> > 
> > 
> > Internal actors have the ability to cancel a recurring reminder by responding to an execution with the special error [`ErrReminderCanceled`](https://github.com/dapr/dapr/blob/9e2bcdc3d8a64b02466a9274e9259f166eedc95a/pkg/actors/actors.go#L894-L898) after a reminder is executed.
> > However, the capability was never exposed to "external" actors.
> > This PR adds the ability for an actor to stop recurring reminders (and timers) after they are executed also for "external" actors. This is possible by including the header `X-DaprReminderCancel` with a truthy value in the response when a reminder or timer is executed.
> > This will require support in SDKs, but it allows something that is particularly helpful (and today can be buggy, as in #6666)
> > Integration test is included
> 
> @ItalyPaleAle So in this scenario, as soon as a reminder is deregistered/unregistered, then the SDK/app sends the the specific header, that returns the response `ErrReminderCancelled`. But won't the reminder still be there in the DB to be executed again?
> 
> Or is this a specific scenario where the app deregisters the reminder first and then sets the header?
> 
> Finally why is an error returned in `callLocalActor`? Wouldn't that trigger the resiliency retry if present which we do not want for deregistered reminders?

It's a lot simpler than that :) The feature was already implemented and used by internal actors (and it was wired via `callLocalActor` because reminder/timer invocation still goes through the regular actor invocation paths). It allows an app to tell Dapr to stop the execution of recurring reminders (so the reminder is also removed from the DB).

A reminder is executed by Dapr sending a HTTP request to the app. The app responds and includes a status code.

What's been added now (bringing it on-par with internal actors) is that at the same time as the app responds, it can tell Dapr to stop a recurring reminder.

This can be useful in scenarios such as what #6666 tries to do, but can also be useful to implement reliable reminders which offer at-least-once delivery guarantee

**Comment by msfussell** [comment]
@ItalyPaleAle - I presume this needs a docs issue/PR, yes? If so, please create a docs PR before merging this issue.

**Comment by mukundansundar** [comment]
@ItalyPaleAle can you fix the conflicts in this PR please?

**Comment by ItalyPaleAle** [comment]
Done

**Review by yaron2 — APPROVED** [review]

**Comment by marcduiker** [comment]
@holopin-bot @ItalyPaleAle

**Pull request merged**
