### PR TITLE
Pin contrib `1.11.0-rc.2` for new stable Azure SDKs

### PR DESCRIPTION
**Pull request by berndverst**
# Description

This updates the contrib version to be used for v1.11.0 / master to 1.11.0-rc.2 which incldues only Azure SDK upgrades to upgrade to stable SDK versions for several important Azure services.

### CODE REVIEW

**Comment by berndverst** [comment]
FYI the goroutine test is flaky and doesn't report the real goroutine count. Rerunning the test produces different results.

Recently merged PRs had the same failures:
https://github.com/dapr/dapr/pull/6308/checks -- 2 more goroutines
https://github.com/dapr/dapr/pull/6321 -- 1 more goroutine
https://github.com/dapr/dapr/pull/6320 -- 1 more goroutine

**Comment by ItalyPaleAle** [comment]
This should be superseded by #6342

**Comment by berndverst** [comment]
Closing this PR now in favor of https://github.com/dapr/dapr/pull/6342

**Pull request closed without merging**
