### PR TITLE
wip:add outputbinding kitex

### PR DESCRIPTION
**Pull request by liu-song**
# Description

add outputbinding kitex

## Issue reference
https://github.com/dapr/components-contrib/pull/2563

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#3266
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by liu-song** [comment]
Kitex currently supports arm64 but not arm32. Can not pass the arm32 test ?
ci some error about arm32 
image

**Comment by daixiang0** [comment]
> To improve the performance of RPC scenarios, Kitex has made many optimizations, among which the [Netpoll](https://github.com/cloudwego/netpoll) and [Gopkg](https://github.com/bytedance/gopkg) libraries are designed for this purpose. However, these libraries currently only support the ARM64 architecture and have not yet supported the ARM32 architecture. Is it possible to skip the tests for ARM32?
> 
> image

You can skip it and point it out in the doc.

**Comment by liu-song** [comment]
https://github.com/dapr/dapr/actions/runs/4444626716 , The result of the previous test.
I suddenly realized that the reason why this test did not pass was due to the compatibility issues with Kitex, which cannot be compiled on the Linux ARM platform. We can add a build tag in this added Go file as follows:
//go:! (linux && arm)
//+build ! linux,arm"
Adopting the same format as this:https://github.com/dapr/dapr/blob/master/pkg/grpc/dial.go#L1，to allows the file to not be compiled on incompatible platforms.
@ItalyPaleAle @yaron2 @artursouza @mukundansundar 
Do you think this is acceptable or reasonable for Dapr?

**Comment by liu-song** [comment]
sorry, my mistake. I forked Dapr again, causing this branch to be lost and unable to be submitted. I will close this branch and submit a new PR.

**Pull request closed without merging**
