### PR TITLE
Update e2e test for declarative subscriptions

### LINKED ISSUE #2014: Update e2e pub/sub test for declarative subscriptions

### PR DESCRIPTION
**Pull request by yaron2**
Closes #2014

### CODE REVIEW

**Comment by yaron2** [comment]
I want to wait with merging this after @wcs1only has fixed the components loading issue.

**Comment by youngbupark** [comment]
@yaron2 we can run e2e test now and see how your test works.

**Comment by yaron2** [comment]
> @yaron2 we can run e2e test now and see how your test works.

But it might fail because of the component not being loaded, no?

**Comment by youngbupark** [comment]
> > @yaron2 we can run e2e test now and see how your test works.
> 
> But it might fail because of the component not being loaded, no?

it could be failed but not all the time ;)

**Comment by yaron2** [comment]
Also, are you sure this will pick up on the updated test and code before merging this to master?

**Review by youngbupark — APPROVED** [review]

**Pull request merged**
