### PR TITLE
Merge release-1.0 branch back to master

### PR DESCRIPTION
**Pull request by wcs1only**
# Description

Release is complete, we can merge back to master.

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by yaron2 — APPROVED** [review]
lgtm

**Comment by mukundansundar** [comment]
wait ... first update release-1.0 branch with latest commit ...

**Comment by wcs1only** [comment]
Ok, had some conflicts to resolve on go.mod go.sum. Should be sorted now.

**Review by yaron2 — APPROVED** [review]
LGTM

**Pull request merged**
