### PR TITLE
Fixes #2462:  Add components to metadata endpoint

### LINKED ISSUE #2462: Add components to metadata endpoint
Dapr exposes a `v1.0/metadata` endpoint that returns information about the sidecar, including its health and registered actors if present.

To allow runtime discoverability of the different components loaded in the Dapr sidecar and their types and versions, we want to add a section to the response object returned by the endpoint:

```json
{
  "components": [
   {
      "name": "redis-prod",
      "type": "state.redis",
      "version": "v2"
   },
  {
      "name": "redis-test",
      "type": "state.redis",
      "version": "v3"
   }
]
}
```

### PR DESCRIPTION
**Pull request by juazasan**
# Description

Dapr exposes a v1.0/metadata endpoint that returns information about the sidecar, including its health and registered actors if present.

To allow runtime discoverability of the different components loaded in the Dapr sidecar and their types and versions, this PR adds a section to the response object returned by the endpoint:

{
  "components": [
   {
      "name": "redis-prod",
      "type": "state.redis",
      "version": "v2"
   },
  {
      "name": "redis-test",
      "type": "state.redis",
      "version": "v3"
   }
]
}

## Issue reference
closes #2462

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Unit tests passing
* [X] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks so much for this PR!

**Comment by juazasan** [comment]
Hi @yaron2  Wondering if you could please advise on how to move forward with the PR. Some checks are not passing but not sure they are really due to the code changes I am submitting. On the other hand, do I need to update the docs (current metadata endpoint does not seem to be documented ether) and add e2e tests (was not able to find an e2e test which I could extend). Thanks.

**Comment by yaron2** [comment]
> Hi @yaron2 Wondering if you could please advise on how to move forward with the PR. Some checks are not passing but not sure they are really due to the code changes I am submitting. On the other hand, do I need to update the docs (current metadata endpoint does not seem to be documented ether) and add e2e tests (was not able to find an e2e test which I could extend)? Thanks.

No need to add e2e for this now. I'll re-run the tests for this. If you are done with your changes, please remove the WIP from the title and we can move forward with a review.

I will open a separate issue on docs for the metadata endpoint.

**Comment by yaron2** [comment]
@juazasan there's already a docs issue for the metadata endpoint. If you can take this up, it'd be grand. if you want to get assigned, please comment on the issue with "/assign". https://github.com/dapr/docs/issues/825

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
