### PR TITLE
Remove pluggable component CRD

### PR DESCRIPTION
**Pull request by mcandeia**
Signed-off-by: Marcos Candeia <marrcooos@gmail.com>

# Description

1) Removes pluggable component CRD
2) Use component CRD as inline pluggable component
3) Remove pluggable components feature flag as we are expecting a socket to be created instead

## Issue reference

Please reference the issue this PR will close: #5210 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by mcandeia** [comment]
FeatureFlag check still missing. The rest is ready for review.

**Comment by mcandeia** [comment]
@yaron2 @artursouza I think it's ready for review

**Review by artursouza — APPROVED** [review]
Wow! Removing code. Love it.

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
