### PR TITLE
Adding daprHTTPMaxRequestSize argument to the dapr runtime, cli and sidecar

### PR DESCRIPTION
**Pull request by apuzyrevsky**
# Description

Adding daprHTTPMaxRequestSize flag to the cli and dapr-http-max-request-size argument to dapr solution to define custom fasthttp server MaxRequestBodySize parameter to handle uploading of big files.

## Issue reference

 #2659 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#1099
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@apuzyrevsky are there any other changes you expect to commit?

**Review by pkedy — APPROVED** [review]
LGTM

I'm unsure how valuable this flag would be in the CLI but I thought I would mention that this could be added here and passed through to daprd.

https://github.com/dapr/cli/blob/master/cmd/run.go#L230-L244

Unrelated to this PR (and total nit) is to consider changing `ServerConfig{}` in `pkg/http/server_test.go` and `pkg/grpc/server_test.go` to use `NewServerConfig(...)` so that there are no places in the code where a zero value occurs for `MaxRequestBodySize` resulting in `s.config.MaxRequestBodySize*1024*1024` being 0. I'm not sure how fasthttp and go-grpc treat that and in all likelihood it could be OK.

**Comment by yaron2** [comment]
@apuzyrevsky can you kindly open a docs PR that adds the new annotation? https://github.com/dapr/docs/blob/4671e66736cbe3c527e57fe097baa4b197f32ae6/daprdocs/content/en/operations/hosting/kubernetes/kubernetes-annotations.md

open it against the 1.0.0-rc.3 branch.
Thanks!

And thanks @pkedy for reviewing

**Comment by apuzyrevsky** [comment]
@yaron2 I won't add anything else to that request. And here is a PR for annotation https://github.com/dapr/docs/pull/1104

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
thanks for this @apuzyrevsky

**Pull request merged**
