### PR TITLE
Add negative e2e tests for workflowbackend

### PR DESCRIPTION
**Pull request by ASHIQUEMD**
# Description

This PR adds negative e2e tests for workflow backend
1. More than one workflow backend components should result in dapr error
2. For invalid workflow backend type, dapr should result in error

This PR is also fixing sqlite backend perf test.

### CODE REVIEW

**Review by mukundansundar — APPROVED** [review]
ITs can be followed up later on to validate Standalone behaviour as well ...

**Comment by daixiang0** [comment]
ping @ASHIQUEMD

**Pull request closed without merging**
