### PR TITLE
#2495. PublishRequest and SubscriberRequest need metadata.

### PR DESCRIPTION
**Pull request by cvictory**
# Description

PublishRequest and SubscriberRequest need metadata.  
Please ignore go.mod/go.sum, them should be modified after components-contrib been released.

## Issue reference

https://github.com/dapr/dapr/issues/2495

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by cvictory** [comment]
@yaron2 @jjcollinge  
please check this pr.  after this pr merged, I will start to update the sdk.

**Comment by cvictory** [comment]
I found that some method is added into StateStore and some test failed.

**Comment by yaron2** [comment]
> I found that some method is added into StateStore and some test failed.

Yes, your PR needs to wait for https://github.com/dapr/dapr/pull/2467

**Comment by yaron2** [comment]
@cvictory please resolve the conflicts so we can move forward, thanks!

**Comment by cvictory** [comment]
> @cvictory please resolve the conflicts so we can move forward, thanks!

Done

**Comment by yaron2** [comment]
@cvictory now that we merged your other PR there are conflicts again here need resolving.

**Comment by cvictory** [comment]
> @cvictory now that we merged your other PR there are conflicts again here need resolving.

please merge as soon as possible.  I have merged 3 times for conflict.

**Review by yaron2 — DISMISSED** [review]

**Comment by cvictory** [comment]
> @cvictory now that we merged your other PR there are conflicts again here need resolving.

can you merge this pr?

**Comment by cvictory** [comment]
@cvictory @patrickdevivo could you merge this pr ?

**Comment by cvictory** [comment]
@youngbupark  can you merge this pr ?

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
