### PR TITLE
Add dapr sidecar as first container in pod

### PR DESCRIPTION
**Pull request by yaron2**
Helping with issue https://github.com/dapr/dapr/issues/2007

Now that the sidecar KEP in Kubernetes has been postponed indefinitely, we need to help increase the chances for the Dapr sidecar to start initializing before the app.

As it turn out, Kubernetes does start containers sequentially when operating on the list of containers in the pod spec.
This PR makes sure the Dapr container is placed first so Kubernetes will attempt to schedule the Dapr container lifecycle first.

This doesn't guarantee that Dapr will always start first, as the container lifecycle happens in parallel and the pulling and starting of the containers happen together, but it reduces the chance for the application to try reaching an unavailable sidecar.

### CODE REVIEW

**Review by youngbupark — APPROVED** [review]

**Comment by youngbupark** [comment]
@yaron2 all e2e KinD test are failing.

**Review by youngbupark — CHANGES_REQUESTED** [review]
Please see e2e test. it is failing now. with this change.

**Comment by yaron2** [comment]
> Please see e2e test. it is failing now. with this change.

Yeah I see what the issue is.. on it.

**Comment by yaron2** [comment]
I'm closing this for now, will re-open once I have a viable solution.

**Comment by skyao** [comment]
@yaron2 hi, yaron, I need this PR for dapr lifecycle management improvement, daprd should be the first container and block other container by k8s prestart script.

**Pull request closed without merging**
