### PR TITLE
fix: InvokeMethod parse uri query

### PR DESCRIPTION
**Pull request by rrylee**
# Description

go-sdk provider all method about invoke service not support set querystring，so dapr need to support parse query in method(url).

## Issue reference

https://github.com/dapr/dapr/issues/2572

## Checklist

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
Hey @rrylee, help me understand the change here: Dapr today sets the query string on the URI sent to the app. Isn't what you're doing here a duplicate with `channelReq.URI().SetQueryString(req.EncodeHTTPQueryString())`?

**Comment by rrylee** [comment]
> Hey @rrylee, help me understand the change here: Dapr today sets the query string on the URI sent to the app. Isn't what you're doing here a duplicate with `channelReq.URI().SetQueryString(req.EncodeHTTPQueryString())`?

if you check the code of dapr/go-sdk, you will found can not set queryString when call Invoke，just like the following.

```
content := &dapr.DataContent{}
client.InvokeMethodWithContent(context.Background(), "app", "method?foo=bar", "get", content)
```

So i think maybe we could solve is on dapr. this have more compatibility but not enough suitable

**Comment by yaron2** [comment]
> > Hey @rrylee, help me understand the change here: Dapr today sets the query string on the URI sent to the app. Isn't what you're doing here a duplicate with `channelReq.URI().SetQueryString(req.EncodeHTTPQueryString())`?
> 
> if you check the code of dapr/go-sdk, you will found can not set queryString when call Invoke，just like the following.
> 
> ```
> content := &dapr.DataContent{}
> client.InvokeMethodWithContent(context.Background(), "app", "method?foo=bar", "get", content)
> ```
> 
> So i think maybe we could solve is on dapr. this have more compatibility but not enough suitable

So this should actually work. Let me test with the Go SDK and report back.

**Comment by rrylee** [comment]
sure, direct curl v1.0/invoke/... api work great.

**Pull request closed without merging**
