### PR TITLE
 Correct use of go get and go install in Makefile

### LINKED ISSUE #3860: Correct use of go get and go install in Makefile
## In what area(s)?

> /area test-and-release

## Describe the feature
Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.
We should change the installation of `protoc-gen-go` and `protoc-gen-go-grpc` to `go install`.
If you find that there are other changes that need to be made together, you can raise them below.

Quote：https://golang.org/doc/go-get-install-deprecation

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by CrazyHZM**
# Description
Change the installation of `protoc-gen-go` and `protoc-gen-go-grpc` to `go install`.

## Issue reference

Fix #3860

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by daixiang0 — COMMENTED** [review]
I am curious does it work for 1.16? Do we need a doc to comment to lowest support GO version? 

/cc @artursouza

**Comment by CrazyHZM** [comment]
> I am also seeing some other places where go get is used ... eg: https://github.com/dapr/dapr/blob/master/tests/dapr_tests.mk#L201

Done.

**Comment by yaron2** [comment]
@CrazyHZM please resolve conflicts.

**Comment by CrazyHZM** [comment]
> @CrazyHZM please resolve conflicts.

Done.

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
@CrazyHZM Please, commit with `-s` to pass DCO.

**Comment by CrazyHZM** [comment]
@artursouza 
Because there are several commits that take too long, the rebase operation to solve the singoff will cause the PR to be not clean enough, I re-submitted the PR:
https://github.com/dapr/dapr/pull/4099

**Pull request closed without merging**
