### PR TITLE
Hot Reloading: don't watch files if not enabled

### PR DESCRIPTION
**Pull request by JoshVanL**
Update hot reloading so that we don't setup file watchers on the component directory if hot reloading is not enabled.

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]

**Review by berndverst — APPROVED** [review]

**Comment by berndverst** [comment]
Should we cherry pick this into 1.13 @JoshVanL ?

**Review by artursouza — CHANGES_REQUESTED** [review]
Please, apply to release-1.13

**Comment by artursouza** [comment]
> Should we cherry pick this into 1.13 @JoshVanL ?

We are not cherry-picking into 1.13 yet since it is an on-going release. We should apply this to 1.13 first and master will have it once we merge from release-1.13 into master.

**Comment by artursouza** [comment]
This reduced the number of go routines (see standalone validation):

```
Mean for number of go routines (new): 33.33
25th percentile for number of go routines (new): 33.00
50th percentile (median) for number of go routines (new): 33.00
75th percentile for number of go routines (new): 34.00
Mean for number of go routines (old): 37.30
25th percentile for number of go routines (old): 37.00
50th percentile (median) for number of go routines (old): 37.00
75th percentile for number of go routines (old): 38.00
T-Statistic (number of go routines): -19.1616[27](https://github.com/dapr/dapr/actions/runs/7845911033/job/21411402002?pr=7521#step:10:28)07114691
P-Value (number of go routines): 1.0
Passed! Did not find statistically significant increase in number of go routines.
``

**Comment by JoshVanL** [comment]
Thanks @berndverst @artursouza! Oversight on my part- I've changed the merge base.

Looking at the disk reconciler loader more closely I don't like the fact we are setting up long running routines on `New` at all anyway, and it is not great we are doing a "hacky" nil check on the receiver. Please see the changes removing `Close` in favor of `Run`.

**Comment by JoshVanL** [comment]
@artursouza resolved conflicts.

**Pull request merged**
