### PR TITLE
Send flag for last subscription topic

### PR DESCRIPTION
**Pull request by DeepanshuA**
Signed-off-by: Deepanshu Agarwal <deepanshu.agarwal1984@gmail.com>

# Description

While analysing https://github.com/dapr/components-contrib/issues/2306, realized that there may be cases when a component wants to subscribe topics from broker at one go. For this, runtime should enable component with knowledge whether the current topic for which `Subscribe` is called is last topic in current list or not.

Ref: https://github.com/dapr/components-contrib/issues/2306#issuecomment-1328605232

## Issue reference

Please reference the issue this PR is related to: #5571  and https://github.com/dapr/components-contrib/issues/2306

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by DeepanshuA** [comment]
> Overall LGTM but I wonder how this will interact with dynamic subscriptions and if it may be a problem See #5031

Sorry, coming back to it after couple of weeks, as I was trying to close some other items meanwhile.

I just went through the Dynamic loading issue and solution that you have proposed for it.

As far as I understand, that there are two types of component SDKs out there, which allow us two kind of subscription mechanisms:
1. which can Subscribe individually for each new topic 
2. which needs to keep a list of subscription, revoke old connection and invoke new connection with new list of topics.

For, 1st case, we need not bother and whatever flag this change is talking about, doesn't bother them.

For 2nd:
I feel with current approach, we would need to tell with each Dynamic Subscription that this is the topic which needs to be added and with each new topic addition/deletion, we need to re-connect. So, with each Dynamic Subscription we would need to send this `lastSubscriptionTopic`. But, this seems overhead.
Instead, it would be better if runtime just informs the component that it is a non-terminal topic subscription via metadata, then component can take a decision whether to use this metadata or not. And, for any other usecase like Dynamic, we need to not send any flag.

Hence, I am changing the flag from `lastSubscriptionTopic` and being sent with LAST topic of topics list
TO
`nonTerminalSubscriptionTopic` and being sent with each topic BUT last.
And, we need not send anything for Dynamic case.

cc @ItalyPaleAle

**Comment by ItalyPaleAle** [comment]
Note that with the last changes to MQTT, the component maintain a single connection

**Comment by mukundansundar** [comment]
@DeepanshuA is this PR still needed?

**Comment by DeepanshuA** [comment]
> @DeepanshuA is this PR still needed?

I will check and get back on this.

**Pull request closed without merging**
