### PR TITLE
remove duplicate and error code.

### PR DESCRIPTION
**Pull request by johncming**
fix typo.

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks for this @johncming, but this behavior is desired. it's using the check-lock-check paradigm to make sure that a connection for a given address gets set-up once.

It first checks if the connection is already there. if it is, it returns it and exits.
if its not, it locks. 2 or more requests might be waiting, but only one should go in and create the connection. once the lock is freed, the remaining requests will again check if the connection is there, and will exit if it is.

As such, I will close this PR, but thanks again for your willingness to contribute to Dapr, this is highly appreciated.

**Comment by johncming** [comment]
@yaron2 

But question is that he first check is not concurrency safe in go env which leads to an error.

How to resolve the unsafe case.

Thanks

**Comment by yaron2** [comment]
> @yaron2
> 
> But question is that the first check is not concurrency safe in go env which leads to an error.
> 
> How to resolve the unsafe case.
> 
> Thanks

So that's a different issue. The solution here would be to turn the lock into an RWMutex, and RLock/RUnlock for the first check.

**Comment by johncming** [comment]
> > @yaron2
> > But question is that the first check is not concurrency safe in go env which leads to an error.
> > How to resolve the unsafe case.
> > Thanks
> 
> So that's a different issue. The solution here would be to turn the lock into an RWMutex, and RLock/RUnlock for the first check.

OK. If it needs to be modified, I can do it.

**Comment by yaron2** [comment]
Yes, if you can please open a new PR for that. Thanks!

**Comment by johncming** [comment]
> Yes, if you can please open a new PR for that. Thanks!

@yaron2 

Read-write locks may not be required, because of the field to protect is `connectionPool`

```go
type Manager struct {
	AppClient      *grpc.ClientConn
	lock           *sync.Mutex
	connectionPool map[string]*grpc.ClientConn
	auth           security.Authenticator
}
```

The longer operation is that create a new connection if not exists

```go
	if !skipTLS && g.auth != nil {
		signedCert := g.auth.GetCurrentSignedCert()
		cert, err := tls.X509KeyPair(signedCert.WorkloadCert, signedCert.PrivateKeyPem)
		if err != nil {
			return nil, fmt.Errorf("error generating x509 Key Pair: %s", err)
		}

		ta := credentials.NewTLS(&tls.Config{
			ServerName:   id,
			Certificates: []tls.Certificate{cert},
			RootCAs:      signedCert.TrustChain,
		})
		opts = append(opts, grpc.WithTransportCredentials(ta))
	} else {
		opts = append(opts, grpc.WithInsecure())
	}
```

So make the following changes
```go
func (g *Manager) GetGRPCConnection(address, id string, skipTLS, recreateIfExists bool) (*grpc.ClientConn, error) {
	g.lock.Lock()
	if val, ok := g.connectionPool[address]; ok && !recreateIfExists {
		g.lock.Unlock()
		return val, nil
	}

	opts := []grpc.DialOption{
		grpc.WithBlock(),
	}
	if !skipTLS && g.auth != nil {
		signedCert := g.auth.GetCurrentSignedCert()
		cert, err := tls.X509KeyPair(signedCert.WorkloadCert, signedCert.PrivateKeyPem)
		if err != nil {
			return nil, fmt.Errorf("error generating x509 Key Pair: %s", err)
		}

		ta := credentials.NewTLS(&tls.Config{
			ServerName:   id,
			Certificates: []tls.Certificate{cert},
			RootCAs:      signedCert.TrustChain,
		})
		opts = append(opts, grpc.WithTransportCredentials(ta))
	} else {
		opts = append(opts, grpc.WithInsecure())
	}

	conn, err := grpc.Dial(address, opts...)
	if err != nil {
		return nil, err
	}

         g.lock.Lock()
	g.connectionPool[address] = conn
	g.lock.Unlock()

	return conn, nil
}
```

**Pull request closed without merging**
