### PR TITLE
Use revive instead of golint

### PR DESCRIPTION
**Pull request by pigletfly**
Signed-off-by: pigletfly <wangbing.adam@gmail.com>

# Description

## Issue reference

part of https://github.com/dapr/components-contrib/issues/1687

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
cc @artursouza

**Comment by artursouza** [comment]
I saw this PR before. What is the advantage of revive over golint?

**Comment by yaron2** [comment]
> dapr/components-contrib#1687

It appears that golint is deprecated. @shubham1172 seems to have replaced it in the CLI: https://github.com/dapr/cli/issues/960.

**Comment by yaron2** [comment]
@pigletfly please see there's one test that's failing: https://github.com/dapr/dapr/runs/6236197796?check_suite_focus=true.

**Comment by ItalyPaleAle** [comment]
Took a review since I have a vested interest in this PR now :)

Looks like the issue is caused by this change here: https://github.com/dapr/dapr/pull/4555/files#diff-30164ead47f86ee4b8e0c078aa25c30a60a6f241ee7d0f19ac778eb360854879R23

Before, in case there was an error importing the TLS certificate, it would just return `nil` as error and essentially not use TLS. This is what the tests are asserting too: https://github.com/dapr/dapr/blob/master/pkg/credentials/grpc_test.go#L21

Now, probably because of the linter's own complaining, an error is returned instead.

Was the previous behavior on purpose or accidental? If TLS certs are invalid, do we want to return an error or silently ignore the failure and proceed without TLS?

CC: @pigletfly @yaron2

**Comment by yaron2** [comment]
> https://github.com/dapr/dapr/pull/4555/files#diff-30164ead47f86ee4b8e0c078aa25c30a60a6f241ee7d0f19ac778eb360854879R23

Accidental.

**Comment by ItalyPaleAle** [comment]
Thanks for confirming.

I've opened a PR against @pigletfly 's PR: https://github.com/pigletfly/dapr/pull/1 I think you _may_ have permissions to merge it yourself since you're a maintainer here, otherwise we'll just wait for @pigletfly to be back :)

**Comment by pigletfly** [comment]
@ItalyPaleAle thank you for your review, I'm back from vacation.

**Comment by ItalyPaleAle** [comment]
@pigletfly Welcome back :) Not sure what happened but the Git history got messed up and the error is back.

I've updated https://github.com/pigletfly/dapr/pull/1/ and this should fix the test failures

**Comment by artursouza** [comment]
I have merged @ItalyPaleAle's PR already.

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
No need to assign PRs. The author is given credit as per the release notes script.

**Pull request merged**
