### PR TITLE
Revert "Convert Dapr middlewares and HTTP channel from fasthttp to net/http"

### PR DESCRIPTION
**Pull request by yaron2**
Reverts dapr/dapr#5316

### CODE REVIEW

**Review by artursouza — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
I will work on exploring how to optimize this. We cannot continue using fasthttp so sooner or later this change needs to happen...

**Comment by yaron2** [comment]
> I will work on exploring how to optimize this. We cannot continue using fasthttp so sooner or later this change needs to happen...

We can, and will continue using fasthttp for as long as we cannot guarantee at the very least an acceptable level of performance degredation with net/http. The current regression is extremely high, to be honest I was surprised by how severe it was and am hoping there's a low hanging fruit there that might explain this.

**Comment by yaron2** [comment]
Verified regression in gone in all latest perf runs for the affected test.

**Pull request merged**
