### PR TITLE
deps: updates to latest components-contrib

### PR DESCRIPTION
**Pull request by codefromthecrypt**
# Description

updates to latest components-contrib

This supports the renovated wasm middleware, making it easier to build a sample for it. https://github.com/dapr/docs/issues/2789

## Issue reference

https://github.com/dapr/components-contrib/pull/1833

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Unit tests passing
* [x] End-to-end tests passing

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
cc @daixiang0

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
It fails lint.

**Comment by codefromthecrypt** [comment]
ok yeah looks like there is drift in the secret stores API. I'll sort it

**Comment by codefromthecrypt** [comment]
ok 🤞 I got all the drift

**Comment by daixiang0** [comment]
@codefromthecrypt please fix CI.

**Comment by codefromthecrypt** [comment]
sure will.

PS I feel like it would be less bombs for newcomers like me if things were updated more often. I'm both ok with fixing all this unrelated drift, and capable of doing it. That said, not everyone will be able to get through all the hoops. I think if the project generally merged things in more often, the burden would be less.

**Comment by codefromthecrypt** [comment]
unsolicited 2p on a way out is that when folks make breaking changes to contrib, they immediately raise a PR here and address them. This keeps the blast radius down

**Comment by codefromthecrypt** [comment]
ok fixed the other drifts 🤞 this passes and merges before there are more

**Comment by daixiang0** [comment]
> sure will.
> 
> PS I feel like it would be less bombs for newcomers like me if things were updated more often. I'm both ok with fixing all this unrelated drift, and capable of doing it. That said, not everyone will be able to get through all the hoops. I think if the project generally merged things in more often, the burden would be less.

I think some authors of component-contrib PRs do not sync here, so you have to do some fixes, thanks!

**Comment by codefromthecrypt** [comment]
@daixiang0 another lint. a little silly to worry about allocation in test but anyway fixed. you may have to re-kick

**Comment by codefromthecrypt** [comment]
would appreciate if someone with a fast windows host can look into the failure. mine is underpowered and will be hours before it does anything. feel free to push a commit.

**Comment by daixiang0** [comment]
I have no access to it, so open a new one #5203.

**Comment by codefromthecrypt** [comment]
obviated by #5203

**Pull request closed without merging**
