### PR TITLE
Reuse ASB namespace for E2E tests.

### PR DESCRIPTION
**Pull request by artursouza**
# Description

Reuse ASB namespace for E2E tests.

## Issue reference

Please reference the issue this PR will close: #3647 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by CrazyHZM — DISMISSED** [review]
LGTM

**Comment by artursouza** [comment]
Latest failure is:

```txt
time="2021-11-04T08:02:14.862629953Z" level=error msg="azure service bus error: error handling message dc618e38-e0f3-4763-8b9f-03c4e8b9f55e on topic 'pubsub-c-topic-http', failed to complete: *Error{Condition: com.microsoft:server-busy, Description: The request was terminated because the namespace dapr-aks-e2e-07 is being throttled. Error code : 50009. Please wait 2 seconds and try again. To know more visit https://aka.ms/sbResourceMgrExceptions TrackingId:f2f83d6400087e6d026225fd618392b7_G60_B12, SystemTracker:dapr-aks-e2e-07:Topic:pubsub-c-topic-http|pubsub-publisher-grpc, Timestamp:2021-11-04T08:02:14, Info: map[]}" app_id=pubsub-publisher-grpc instance=pubsub-publisher-grpc-5c856fdc44-d2rr9 scope=dapr.contrib type=log ver=edge
```

**Review by yaron2 — APPROVED** [review]
lgtm

**Pull request merged**
