### PR TITLE
Add ctx in bindings

### PR DESCRIPTION
**Pull request by pigletfly**
Signed-off-by: pigletfly <wangbing.adam@gmail.com>

# Description

add context.Context in bindings

## Issue reference
https://github.com/dapr/dapr/issues/2716

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [x] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by berndverst** [comment]
Once https://github.com/dapr/components-contrib/pull/1681 is merged please update this PR with a commit to pull in the latest contrib -- `go get github.com/dapr/components-contrib@master`

**Comment by pigletfly** [comment]
> Once [dapr/components-contrib#1681](https://github.com/dapr/components-contrib/pull/1681) is merged please update this PR with a commit to pull in the latest contrib -- `go get github.com/dapr/components-contrib@master`

ok

**Comment by berndverst** [comment]
I think the following lines need to be updated:

`func (b *mockBinding) Read(handler func(*bindings.ReadResponse) ([]byte, error)) error {`

should be

`func (b *mockBinding) Read(handler func(context.Context, *bindings.ReadResponse) ([]byte, error)) error {`

https://github.com/dapr/dapr/blob/aa6a9092e67bf50ca921a4f443e00e9afa468b04/pkg/runtime/runtime_test.go#L2977

and

`func (m *MockBinding) Read(handler func(*bindings.ReadResponse) ([]byte, error)) error {`

should be

`func (m *MockBinding) Read(handler func(context.Context *bindings.ReadResponse) ([]byte, error)) error {`

https://github.com/dapr/dapr/blob/4b920e3a69cc92b26b998e6ea267f73ac8faf64d/pkg/testing/bindings_mock.go#L20

**Comment by berndverst** [comment]
Same thing for invoke actually:

https://github.com/dapr/dapr/blob/4b920e3a69cc92b26b998e6ea267f73ac8faf64d/pkg/testing/bindings_mock.go#L26

https://github.com/dapr/dapr/blob/aa6a9092e67bf50ca921a4f443e00e9afa468b04/pkg/runtime/runtime_test.go#L2996

**Comment by berndverst** [comment]
@artursouza the error looks like it's in `runtime.go` but that's actually because the `runtime_test.go` is calling the real runtime with the wrong signature.

**Comment by pigletfly** [comment]
> I think the following lines need to be updated:
> 
> `func (b *mockBinding) Read(handler func(*bindings.ReadResponse) ([]byte, error)) error {`
> 
> should be
> 
> `func (b *mockBinding) Read(handler func(context.Context, *bindings.ReadResponse) ([]byte, error)) error {`
> 
> https://github.com/dapr/dapr/blob/aa6a9092e67bf50ca921a4f443e00e9afa468b04/pkg/runtime/runtime_test.go#L2977
> 
> and
> 
> `func (m *MockBinding) Read(handler func(*bindings.ReadResponse) ([]byte, error)) error {`
> 
> should be
> 
> `func (m *MockBinding) Read(handler func(context.Context, *bindings.ReadResponse) ([]byte, error)) error {`
> 
> https://github.com/dapr/dapr/blob/4b920e3a69cc92b26b998e6ea267f73ac8faf64d/pkg/testing/bindings_mock.go#L20

gotcha

**Comment by pigletfly** [comment]
after https://github.com/dapr/components-contrib/pull/1688 is merged, I will update go.mod again

**Comment by berndverst** [comment]
@pigletfly I asked @artursouza to merge the other PR for me (to overwrite failing tests again) and then to update this PR here.

So it is up to date now. Hopefully everything passes.

**Review by berndverst — APPROVED** [review]
LGTM

**Comment by berndverst** [comment]
@pigletfly why did you update this again? It was already done as I said! Now we have to run these very slow tests again... and I cannot trigger them :(

**Comment by berndverst** [comment]
@pigletfly you forgot to run `go mod tidy`. Please run that and commit the change.

Then ask @mukundansundar or @daixiang0 to run this test again.

**Comment by pigletfly** [comment]
> @pigletfly why did you update this again? It was already done as I said. Now we unfortunately have to run these very slow tests again... and I cannot trigger the tests because I'm not a maintainer in dapr/dapr. -- The PR was already ready to be merged because Artur updated it. Maintainers can update PRs.
> 
> Please ask @daixiang0 to trigger this test again so we can merge this very quickly.
rebased from upstream/master

**Comment by pigletfly** [comment]
@mukundansundar @daixiang0 we are ready to go

**Comment by daixiang0** [comment]
I have re-run failed jobs by hand :)

**Review by daixiang0 — APPROVED** [review]

**Comment by daixiang0** [comment]
@pigletfly thanks for your contribution!

**Pull request merged**
