### PR TITLE
Patch release 1.10.6

### PR DESCRIPTION
**Pull request by artursouza**
# Description

Merging fixes into release branch first:
https://github.com/dapr/dapr/pull/6277
https://github.com/dapr/dapr/pull/6270

## Issue reference

Fixes https://github.com/dapr/dapr/issues/6268
Fixes https://github.com/dapr/go-sdk/issues/390
Fixes https://github.com/dapr/components-contrib/issues/2786

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by artursouza** [comment]
I am working on the release notes.

**Comment by artursouza** [comment]
> I am working on the release notes.

Done.

**Review by berndverst — APPROVED** [review]

**Comment by artursouza** [comment]
> /ok-to-test

It does not work. It seems to be some incompatibility with the master version.

**Comment by mukundansundar** [comment]
> # Dapr E2E test
> 🔗 **[Link to Action run](https://github.com/dapr/dapr/actions/runs/4793081997)**
> 
> Commit ref: [5fb0406](https://github.com/dapr/dapr/commit/5fb0406ba2c6139bd8372650034874a48bf64fa3)
> 
> ## ❌ Infrastructure deployment failed
> Cluster	Resource group name	Azure region
> Linux	`Dapr-E2E-dapre2eddaa08ba22l`	westus3
> Windows	`Dapr-E2E-dapre2eddaa08ba22w`	westus3
> Linux/arm64	`Dapr-E2E-dapre2eddaa08ba22la`	eastus
> Please check the logs for details on the failure.
> 
> ## ❌ Build failed for linux/arm64
> Please check the logs for details on the error.
> 
> ## ❌ Build failed for linux/amd64
> Please check the logs for details on the error.
> 
> ## ❌ Build failed for windows/amd64
> Please check the logs for details on the error.

first the k8s version that this is trying to deploy is no longer available. That is why infra deployment fails.

**Pull request merged**
