### PR TITLE
Daprd router normalize only seperator - release-1.10

### PR DESCRIPTION
**Pull request by JoshVanL**
See https://github.com/dapr/dapr/pull/6430

/assign @ItalyPaleAle

### CODE REVIEW

**Review by artursouza — COMMENTED** [review]
Please, add release notes for the hotfix.

**Comment by berndverst** [comment]
@JoshVanL can you please also update contrib in this PR?
github.com/dapr/components-contrib@v1.10.7

That contrib updates include two cherry-picks that need to go into the 1.10.7 release:
https://github.com/dapr/components-contrib/pull/2881

- [MongoDB state store] Fixes an issue retrieving / deserializing Actor Reminder Data
- [Azure ServiceBus PubSub] Now returns an error if delayed message scheduling metadata was provided in wrong time format.

**Comment by JoshVanL** [comment]
@berndverst done :+1:

**Comment by berndverst** [comment]
@JoshVanL cut a new contrib 1.10 release to include your memcache `ttlInSeconds` fix also.

Can you update to:
`github.com/dapr/components-contrib@v1.10.8`

And `make modtidy-all`

Thanks!

**Comment by JoshVanL** [comment]
@berndverst done! :slightly_smiling_face:

**Comment by mukundansundar** [comment]
> de two cherry-picks that need to go into the 1.10.7 release: [dapr/components-contrib#2881](https://github.com/dapr/components-contrib/pull/2881)
> 
> * [MongoDB state store] Fixes an issue retrieving / deserializing Actor Reminder Data
> * [Azure ServiceBus PubSub] Now returns an error if delayed message scheduling metadata was provided in wrong time format.

Please add these to the release notes also.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
