### PR TITLE
House cleaning: Move grpc, http, and universal under `pkg/api`. Make Universal immutable.

### PR DESCRIPTION
**Pull request by JoshVanL**
General house cleaning PR to move the `grpc`, `http` and `universal` packages under `pkg/api`.

Makes the shared universal object immutable by callers.

Based on https://github.com/ItalyPaleAle/dapr/pull/97

### CODE REVIEW

**Comment by daixiang0** [comment]
@JoshVanL please fix conflicts and make CI happy, then we can merge it.

**Comment by JoshVanL** [comment]
@daixiang0 done! Please take  look

**Comment by cicoyle** [comment]
I think the file structure is more explicit and helpful now. Thanks for moving it all around 👍🏻

**Review by cicoyle — DISMISSED** [review]

**Comment by yaron2** [comment]
@JoshVanL please resolve the conflicts

**Comment by JoshVanL** [comment]
@yaron Done.

**Review by elena-kolevska — APPROVED** [review]

**Review by yaron2 — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
Note this PR broke the builds with the `subtlecrypto` tag:

```
pkg/api/universal/subtlecrypto_subtlecrypto.go:50:5: a.Logger undefined (type *Universal has no field or method Logger, but does have logger)
pkg/api/universal/subtlecrypto_subtlecrypto.go:56:16: a.Resiliency.ComponentOutboundPolicy undefined (type func() "github.com/dapr/dapr/pkg/resiliency".Provider has no field or method ComponentOutboundPolicy)
pkg/api/universal/subtlecrypto_subtlecrypto.go:68:5: a.Logger undefined (type *Universal has no field or method Logger, but does have logger)
pkg/api/universal/subtlecrypto_subtlecrypto.go:94:6: a.Logger undefined (type *Universal has no field or method Logger, but does have logger)
pkg/api/universal/subtlecrypto_subtlecrypto.go:101:6: a.Logger undefined (type *Universal has no field or method Logger, but does have logger)
pkg/api/universal/subtlecrypto_subtlecrypto.go:114:6: a.Logger undefined (type *Universal has no field or method Logger, but does have logger)
pkg/api/universal/subtlecrypto_subtlecrypto.go:138:16: a.Resiliency.ComponentOutboundPolicy undefined (type func() "github.com/dapr/dapr/pkg/resiliency".Provider has no field or method ComponentOutboundPolicy)
pkg/api/universal/subtlecrypto_subtlecrypto.go:152:5: a.Logger undefined (type *Universal has no field or method Logger, but does have logger)
pkg/api/universal/subtlecrypto_subtlecrypto.go:171:16: a.Resiliency.ComponentOutboundPolicy undefined (type func() "github.com/dapr/dapr/pkg/resiliency".Provider has no field or method ComponentOutboundPolicy)
pkg/api/universal/subtlecrypto_subtlecrypto.go:184:5: a.Logger undefined (type *Universal has no field or method Logger, but does have logger)
pkg/api/universal/subtlecrypto_subtlecrypto.go:184:5: too many errors
```

**Pull request merged**
