### PR TITLE
optimize(components): use IsInitialVersion method

### PR DESCRIPTION
**Pull request by 1046102779**

### CODE REVIEW

**Review by FREELANCEGITIT — APPROVED** [review]

**Review by FREELANCEGITIT — APPROVED** [review]

**Review by FREELANCEGITIT — APPROVED** [review]

**Review by FREELANCEGITIT — APPROVED** [review]

**Review by FREELANCEGITIT — APPROVED** [review]
Tu

**Review by FREELANCEGITIT — COMMENTED** [review]
Thank goodness

**Review by FREELANCEGITIT — APPROVED** [review]

**Review by FREELANCEGITIT — APPROVED** [review]

**Comment by yaron2** [comment]
> Thank goodness

Hi, why do you keep approving this PR?

**Review by FREELANCEGITIT — APPROVED** [review]

**Review by FREELANCEGITIT — APPROVED** [review]

**Comment by artursouza** [comment]
> > Thank goodness
> 
> Hi, why do you keep approving this PR?

Can this be merged, @yaron2 ?

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
