### PR TITLE
Creating e2e test for Secrets API 

### PR DESCRIPTION
**Pull request by cmendible**
# Description

Creating e2e test for Secrets API 

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1081

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by cmendible** [comment]
@yaron2 can you add /ok-to-test to see how it goes?

**Comment by cmendible** [comment]
> End-to-end tests failed.

@yaron2  guess it was the new test that failed. It's an issue related to the service account not being able to read the secrets.

**Comment by yaron2** [comment]
This is great, thanks @cmendible

**Pull request merged**
