### PR TITLE
make state key prefix configurable by state component yaml

### PR DESCRIPTION
**Pull request by skyao**
# Description

Make state key prefix configurable by state component yaml.

## Issue reference

Discussed in this issue:

https://github.com/dapr/components-contrib/issues/542

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
This generally looks good, I'll finish reviewing tomorrow. Can you update the end to end test for this scenario? If you think this is too much for this PR we can do it in a separate one.

**Comment by skyao** [comment]
> This generally looks good, I'll finish reviewing tomorrow.

Hi, you need to make one decision: should we add prefix to the state key by default?  

In this PR I follow the current design of daprd to add prefix. But I strongly sugguest to disable this feature by default and only enable it when people really want it and set it in config. 

If you agree with this, I will change the implmentation and update this PR.

**Comment by skyao** [comment]
> Can you update the end to end test for this scenario? If you think this is too much for this PR we can do it in a separate one.

It is realy too big for one PR since the e2e test case need to add many test case to cover all the prefix strategy. 

For unit test, I cover all of the strategies in state_config_test.go ( state_config.go now is 100% covered by ut).

**Comment by yaron2** [comment]
@skyao can you fix the linter issue?

**Comment by skyao** [comment]
> @skyao can you fix the linter issue?

Linter fixed.

Should we change the default behaivor from "appid prefix" to "none prefix"? I suggust to no prefix by default so there is no surprise for the peaples who use dapr to access the exist shared state.

**Comment by yaron2** [comment]
> > @skyao can you fix the linter issue?
> 
> Linter fixed.
> 
> Should we change the default behaivor from "appid prefix" to "none prefix"? I suggust to no prefix by default so there is no surprise for the peaples who use dapr to access the exist shared state.

Current behavior should be the default.

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
@skyao can you please submit a docs PR for this?

**Review by yaron2 — APPROVED** [review]

**Comment by skyao** [comment]
> @skyao can you please submit a docs PR for this?

OK, where should we put docs for this?

**Comment by yaron2** [comment]
> > @skyao can you please submit a docs PR for this?
> 
> OK, where should we put docs for this?

Best to add a new How-To tutorial [here](https://docs.dapr.io/developing-applications/building-blocks/state-management/) labeled "How-To: Configure state sharing policies"

**Pull request merged**
