### PR TITLE
Added command line flag for health check port

### PR DESCRIPTION
**Pull request by abelperezok**
Signed-off-by: Abel Perez Martinez <abelperezok@gmail.com>

# Description

This pull request is a follow up from issue https://github.com/dapr/dapr/issues/4141 I changed the constant value `8080` and put a variable instead, this variable is populated from the command line flag `healthz-port` and defaults to `8080` if not passed in the command line. 

This is one first step towards offering more flexibility to deploy this injector in a wider range of setups. Once this change is in place, I'll submit another PR to allow passing this value via helm chart. 

## Issue reference

Please reference the issue this PR will close: #4141

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests N/A
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by abelperezok** [comment]
Could anyone retry the failed E2E ? based on the error details from the log, it seems totally unrelated to the change in this PR.

**Comment by daixiang0** [comment]
@artursouza please help track /ok-to-test :)

**Review by daixiang0 — APPROVED** [review]

**Comment by abelperezok** [comment]
Thanks, @yaron2 do you guys create pre-release docker images? This is so I point to an image with my change enabled and I can start adding the changes to helm to allow a separate healthz port.

**Pull request merged**
