### PR TITLE
actor state get and save should return 400 if actor doesn't exist

### PR DESCRIPTION
**Pull request by LMWF**
# Description

The api spec says state get/save calls should return 400 if the actor does not exist.  

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1991

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
This is actually a docs issue. We made a blanket decision in the past to not use 404 for the server APIs.

This change will make this API different from the other endpoints.

**Comment by LMWF** [comment]
What should it return in this case then? 500?

**Comment by yaron2** [comment]
The other APIs return 400 which signals a bad request, for missing entities.

**Comment by LMWF** [comment]
Ok I'll leave it at 400.  The get api still needs the change there though it'll change it to 400.  Without it, it returns 204 today for "key not present".  I think an actor not being there supersedes the key not being there.

**Review by yaron2 — APPROVED** [review]
LGTM

**Pull request merged**
