### PR TITLE
Dns policy

### PR DESCRIPTION
**Pull request by ls-2018**
# Description
some unexpected operation caused the source PR to shut down, now reopen this.
 
- https://github.com/dapr/dapr/pull/4264
## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by ls-2018** [comment]
/c @yaron2 checks already fix .
image

**Comment by yaron2** [comment]
@ls-2018 I think it's best to open a new PR, you've brought in unrelated commits that caused 154 changed files.

**Pull request closed without merging**
