### PR TITLE
Renaming Distributed Lock API UnlockResponse.Status.

### LINKED ISSUE #4988: Renaming Distributed Lock API UnlockResponse.Status
While writing the Python SDK bindings for the Distributed Lock (dapr/python-sdk#43), a discussion arose regarding the naming of fields: `LOCK_UNEXIST ` and `LOCK_BELONG_TO_OTHERS`.

https://github.com/dapr/dapr/blob/1fdc9a151956f061677258479965af61cb34ddf3/dapr/proto/runtime/v1/dapr.proto#L592-L593

The main concerns are:
1. There is a typo/grammar error  in `LOCK_BELONG_TO_OTHERS`. It should read `_BELONGS_`, 3rd person singular, as in `LOCK_BELONGS_TO_OTHERS`.
2. While not necessarily wrong, `LOCK_UNEXIST` does not sound natural. It should be `UNEXISTENT_LOCK` or, too keep consistency,  `LOCK_DOES_NOT_EXIST`.

## Suggested fix

```diff
--- a/dapr/proto/runtime/v1/dapr.proto
+++ b/dapr/proto/runtime/v1/dapr.proto
@@ -589,10 +589,10 @@ message UnlockRequest {
 message UnlockResponse {
   enum Status {
     SUCCESS = 0;
-    LOCK_UNEXIST = 1;
-    LOCK_BELONG_TO_OTHERS = 2;
+    LOCK_DOES_NOT_EXIST = 1;
+    LOCK_BELONGS_TO_OTHERS = 2;
     INTERNAL_ERROR = 3;
   }

   Status status = 1;
}
```
## Impact

Regarding client impact, usage of the Distributed Lock API comes with the following warning:

>  The Distributed Lock API is an Alpha version and  is subject to change. 

That said, I don't know if this change would require a process similar to a deprecation notice.

SDKs that implement this API would need to be updated to accommodate for these renames. If those SDKs expose these status enums as-is, they too would need to be updated. At this point this would impact Java, Go, .Net, JS and Python SDK.

### PR DESCRIPTION
**Pull request by tmacam**
# Description

While writing the Python SDK bindings for the Distributed Lock
(dapr/python-sdk#43), a discussion arose regarding the naming of fields:
`LOCK_UNEXIST ` and `LOCK_BELONG_TO_OTHERS`.

https://github.com/dapr/dapr/blob/1fdc9a151956f061677258479965af61cb34ddf3/dapr/proto/runtime/v1/dapr.proto#L592-L593

The main concerns are:
1. There is a typo/grammar error  in `LOCK_BELONG_TO_OTHERS`.
   It should read `_BELONGS_`, 3rd person singular, as in
   `LOCK_BELONGS_TO_OTHERS`.
2. While not necessarily wrong, `LOCK_UNEXIST` does not sound natural.
   It should be `UNEXISTENT_LOCK` or, too keep consistency,
   `LOCK_DOES_NOT_EXIST`.

This PR addresses this issue by renaming those fields as suggested
above.

Go gRPC client and protocol buffer generated code was updated
accordingly.

## Issue reference

Please reference the issue this PR will close: #4988 

## Impact

Regarding client impact, usage of the Distributed Lock API comes with
the following warning:

>  The Distributed Lock API is an Alpha version and is
> subject to change.

That said, I don't know if this change would require a process similar
to a deprecation notice.

SDKs that implement this API would need to be updated to accommodate
for these renames. If those SDKs expose these status enums as-is, they
too would need to be updated. At this point this would impact Java, Go,
.Net, JS and Python SDK.

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] ~~Created/updated tests~~  There are no referring to these enums, nothing to change/
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [x] ~~Extended the documentation~~ No mention to these enums in https://docs.dapr.io/developing-applications/building-blocks/distributed-lock/
* [x] ~~Specification has been updated~~ Does not apply
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by berndverst** [comment]
Addressed the Fossa failure in the Fossa Portal. Please have an approver or maintainer rerun that test.

**Review by halspang — APPROVED** [review]
Change seems fine. Though it'll be important to see how any SDK who has implemented this already handles the enum. For instance, the .NET SDK examines it directly to pass back a domain object to the user.

Can you make an issue in that repo about it and reference this: https://github.com/dapr/dotnet-sdk/blob/master/src/Dapr.Client/DaprClientGrpc.cs#L1436

**Comment by berndverst** [comment]
I also asked him to file issues in every SDK repo to update the proto and make sure to use the updated enum name.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yaron2** [comment]
> I also asked him to file issues in every SDK repo to update the proto and make sure to use the updated enum name.

Thanks.

**Comment by tmacam** [comment]
> I also asked him to file issues in every SDK repo to update the proto and make sure to use the updated enum name.

Tracking the impact of this change in the SDKs under with the following issues:

Affected SDK |  Issue 
-|-
[dapr/dotnet-sdk](https://github.com/dapr/dotnet-sdk)| ?
[dapr/python-sdk](https://github.com/dapr/python-sdk) |?
[dapr/js-sdk](https://github.com/dapr/js-sdk) | ?
[components-contrib](https://github.com/dapr/components-contrib)| ?
Java| ?
C++|?
Rust|?

Some SDKs, like Rust and C++ ones, only have a copy of the `.proto` itself but not code referencing those enums. What is the process for those? Updating the .proto itself?

Java only references those enums in [documentation/`.html` files](https://github.com/dapr/java-sdk/blob/cff90c0015e5ffee0e82b56f50a9d8892c4416f5/docs/io/dapr/v1/DaprProtos.UnlockResponse.Status.html#L122-L124).

For the record, the following searches can be used to track impact within Dapr-org owned repositories:
* [`LOCK_BELONG_TO_OTHERS`](https://github.com/search?l=&q=org%3Adapr+LOCK_BELONG_TO_OTHERS+NOT+extension%3Ahtml+NOT+extension%3Aproto&type=code)
* [`LOCK_UNEXIST `](https://github.com/search?l=&q=org%3Adapr+LOCK_UNEXIST+NOT+extension%3Ahtml+NOT+extension%3Aproto&type=code)
* [`LockBelongToOthers`](https://github.com/search?l=&q=org%3Adapr+LockBelongToOthers+NOT+extension%3Ahtml+NOT+extension%3Aproto&type=code)
* [`LockUnexist`](https://github.com/search?l=&q=org%3Adapr+LockUnexist+NOT+extension%3Ahtml+NOT+extension%3Aproto&type=code)

**Pull request merged**
