### PR TITLE
Expose metrics port on Kubernetes service

### PR DESCRIPTION
**Pull request by jjcollinge**
# Description
Exposed the runtime metrics port in the Kubernetes pod and service.

## Issue reference

Please reference the issue this PR will close: #1053 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation
* [ ] Specification has been updated
* [ ] Provided sample for the feature

### CODE REVIEW

**Comment by jjcollinge** [comment]
Should we add some e2e tests for metrics i.e. we could test the default metrics endpoint, annotated metrics endpoint and disabled endpoints using the hellodapr app?

**Comment by youngbupark** [comment]
> Should we add some e2e tests for metrics i.e. we could test the default metrics endpoint, annotated metrics endpoint and disabled endpoints using the hellodapr app?

That's good suggestion. I would add simple e2e test for metric endpoint and check if it is generating metrics after sending some request to hellodapr app.

**Comment by yaron2** [comment]
I agree. The test code can port forward to the Dapr sidecar and scrap the metrics port.

**Comment by jjcollinge** [comment]
Ok I got something working today for HTTP and gRPC but it’s a bit more involved than I first thought. Will take another looking Monday to see if I can clean it up and then push.

**Comment by yaron2** [comment]
@jjcollinge I think it'd be beneficial to add prometheus annotations to the Dapr service, to enable automatic scraping from Prometheus. that'd save the user the trouble of manually adding those annotations to their deployments.

Sample:
```yaml
       apiVersion: v1
       kind: Service
       metadata:
         annotations:
           prometheus.io/scrape: 'true'
           prometheus.io/port: '8099'
         name: myService
       spec:
         ports:
         - name: metricsPrometheus
           targetPort: 8099
           port: 8099
           protocol: TCP
         - name: generalPort
           targetPort: 8443
           port: 8443
           protocol: TCP
```

**Comment by youngbupark** [comment]
> @jjcollinge I think it'd be beneficial to add prometheus annotations to the Dapr service, to enable automatic scraping from Prometheus. that'd save the user the trouble of manually adding those annotations to their deployments.
> 
> Sample:
> 
> ```yaml
>        apiVersion: v1
>        kind: Service
>        metadata:
>          annotations:
>            prometheus.io/scrape: 'true'
>            prometheus.io/port: '8099'
>          name: myService
>        spec:
>          ports:
>          - name: metricsPrometheus
>            targetPort: 8099
>            port: 8099
>            protocol: TCP
>          - name: generalPort
>            targetPort: 8443
>            port: 8443
>            protocol: TCP
> ```

Annotation vs ServiceMonitor. looks like promethues-operator maintainer encourages to use ServiceMonitor - https://github.com/coreos/prometheus-operator/issues/1547#issuecomment-401092041

**Comment by yaron2** [comment]
Not vs, in addition to. The stable chart for for Prometheus doesn't support Service Monitors, and the prom operator doesn't honor annotations.

By putting annotations, we give built in support for anyone using the stable chart, and if users are using the prom operator, they will deploy a Service Monitor.

**Comment by jjcollinge** [comment]
This will fail until we fix the mtls issue

**Comment by yaron2** [comment]
@youngbupark can we check why Helm for tests doesn't apply custom config? `mtls.enabled: false` in this case.

**Comment by youngbupark** [comment]
> @youngbupark can we check why Helm for tests doesn't apply custom config? `mtls.enabled: false` in this case.

mtls is enabled in e2e by default. btw, do we need to disable mtls to talk to dapr sidecar?

**Comment by jjcollinge** [comment]
If the test runner has the client certificate to call the gRPC API then we can leave it enabled I guess. Seems a little strange it was only an issue on the gRPC API and not HTTP API too.

**Comment by yaron2** [comment]
> If the test runner has the client certificate to call the gRPC API then we can leave it enabled I guess. Seems a little strange it was only an issue on the gRPC API and not HTTP API too.

mTLS is used for dapr to dapr calls, which is only done via gRPC.

**Comment by yaron2** [comment]
@jjcollinge there's a change you need to do on the caller side when calling Dapr via gRPC:

```go
tlsConfig := &tls.Config{
		InsecureSkipVerify: true,
	}

creds := credentials.NewTLS(tlsConfig)
conn, err := grpc.Dial(daprAddress, grpc.WithTransportCredentials(creds))
```

**Comment by yaron2** [comment]
Resolve conflicts

**Comment by jjcollinge** [comment]
e2e still failing for me with:
`rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"`
Will investigate later.

**Comment by yaron2** [comment]
e2e tests are running with mTLS enabled ever since 0.4.0 release, it's on by default.

**Comment by youngbupark** [comment]
@jjcollinge @yaron2 we do not apply mtls configuration. so mtls is enabled by default.

https://github.com/dapr/dapr/blob/8734b25aad5be32aef1838e84260e5c9a2bccd81/.github/workflows/dapr-test.yml#L114-L120

**Comment by yaron2** [comment]
Yes, that's what I wrote.. :)

**Comment by jjcollinge** [comment]
🙂 understood, think it was just my cluster had it left over from previous testing. Can we re-run the e2e to test if this is fixed please?

**Comment by yaron2** [comment]
> e2e still failing for me with:
> `rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"`
> Will investigate later.
> 
> EDIT: Looks like this caused because I added the tls config (InsecureSkipVerify) to the test client but the `default` config for the e2e test disabled mTLS. When I enable it the tests metrics test pass. I'll just check setting it to true doesn't break any other e2e tests and if not I'll change the config to enabled for the tests in https://github.com/dapr/dapr/blob/master/tests/config/dapr_mtls_off_config.yaml

The tests fail now on our infra, but they pass when you run it? that's interesting.

**Comment by jjcollinge** [comment]
Is this gRPC connection issue still?

**Comment by yaron2** [comment]
@youngbupark @jjcollinge I've looked up the error from the latest test run: `transport: authentication handshake failed: tls: first record does not look like a TLS handshake`.

It means that TLS is not enabled on the server, in our case the gRPC server, so it means this test was run with mTLS disabled somehow?

**Comment by yaron2** [comment]
Yeah, just verified. I ran the gRPC client against an mTLS-disabled Dapr and got the same error. It means the test ran with mTLS disabled.

**Comment by youngbupark** [comment]
> Yeah, just verified. I ran the gRPC client against an mTLS-disabled Dapr and got the same error. It means the test ran with mTLS disabled.

Let's add the additional step to print out the default configuration. https://github.com/dapr/dapr/pull/1120/files

**Comment by yaron2** [comment]
There's a problem with the last commit, the kubectl command is wrong. This will fail all tests now.

**Comment by youngbupark** [comment]
@jjcollinge @yaron2 it is enabled:
```
Run kubectl get configurations default -n dapr-tests -o yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  creationTimestamp: "2020-02-26T18:18:45Z"
  generation: 1
  name: default
  namespace: dapr-tests
  resourceVersion: "11812573"
  selfLink: /apis/dapr.io/v1alpha1/namespaces/dapr-tests/configurations/default
  uid: 6d1b6ddd-58c4-11ea-bdaa-e2de3ce5cba4
spec:
  mtls:
    allowedClockSkew: 15m
    enabled: true
    workloadCertTTL: 24h
```

**Comment by yaron2** [comment]
> @jjcollinge @yaron2 it is enabled:
> 
> ```
> Run kubectl get configurations default -n dapr-tests -o yaml
> apiVersion: dapr.io/v1alpha1
> kind: Configuration
> metadata:
>   creationTimestamp: "2020-02-26T18:18:45Z"
>   generation: 1
>   name: default
>   namespace: dapr-tests
>   resourceVersion: "11812573"
>   selfLink: /apis/dapr.io/v1alpha1/namespaces/dapr-tests/configurations/default
>   uid: 6d1b6ddd-58c4-11ea-bdaa-e2de3ce5cba4
> spec:
>   mtls:
>     allowedClockSkew: 15m
>     enabled: true
>     workloadCertTTL: 24h
> ```

I'm gonna re-run the tests and monitor closely.

Both @jjcollinge and I have the tests passing when we run them, and I can reproduce the test failing when I disable mTLS.

**Comment by yaron2** [comment]
I confirmed mTLS is disabled for e2e tests. I logged in to the test environment and pulled the logs from a `daprd` instance.

The configuration is set correctly, and the command argument is passed correctly into the container, but `daprd` shows that mtls is disabled and getting skipped.

**Comment by yaron2** [comment]
<a href="https://ibb.co/q1fHyPs">Screen-Shot-2020-02-26-at-12-10-57-PM</a>

**Comment by yaron2** [comment]
I have a suspect:

The argument `--log-as-json "false"` is stopping all the arguments that come after it.

**Comment by yaron2** [comment]
Yes, that's 99% the cause of the issue.

`--log-as-json` is defined in the sidecar injector, but isn't handled anywhere in: https://github.com/dapr/dapr/blob/938ddbecee0448b35845d26809103c4117a6d663/pkg/runtime/cli.go#L20

**Comment by yaron2** [comment]
Did some conflict resolution mojo. Lets see if my mutant makes sense..

**Comment by youngbupark** [comment]
> Did some conflict resolution mojo. Lets see if my mutant makes sense..

oh! I was resolving the conflict.. anyhow. thanks.

**Pull request merged**
