### PR TITLE
merge release-1.6 into master

### PR DESCRIPTION
**Pull request by dmitsh**
# Description

merge release-1.6 into master

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@dmitsh there's a conflict and failing DCO test.

**Comment by berndverst** [comment]
@yaron2 I'll work with @dmitsh to address this. Will update this PR in a bit.

**Review by berndverst — APPROVED** [review]

**Comment by dmitsh** [comment]
> @dmitsh there's a conflict and failing DCO test.

addressed

**Comment by berndverst** [comment]
@yaron2 @artursouza  -- this can be merged. DO NOT SQUASH MERGE.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
