### PR TITLE
add resources

### LINKED ISSUE #2325: Add resources by default
As stated [here](https://github.com/dapr/docs/tree/master/howto/deploy-k8s-prod#cluster-capacity-requirements) 

Deployment | CPU | Memory
-- | -- | --
Operator | Limit: 1, Request: 100m | Limit: 200Mi, Request: 20Mi
Sidecar Injector | Limit: 1, Request: 100m | Limit: 200Mi, Request: 20Mi
Sentry | Limit: 1, Request: 100m | Limit: 200Mi, Request: 20Mi
Placement | Limit: 1, Request: 250m | Limit: 500Mi, Request: 100Mi
Dashboard | Limit: 200m, Request: 50m | Limit: 200Mi, Request: 20Mi

In the chart's *[README.md](https://github.com/dapr/dapr/blame/master/charts/dapr/README.md#L21-L22)* states 

>_**Resources Required**_
> _The chart deploys pods that consume minimum resources as specified in the resources configuration parameter._

However, I see no `resources` value set in the deployments [here](https://github.com/dapr/dapr/tree/master/charts/dapr/charts)

Please automatically set the limits/requests in the charts by default.

### PR DESCRIPTION
**Pull request by cilerler**
# Description

Added default recommended requests and limits

## Issue reference

Closes #2325

### CODE REVIEW

**Comment by cilerler** [comment]
Not sure why it is skipping the `dapr / Publish helm charts to Helm GitHub pages repo (pull_request)` it seems to be the only relevant one based on my changes.

Plus, no idea how/why **End-to-end tests failed on Linux** since my changes should only affect the Helm charts.

Please advise

**Comment by yaron2** [comment]
I think we have a problem with one of our test clusters, looks like this isn't related to the PR.

**Comment by cilerler** [comment]
@yaron2, who is going to deploy it to the [helm-charts repo](https://github.com/dapr/helm-charts)? 
Wondering besides waiting for that cluster to be rebooted, is there anything else I should do?

**Comment by yaron2** [comment]
> @yaron2, who is going to deploy it to the [helm-charts repo](https://github.com/dapr/helm-charts)?
> Wondering besides waiting for that cluster to be rebooted, is there anything else I should do?

It will be pushed with the next release, 1.0-rc1.

**Review by yaron2 — APPROVED** [review]
LGTM

**Comment by yaron2** [comment]
Thanks for this @cilerler

**Pull request merged**
