### PR TITLE
Added healthzPort option to injector helm chart - defaults to 8080

### PR DESCRIPTION
**Pull request by abelperezok**
# Description

Following from https://github.com/dapr/dapr/issues/4174 now that the health check port can be passed via command line argument, this PR adds the value to the chart so it can be set at deployment time. 

When this is not used in combination with `hostNetwork: true` it doesn't make any difference since the ports are not exposed at node level. The main motivation for this setting is in combination with `hostNetwork: true`.

To use this, add the `healthzPort: 8091` to any arbitrary port that is available in your node, assuming you have other apps already using port 8080. 

* Using values.yaml file:
  ```
  helm upgrade --install dapr . \
    --namespace dapr-system \
    --create-namespace \
    --values values.yaml
  ``` 
  `values.yaml`
  ```yaml
  # only needed while not part of a release
  global:
    tag: "edge"

  dapr_sidecar_injector:
    hostNetwork: true
    healthzPort: 8091
  ```
* Using command line:

  ```
  helm upgrade --install dapr . \
    --namespace dapr-system \
    --create-namespace \
    --set global.tag=edge \
    --set dapr_sidecar_injector.hostNetwork=true \
    --set dapr_sidecar_injector.healthzPort=8091
  ```

At this point, it only works with the "edge" tag, when this is part of the main line it won't be necessary, meanwhile, make sure you use the latest docker image. 

## Issue reference

Please reference the issue this PR will close: #_[4174]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [x] Extended the documentation / Modified helm chart README 
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@abelperezok version 1.6 is already locked down and released, so please change back to `master` branch. this will go out in 1.7.

**Comment by abelperezok** [comment]
> @abelperezok version 1.6 is already locked down and released, so please change back to `master` branch. this will go out in 1.7.

@yaron2 In `master` branch the E2E won't run - I presume the changes from 1.6 are not there yet. I'll do it now

**Comment by abelperezok** [comment]
@yaron2 I tied to follow the steps from https://github.com/dapr/dapr/pull/4179/checks?check_run_id=5008954459 to correct the missing sign off from my commit, but I get a merge conflict in file go.mod which is not part of any of my commits, what should I do ?

**Comment by abelperezok** [comment]
I created another PR much cleaner without this back and forth with the branch release-1.6. https://github.com/dapr/dapr/pull/4181
Closing this one, apologies for the disruption created.

**Pull request closed without merging**
