### PR TITLE
Enable PR gating on unit test coverage regressions (#2262)

### PR DESCRIPTION
**Pull request by wcs1only**
# Description

Turn on PR gating based on codecov. For now, the rule is, no PR should reduce unit test coverage.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2262 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by tcnghia — APPROVED** [review]
I think we _probably_ want to keep the patch coverage disabled or configure it somehow, otherwise it will fail everytime the patch has uncovered line I think.

We can try it out and tune later in a future PR too.

**Comment by wcs1only** [comment]
> I think we _probably_ want to keep the patch coverage disabled or configure it somehow, otherwise it will fail everytime the patch has uncovered line I think.
> 
> We can try it out and tune later in a future PR too.

Really? Let me have a more careful read of the codecov docs. That seems an incredibly aggressive default. We just enabled this on the python-sdk. Let me cook up a PR that increases code coverage, but introduces some untested lines and see if it passes or not.

**Comment by wcs1only** [comment]
So, I wrote up a bogus PR on the python SDK that introduces some new untested code, but still increases the overall coverage, and it passed as expected.

**Comment by tcnghia** [comment]
> So, I wrote up a bogus PR on the python SDK that introduces some new untested code, but still increases the overall coverage, and it passed as expected.

Thanks for verifying!

**Pull request merged**
