### PR TITLE
Add smtp output binding

### PR DESCRIPTION
**Pull request by EdwinVW**
# Description

This PR contains an SMTP output binding for sending email directly via SMTP.
See https://github.com/dapr/components-contrib/pull/646

## Issue reference

https://github.com/dapr/components-contrib/issues/645

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [x] Created issue in the https://github.com/dapr/docs/ repo: https://github.com/dapr/docs/issues/1145

### CODE REVIEW

**Comment by yaron2** [comment]
@EdwinVW please run:

`go get -u github.com/dapr/components-contrib@master`
`go mod tidy`

And push the changes.

**Comment by EdwinVW** [comment]
> @EdwinVW please run:
> 
> `go get -u github.com/dapr/components-contrib@master`
> `go mod tidy`
> 
> And push the changes.

@yaron2 Done.

I did receive an error that the smtp package could not be found. But I recon this makes sense because the smtp binding package is not yet merged and published.

**Comment by yaron2** [comment]
> > @EdwinVW please run:
> > `go get -u github.com/dapr/components-contrib@master`
> > `go mod tidy`
> > And push the changes.
> 
> @yaron2 Done.
> 
> I did receive an error that the smtp package could not be found. But I recon this makes sense because the smtp binding package is not yet merged and published.

Sorry, I jumped the gun. didn't notice we didn't merge it in contrib yet. It's merged now, please re-do the steps and push the changes.

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
Congrats and thanks @EdwinVW

**Pull request merged**
