### PR TITLE
remove redundant metadata

### PR DESCRIPTION
**Pull request by beiwei30**
# Description

fix issue https://github.com/dapr/dapr/issues/2136

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [x] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by tcnghia** [comment]
LGTM

cc @youngbupark @mukundansundar who are driving the 0.11 release

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
This doesn't need a backport to 0.11.

**Review by youngbupark — APPROVED** [review]

**Review by yaron2 — APPROVED** [review]
lgtm

**Pull request merged**
