### PR TITLE
Add DeleteBulkState() method in dapr runtime

### PR DESCRIPTION
**Pull request by skyao**
# Description

Add DeleteBulkState() method in dapr runtime

## Issue reference

https://github.com/dapr/dapr/issues/2658

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by yaron2 — APPROVED** [review]
lgtm

**Comment by yaron2** [comment]
hey @skyao, I approved the PR but after updating with master there's a conflict. Please resolve and we can then merge.

**Comment by yaron2** [comment]
Linter is failing.

This morning we merged a PR that makes some changes to proto generation, it might be related:

https://github.com/dapr/dapr/blob/master/dapr/README.md#proto-client-generation

**Comment by skyao** [comment]
> Linter is failing.
> 
> This morning we merged a PR that makes some changes to proto generation, it might be related:
> 
> https://github.com/dapr/dapr/blob/master/dapr/README.md#proto-client-generation

Thank you. Done!

**Review by yaron2 — DISMISSED** [review]
lgtm

**Comment by yaron2** [comment]
@skyao why did you close this?

**Comment by yaron2** [comment]
It wasn't merged yet..

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
