### PR TITLE
Fix typos in comments

### PR DESCRIPTION
**Pull request by luckyxiaoqiang**
# Description

Fix typos in comments of `diagnostics` package.

### CODE REVIEW

**Review by membphis — APPROVED** [review]

**Comment by membphis** [comment]
ci failed, maybe you can merge the `master` branch

**Comment by luckyxiaoqiang** [comment]
> ci failed, maybe you can merge the `master` branch

It is update to date with `master` branch.

**Review by mukundansundar — APPROVED** [review]

**Comment by yaron2** [comment]
Thanks for your contribution @luckyxiaoqiang

**Pull request merged**
