### PR TITLE
Register alicloud nacos binding component

### PR DESCRIPTION
**Pull request by liu-song**
# Description
It seems that  forgot to add,  Add alicloud nacos binding component
https://github.com/dapr/components-contrib/tree/master/bindings/nacos

## Issue reference

Please reference the issue this PR will close: #_[https://github.com/dapr/dapr/issues/5873]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by mukundansundar — DISMISSED** [review]

**Comment by liu-song** [comment]
I just realized there is an issue with the nacos-go-sdk and I will try to confirm  it.https://github.com/dapr/dapr/issues/5873

**Comment by liu-song** [comment]
First, let's review the previous issue and the code fragment that was fixed.
https://github.com/dapr/dapr/pull/3212

nacos-sdk-go issue
https://github.com/nacos-group/nacos-sdk-go/issues/250

nacos-sdk-go fix
https://github.com/nacos-group/nacos-sdk-go/pull/251/files

Before the issue was fixed, the nacos-go-sdk would initialize a map and establish a goroutine during the init() function. 
https://github.com/nacos-group/nacos-sdk-go/pull/251/files#diff-3f155c99c6b9cfd0acfbb7bcc7a22c3384d0c5400130670f6966ef899de0a7fdL79-R81
After the fix, the map and goroutine are only created when they are actually used, which ensures that the nacos component does not consume additional resources in Dapr when it is not being used.

**Comment by liu-song** [comment]
At the same time, I also monitored the differences between running the nacos-go-sdk with the same code before the fix and with the latest version.
before fix
code
https://github.com/liu-song/registry-nacos/tree/beforefix/example/basic/server
nacos-go-sdk version
https://github.com/liu-song/registry-nacos/blob/beforefix/go.mod#L9
latest  versioin
code 
https://github.com/liu-song/registry-nacos/blob/latest/example/basic/server/main.go
nacos-go-sdk version
https://github.com/liu-song/registry-nacos/blob/latest/go.mod#L10

image

**Comment by liu-song** [comment]
The above code is a simple example using Kitex as an RPC framework and Nacos for service registration and discovery. The section before the blue dotted line shows the code running with the "beforefix" version, and the section after the line shows the code running with the latest version.

My computer has a configuration of 16GB RAM and 8 cores. From the graph, we can observe that the memory usage of the program ranges from 0.1% to 0.13%, the number of goroutines ranges from 11 to 16, and the CPU usage ranges from 0% to 2%, with most of the time spent at 1%.

One noteworthy point is that the latest version has reduced the number of times the CPU usage reaches 2%, indicating that the new version of nacos-go-sdk can reduce some CPU consumption. Overall, using nacos-go-sdk correctly does not result in excessive resource consumption.

Finally, if the binding  nacos is actually applied and brings additional resource consumption, providing more code information, conditions for reproduction, or pprof data can help us address the issue and make nacos-go-sdk more robust.

**Comment by liu-song** [comment]
Could you please review this issue again?   :grin:
@shubham1172 @yaron2 @berndverst @mukundansundar

**Comment by liu-song** [comment]
Do I need to provide any other additional information?

**Comment by ItalyPaleAle** [comment]
I think we still need this?

**Comment by ItalyPaleAle** [comment]
Are we still interested in this? Otherwise, I think we should just remove the component from components-contrib

**Comment by liu-song** [comment]
There may not be a significant demand, so temporarily close it.

**Comment by ItalyPaleAle** [comment]
Opened https://github.com/dapr/components-contrib/pull/3118 to delete the component's code

**Pull request closed without merging**
