### PR TITLE
Update Windows versions in Dockerfiles for e2e apps

### PR DESCRIPTION
**Pull request by shubham1172**
# Description

With #5999, e2e pipeline was also updated to use Windows ltsc2022 images instead of 1809. The e2e pipeline started failing because e2e apps were still using 1809 images. Example https://github.com/dapr/dapr/actions/runs/4397834807/jobs/7701245210

This PR updates Dockerfiles from e2e apps to build ltsc2022 images.
Also updates actordotnet and actorpython apps to support Windows 2022.

Related issue: https://github.com/dapr/dapr/issues/5644

## Issue reference

Please reference the issue this PR will close: #NA

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by shubham1172** [comment]
@dapr/maintainers-dapr can this be merged?

**Comment by daixiang0** [comment]
@shubham1172 I not familiar with Win development, my concern is that do we mention about the minimum supported version of Windows/Windows image?

I think we should point it out and make all tests sync to it.

**Comment by shubham1172** [comment]
> @shubham1172 I not familiar with Win development, my concern is that do we mention about the minimum supported version of Win/Win image?
> 
> I think we should point it out and make all tests sync to it.

Hi @daixiang0, with #5999 and this PR, only a new image has been added (Windows 2022) and is being used in our e2e tests as well. The older image 1809's deprecation will be tracked separately. We can document the minimum supported version and set 1809 on a deprecation path. We can also explore adding Windows 2019 LTS image when we remove 1809.

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by mukundansundar** [comment]
@shubham1172 a question on this, we are no longer going to test the apps against 1809 version of windows?

**Comment by shubham1172** [comment]
> @shubham1172 a question on this, we are no longer going to test the apps against 1809 version of windows?

That is correct. 1809 has reached EOL already and we should remove it from Dapr as well. Going forward our e2e tests will run on 2022.

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by shubham1172** [comment]
@mukundansundar I fixed a typo, seems to be working now.

**Comment by shubham1172** [comment]
@mukundansundar can we merge this now?

**Review by DeepanshuA — APPROVED** [review]

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
