### PR TITLE
Add grpc perf test for service invoke

### PR DESCRIPTION
**Pull request by skyao**
# Description

Add grpc perf test case for service invoke. 

## Issue reference

https://github.com/dapr/dapr/issues/1787

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@skyao we need to add you to Daprbot for you to run tests. Open a PR like the one here https://github.com/dapr/dapr/pull/4487/files and I'll merge it.

**Comment by yaron2** [comment]
> /ok-to-perf

It's running :)

https://github.com/dapr/dapr/actions/runs/2141001279

**Comment by yaron2** [comment]
Also, see this: https://github.com/dapr/dapr/issues/1787#issuecomment-1093059733

**Comment by skyao** [comment]
> 

The new added perf test case of service_invocation_grpc is NOT included.

Selection_004

I have updated `tests/dapr_tests.mk` file to add service_invocation_grpc:

Selection_005

**Comment by skyao** [comment]
OK. I found it, the dapr-perf.yml file in .github/workflow need to update.

**Comment by yaron2** [comment]
Still doesn't seem to be added to the workflow...

**Comment by skyao** [comment]
@yaron2 Why the perf test I trigged by "ok-to-perf" didn't run real test case:

https://github.com/dapr/dapr/actions/runs/2141368410
https://github.com/dapr/dapr/actions/runs/2143138603

**Comment by skyao** [comment]
> 

Hi, yaron, I triggered the perf test two times:

Selection_006

- #8407: https://github.com/dapr/dapr/actions/runs/2143139173
- #8408: https://github.com/dapr/dapr/actions/runs/2143158740

From the page, we can see the workflow file of dapr-perf:

Selection_007

It seems that the perf test will always use the master branch to get the workflow file, not the branch I submit the PR. That's why my new added service_invocation_grpc test case is not included in the perf test.

**Comment by skyao** [comment]
/ok-to-test

Trigger e2e test.

**Comment by yaron2** [comment]
@skyao is this PR ready to merge?

**Comment by yaron2** [comment]
@skyao as next step,.let's fork Fortio into the Dapr org so we can rely on that repo instead of your personal fork.

**Comment by skyao** [comment]
> @skyao as next step,.let's fork Fortio into the Dapr org so we can rely on that repo instead of your personal fork.

OK. You can fork fortio in dapr orgnization first, and I will PR on that forked repo, then I will update the repo address.

**Comment by skyao** [comment]
Service invocation by gRPC even slower than HTTP: 

Screen Shot 2022-04-12 at 07 06 33

Screen Shot 2022-04-12 at 07 06 13

**Pull request merged**
