### PR TITLE
Updated python script to find latest release version and set env var

### PR DESCRIPTION
**Pull request by ChaosInTheCRD**
# Description

This PR modifies one of the python scripts used in the Github Actions Workflows to fix the issue mentioned in https://github.com/dapr/dapr/issues/5625. It defines a boolean function that checks the `.md` file names in `docs/release_notes` to find semantic versions (minus `-rc` release candidates) and compares the highest version against the release version being inputted to the script.

This was required as the script currently was not actually checking whether the release was the latest version, and instead just validating that the provided version had a release note against it and that it wasn't an `-rc` release. This introduces issues with the `:latest` image tag when a patch for a previous major version (e.g., `1.9.*`) is released.

## Issue reference

Please reference the issue this PR will close: #5625

## Checklist

I tested the code locally but there are no unit / end-to-end tests that exist, since it is just a workflow script.

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
Thanks a lot for this PR!

I am not good at Python so I can’t comment on the code, but the way you’ve approached the problem seems perfect.

**Comment by ChaosInTheCRD** [comment]
> Thanks a lot for this PR!
> 
> I am not good at Python so I can’t comment on the code, but the way you’ve approached the problem seems perfect.

No problem at all @ItalyPaleAle 😄 

If anyone knows if there is a standardised way of testing these scripts please let me know.

**Comment by ItalyPaleAle** [comment]
Testing scripts like these is particularly complex 🙃 Sometimes you can try them if you have a fork of Dapr by running them in your fork. That's how far as you can go normally.

**Review by artursouza — CHANGES_REQUESTED** [review]
At this point, can we have some sort of automated testing for this script? It is critical for our release process and it will help us not having regressions. Overall, no concerns but the test scenarios will really help.

**Comment by artursouza** [comment]
> > Thanks a lot for this PR!
> > I am not good at Python so I can’t comment on the code, but the way you’ve approached the problem seems perfect.
> 
> No problem at all @ItalyPaleAle 😄
> 
> If anyone knows whether there is a standardised way of testing these scripts please let me know.

I would test this via mechanical markdown, using a .md file. We use that for our quickstarts. You can set the environment variables before invoking the function and all with command line: https://github.com/dapr/quickstarts/blob/master/tutorials/hello-world/README.md

**Pull request closed without merging**
