### PR TITLE
Support rename reminder

### PR DESCRIPTION
**Pull request by CrazyHZM**
# Description

## Issue reference

Resolved https://github.com/dapr/dapr/issues/3273

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by beiwei30 — CHANGES_REQUESTED** [review]
Overall the change looks good to me. If RenameReminder can reuse more code from CreateReminder in actorsRuntime, it'll be better. I am not sure if it can be simplified to the following psuedocode:

```
a.DeleteReminder()
a.CreateReminder()
```

**Comment by CrazyHZM** [comment]
> Overall the change looks good to me. If RenameReminder can reuse more code from CreateReminder in actorsRuntime, it'll be better. I am not sure if it can be simplified to the following psuedocode:
> 
> ```
> a.DeleteReminder()
> a.CreateReminder()
> ```

At the beginning, I also thought about it this way, but later rejected this idea. The main reasons are as follows:
1. At present, `CreateReminder` also contains part of the `update` logic, and has done verification and calculation for each parameter, such as `TTL`, I think there is no need to re-check and calculate in the `RenameReminder` operation.
2. The `CreateReminderRequest` parameter in the `CreateReminder` operation is designed for `CreateReminder`, and there is no need to care about `TTL` and other parameters in the `RenameReminder` operation
@beiwei30 Do you have another opinion？

**Comment by beiwei30** [comment]
> > Overall the change looks good to me. If RenameReminder can reuse more code from CreateReminder in actorsRuntime, it'll be better. I am not sure if it can be simplified to the following psuedocode:
> > ```
> > a.DeleteReminder()
> > a.CreateReminder()
> > ```
> 
> At the beginning, I also thought about it this way, but later rejected this idea. The main reasons are as follows:
> 
> 1. At present, `CreateReminder` also contains part of the `update` logic, and has done verification and calculation for each parameter, such as `TTL`, I think there is no need to re-check and calculate in the `RenameReminder` operation.
> 2. The `CreateReminderRequest` parameter in the `CreateReminder` operation is designed for `CreateReminder`, and there is no need to care about `TTL` and other parameters in the `RenameReminder` operation
> 
> @beiwei30 Do you have another opinion？

or is it possible to reuse code between line 1054 - line 1093 between these two methods?

**Comment by CrazyHZM** [comment]
> > > Overall the change looks good to me. If RenameReminder can reuse more code from CreateReminder in actorsRuntime, it'll be better. I am not sure if it can be simplified to the following psuedocode:
> > > ```
> > > a.DeleteReminder()
> > > a.CreateReminder()
> > > ```
> > 
> > 
> > At the beginning, I also thought about it this way, but later rejected this idea. The main reasons are as follows:
> > 
> > 1. At present, `CreateReminder` also contains part of the `update` logic, and has done verification and calculation for each parameter, such as `TTL`, I think there is no need to re-check and calculate in the `RenameReminder` operation.
> > 2. The `CreateReminderRequest` parameter in the `CreateReminder` operation is designed for `CreateReminder`, and there is no need to care about `TTL` and other parameters in the `RenameReminder` operation
> > 
> > @beiwei30 Do you have another opinion？
> 
> or is it possible to reuse code between line 1054 - line 1093 between these two methods?

@beiwei30 Done.

**Review by beiwei30 — APPROVED** [review]
LGTM now.

**Comment by artursouza** [comment]
@CrazyHZM This needs E2E tests, changes to SDKs and documentation. Right now, this feature cannot be used.

**Comment by artursouza** [comment]
@yaron2 Shouldn't this API be suffixed with Alpha?

**Comment by CrazyHZM** [comment]
> @CrazyHZM This needs E2E tests, changes to SDKs and documentation. Right now, this feature cannot be used.

I will be doing this part in the near future
@artursouza

**Pull request merged**
