### PR TITLE
Components now use SecretKeyRef.Name if SecretKeyRef.Key isn't set

### PR DESCRIPTION
**Pull request by lynn-orrell**
## Issue reference

#1283 

Please reference the issue this PR will close: #1283

### CODE REVIEW

**Comment by yaron2** [comment]
You need to fix the tests:
https://github.com/dapr/dapr/pull/1284/checks?check_run_id=518309669

**Comment by amanbha** [comment]
@lynn-orrell Could you please fix the unit test https://github.com/dapr/dapr/pull/1284/checks?check_run_id=531659208
You can run tests locally on your machine by running "make test"  
https://github.com/dapr/dapr/blob/master/docs/development/developing-dapr.md#run-unit-tests

**Comment by youngbupark** [comment]
@lynn-orrell please double-check the dependency of `DefaultSecretRefKeyName` in component-contrib.

**Comment by yaron2** [comment]
> @lynn-orrell please double-check the dependency of `DefaultSecretRefKeyName` in component-contrib.

Its only used in Google KMS which isn't registered and needs to be removed completely from `components-contrib` now that `GCP Secret Manager` is in.

**Pull request merged**
