### PR TITLE
Pin contrib for ASB and update apache dubbo replacement to address CVE

### PR DESCRIPTION
**Pull request by berndverst**
Signed-off-by: Bernd Verst <github@bernd.dev>

# Description

Addresses a CVE in the Dubbo Binding. https://github.com/dapr/components-contrib/issues/2425

### CODE REVIEW

**Comment by berndverst** [comment]
@ItalyPaleAle @jjcollinge @yaron2 using this PR to see if the ASB changes address the E2E test failure.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
