### PR TITLE
Perf test for actor activation in Java.

### PR DESCRIPTION
**Pull request by artursouza**
# Description

Perf test for actor activation in Java.
Added feature to Fortio in fork repo, allowing Fortio to invoke a URL with a different ID on every request.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1386 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [X] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by artursouza** [comment]
Perf test will not pass until the new workflow file is merged.

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
